/*
rh-trex-ai Service API

rh-trex-ai Service API

API version: 0.0.1
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package openapi

import (
	"bytes"
	"encoding/json"
	"fmt"
)

// checks if the FossilList type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &FossilList{}

// FossilList struct for FossilList
type FossilList struct {
	Kind  string   `json:"kind"`
	Page  int32    `json:"page"`
	Size  int32    `json:"size"`
	Total int32    `json:"total"`
	Items []Fossil `json:"items"`
}

type _FossilList FossilList

// NewFossilList instantiates a new FossilList object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewFossilList(kind string, page int32, size int32, total int32, items []Fossil) *FossilList {
	this := FossilList{}
	this.Kind = kind
	this.Page = page
	this.Size = size
	this.Total = total
	this.Items = items
	return &this
}

// NewFossilListWithDefaults instantiates a new FossilList object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewFossilListWithDefaults() *FossilList {
	this := FossilList{}
	return &this
}

// GetKind returns the Kind field value
func (o *FossilList) GetKind() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Kind
}

// GetKindOk returns a tuple with the Kind field value
// and a boolean to check if the value has been set.
func (o *FossilList) GetKindOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Kind, true
}

// SetKind sets field value
func (o *FossilList) SetKind(v string) {
	o.Kind = v
}

// GetPage returns the Page field value
func (o *FossilList) GetPage() int32 {
	if o == nil {
		var ret int32
		return ret
	}

	return o.Page
}

// GetPageOk returns a tuple with the Page field value
// and a boolean to check if the value has been set.
func (o *FossilList) GetPageOk() (*int32, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Page, true
}

// SetPage sets field value
func (o *FossilList) SetPage(v int32) {
	o.Page = v
}

// GetSize returns the Size field value
func (o *FossilList) GetSize() int32 {
	if o == nil {
		var ret int32
		return ret
	}

	return o.Size
}

// GetSizeOk returns a tuple with the Size field value
// and a boolean to check if the value has been set.
func (o *FossilList) GetSizeOk() (*int32, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Size, true
}

// SetSize sets field value
func (o *FossilList) SetSize(v int32) {
	o.Size = v
}

// GetTotal returns the Total field value
func (o *FossilList) GetTotal() int32 {
	if o == nil {
		var ret int32
		return ret
	}

	return o.Total
}

// GetTotalOk returns a tuple with the Total field value
// and a boolean to check if the value has been set.
func (o *FossilList) GetTotalOk() (*int32, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Total, true
}

// SetTotal sets field value
func (o *FossilList) SetTotal(v int32) {
	o.Total = v
}

// GetItems returns the Items field value
func (o *FossilList) GetItems() []Fossil {
	if o == nil {
		var ret []Fossil
		return ret
	}

	return o.Items
}

// GetItemsOk returns a tuple with the Items field value
// and a boolean to check if the value has been set.
func (o *FossilList) GetItemsOk() ([]Fossil, bool) {
	if o == nil {
		return nil, false
	}
	return o.Items, true
}

// SetItems sets field value
func (o *FossilList) SetItems(v []Fossil) {
	o.Items = v
}

func (o FossilList) MarshalJSON() ([]byte, error) {
	toSerialize, err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o FossilList) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["kind"] = o.Kind
	toSerialize["page"] = o.Page
	toSerialize["size"] = o.Size
	toSerialize["total"] = o.Total
	toSerialize["items"] = o.Items
	return toSerialize, nil
}

func (o *FossilList) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"kind",
		"page",
		"size",
		"total",
		"items",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err
	}

	for _, requiredProperty := range requiredProperties {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varFossilList := _FossilList{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varFossilList)

	if err != nil {
		return err
	}

	*o = FossilList(varFossilList)

	return err
}

type NullableFossilList struct {
	value *FossilList
	isSet bool
}

func (v NullableFossilList) Get() *FossilList {
	return v.value
}

func (v *NullableFossilList) Set(val *FossilList) {
	v.value = val
	v.isSet = true
}

func (v NullableFossilList) IsSet() bool {
	return v.isSet
}

func (v *NullableFossilList) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableFossilList(val *FossilList) *NullableFossilList {
	return &NullableFossilList{value: val, isSet: true}
}

func (v NullableFossilList) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableFossilList) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
