/*
rh-trex-ai Service API

rh-trex-ai Service API

API version: 0.0.1
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package openapi

import (
	"encoding/json"
)

// checks if the ScientistPatchRequest type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &ScientistPatchRequest{}

// ScientistPatchRequest struct for ScientistPatchRequest
type ScientistPatchRequest struct {
	Name  *string `json:"name,omitempty"`
	Field *string `json:"field,omitempty"`
}

// NewScientistPatchRequest instantiates a new ScientistPatchRequest object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewScientistPatchRequest() *ScientistPatchRequest {
	this := ScientistPatchRequest{}
	return &this
}

// NewScientistPatchRequestWithDefaults instantiates a new ScientistPatchRequest object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewScientistPatchRequestWithDefaults() *ScientistPatchRequest {
	this := ScientistPatchRequest{}
	return &this
}

// GetName returns the Name field value if set, zero value otherwise.
func (o *ScientistPatchRequest) GetName() string {
	if o == nil || IsNil(o.Name) {
		var ret string
		return ret
	}
	return *o.Name
}

// GetNameOk returns a tuple with the Name field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ScientistPatchRequest) GetNameOk() (*string, bool) {
	if o == nil || IsNil(o.Name) {
		return nil, false
	}
	return o.Name, true
}

// HasName returns a boolean if a field has been set.
func (o *ScientistPatchRequest) HasName() bool {
	if o != nil && !IsNil(o.Name) {
		return true
	}

	return false
}

// SetName gets a reference to the given string and assigns it to the Name field.
func (o *ScientistPatchRequest) SetName(v string) {
	o.Name = &v
}

// GetField returns the Field field value if set, zero value otherwise.
func (o *ScientistPatchRequest) GetField() string {
	if o == nil || IsNil(o.Field) {
		var ret string
		return ret
	}
	return *o.Field
}

// GetFieldOk returns a tuple with the Field field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ScientistPatchRequest) GetFieldOk() (*string, bool) {
	if o == nil || IsNil(o.Field) {
		return nil, false
	}
	return o.Field, true
}

// HasField returns a boolean if a field has been set.
func (o *ScientistPatchRequest) HasField() bool {
	if o != nil && !IsNil(o.Field) {
		return true
	}

	return false
}

// SetField gets a reference to the given string and assigns it to the Field field.
func (o *ScientistPatchRequest) SetField(v string) {
	o.Field = &v
}

func (o ScientistPatchRequest) MarshalJSON() ([]byte, error) {
	toSerialize, err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o ScientistPatchRequest) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.Name) {
		toSerialize["name"] = o.Name
	}
	if !IsNil(o.Field) {
		toSerialize["field"] = o.Field
	}
	return toSerialize, nil
}

type NullableScientistPatchRequest struct {
	value *ScientistPatchRequest
	isSet bool
}

func (v NullableScientistPatchRequest) Get() *ScientistPatchRequest {
	return v.value
}

func (v *NullableScientistPatchRequest) Set(val *ScientistPatchRequest) {
	v.value = val
	v.isSet = true
}

func (v NullableScientistPatchRequest) IsSet() bool {
	return v.isSet
}

func (v *NullableScientistPatchRequest) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableScientistPatchRequest(val *ScientistPatchRequest) *NullableScientistPatchRequest {
	return &NullableScientistPatchRequest{value: val, isSet: true}
}

func (v NullableScientistPatchRequest) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableScientistPatchRequest) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
