/*
rh-trex-ai Service API

rh-trex-ai Service API

API version: 0.0.1
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package openapi

import (
	"bytes"
	"encoding/json"
	"fmt"
)

// checks if the ScientistList type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &ScientistList{}

// ScientistList struct for ScientistList
type ScientistList struct {
	Kind  string      `json:"kind"`
	Page  int32       `json:"page"`
	Size  int32       `json:"size"`
	Total int32       `json:"total"`
	Items []Scientist `json:"items"`
}

type _ScientistList ScientistList

// NewScientistList instantiates a new ScientistList object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewScientistList(kind string, page int32, size int32, total int32, items []Scientist) *ScientistList {
	this := ScientistList{}
	this.Kind = kind
	this.Page = page
	this.Size = size
	this.Total = total
	this.Items = items
	return &this
}

// NewScientistListWithDefaults instantiates a new ScientistList object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewScientistListWithDefaults() *ScientistList {
	this := ScientistList{}
	return &this
}

// GetKind returns the Kind field value
func (o *ScientistList) GetKind() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Kind
}

// GetKindOk returns a tuple with the Kind field value
// and a boolean to check if the value has been set.
func (o *ScientistList) GetKindOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Kind, true
}

// SetKind sets field value
func (o *ScientistList) SetKind(v string) {
	o.Kind = v
}

// GetPage returns the Page field value
func (o *ScientistList) GetPage() int32 {
	if o == nil {
		var ret int32
		return ret
	}

	return o.Page
}

// GetPageOk returns a tuple with the Page field value
// and a boolean to check if the value has been set.
func (o *ScientistList) GetPageOk() (*int32, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Page, true
}

// SetPage sets field value
func (o *ScientistList) SetPage(v int32) {
	o.Page = v
}

// GetSize returns the Size field value
func (o *ScientistList) GetSize() int32 {
	if o == nil {
		var ret int32
		return ret
	}

	return o.Size
}

// GetSizeOk returns a tuple with the Size field value
// and a boolean to check if the value has been set.
func (o *ScientistList) GetSizeOk() (*int32, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Size, true
}

// SetSize sets field value
func (o *ScientistList) SetSize(v int32) {
	o.Size = v
}

// GetTotal returns the Total field value
func (o *ScientistList) GetTotal() int32 {
	if o == nil {
		var ret int32
		return ret
	}

	return o.Total
}

// GetTotalOk returns a tuple with the Total field value
// and a boolean to check if the value has been set.
func (o *ScientistList) GetTotalOk() (*int32, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Total, true
}

// SetTotal sets field value
func (o *ScientistList) SetTotal(v int32) {
	o.Total = v
}

// GetItems returns the Items field value
func (o *ScientistList) GetItems() []Scientist {
	if o == nil {
		var ret []Scientist
		return ret
	}

	return o.Items
}

// GetItemsOk returns a tuple with the Items field value
// and a boolean to check if the value has been set.
func (o *ScientistList) GetItemsOk() ([]Scientist, bool) {
	if o == nil {
		return nil, false
	}
	return o.Items, true
}

// SetItems sets field value
func (o *ScientistList) SetItems(v []Scientist) {
	o.Items = v
}

func (o ScientistList) MarshalJSON() ([]byte, error) {
	toSerialize, err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o ScientistList) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["kind"] = o.Kind
	toSerialize["page"] = o.Page
	toSerialize["size"] = o.Size
	toSerialize["total"] = o.Total
	toSerialize["items"] = o.Items
	return toSerialize, nil
}

func (o *ScientistList) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"kind",
		"page",
		"size",
		"total",
		"items",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err
	}

	for _, requiredProperty := range requiredProperties {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varScientistList := _ScientistList{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varScientistList)

	if err != nil {
		return err
	}

	*o = ScientistList(varScientistList)

	return err
}

type NullableScientistList struct {
	value *ScientistList
	isSet bool
}

func (v NullableScientistList) Get() *ScientistList {
	return v.value
}

func (v *NullableScientistList) Set(val *ScientistList) {
	v.value = val
	v.isSet = true
}

func (v NullableScientistList) IsSet() bool {
	return v.isSet
}

func (v *NullableScientistList) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableScientistList(val *ScientistList) *NullableScientistList {
	return &NullableScientistList{value: val, isSet: true}
}

func (v NullableScientistList) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableScientistList) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
