/*
rh-trex-ai Service API

rh-trex-ai Service API

API version: 0.0.1
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package openapi

import (
	"bytes"
	"encoding/json"
	"fmt"
	"time"
)

// checks if the Fossil type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &Fossil{}

// Fossil struct for Fossil
type Fossil struct {
	Id                *string    `json:"id,omitempty"`
	Kind              *string    `json:"kind,omitempty"`
	Href              *string    `json:"href,omitempty"`
	CreatedAt         *time.Time `json:"created_at,omitempty"`
	UpdatedAt         *time.Time `json:"updated_at,omitempty"`
	DiscoveryLocation string     `json:"discovery_location"`
	EstimatedAge      *int32     `json:"estimated_age,omitempty"`
	FossilType        *string    `json:"fossil_type,omitempty"`
	ExcavatorName     *string    `json:"excavator_name,omitempty"`
}

type _Fossil Fossil

// NewFossil instantiates a new Fossil object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewFossil(discoveryLocation string) *Fossil {
	this := Fossil{}
	this.DiscoveryLocation = discoveryLocation
	return &this
}

// NewFossilWithDefaults instantiates a new Fossil object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewFossilWithDefaults() *Fossil {
	this := Fossil{}
	return &this
}

// GetId returns the Id field value if set, zero value otherwise.
func (o *Fossil) GetId() string {
	if o == nil || IsNil(o.Id) {
		var ret string
		return ret
	}
	return *o.Id
}

// GetIdOk returns a tuple with the Id field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *Fossil) GetIdOk() (*string, bool) {
	if o == nil || IsNil(o.Id) {
		return nil, false
	}
	return o.Id, true
}

// HasId returns a boolean if a field has been set.
func (o *Fossil) HasId() bool {
	if o != nil && !IsNil(o.Id) {
		return true
	}

	return false
}

// SetId gets a reference to the given string and assigns it to the Id field.
func (o *Fossil) SetId(v string) {
	o.Id = &v
}

// GetKind returns the Kind field value if set, zero value otherwise.
func (o *Fossil) GetKind() string {
	if o == nil || IsNil(o.Kind) {
		var ret string
		return ret
	}
	return *o.Kind
}

// GetKindOk returns a tuple with the Kind field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *Fossil) GetKindOk() (*string, bool) {
	if o == nil || IsNil(o.Kind) {
		return nil, false
	}
	return o.Kind, true
}

// HasKind returns a boolean if a field has been set.
func (o *Fossil) HasKind() bool {
	if o != nil && !IsNil(o.Kind) {
		return true
	}

	return false
}

// SetKind gets a reference to the given string and assigns it to the Kind field.
func (o *Fossil) SetKind(v string) {
	o.Kind = &v
}

// GetHref returns the Href field value if set, zero value otherwise.
func (o *Fossil) GetHref() string {
	if o == nil || IsNil(o.Href) {
		var ret string
		return ret
	}
	return *o.Href
}

// GetHrefOk returns a tuple with the Href field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *Fossil) GetHrefOk() (*string, bool) {
	if o == nil || IsNil(o.Href) {
		return nil, false
	}
	return o.Href, true
}

// HasHref returns a boolean if a field has been set.
func (o *Fossil) HasHref() bool {
	if o != nil && !IsNil(o.Href) {
		return true
	}

	return false
}

// SetHref gets a reference to the given string and assigns it to the Href field.
func (o *Fossil) SetHref(v string) {
	o.Href = &v
}

// GetCreatedAt returns the CreatedAt field value if set, zero value otherwise.
func (o *Fossil) GetCreatedAt() time.Time {
	if o == nil || IsNil(o.CreatedAt) {
		var ret time.Time
		return ret
	}
	return *o.CreatedAt
}

// GetCreatedAtOk returns a tuple with the CreatedAt field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *Fossil) GetCreatedAtOk() (*time.Time, bool) {
	if o == nil || IsNil(o.CreatedAt) {
		return nil, false
	}
	return o.CreatedAt, true
}

// HasCreatedAt returns a boolean if a field has been set.
func (o *Fossil) HasCreatedAt() bool {
	if o != nil && !IsNil(o.CreatedAt) {
		return true
	}

	return false
}

// SetCreatedAt gets a reference to the given time.Time and assigns it to the CreatedAt field.
func (o *Fossil) SetCreatedAt(v time.Time) {
	o.CreatedAt = &v
}

// GetUpdatedAt returns the UpdatedAt field value if set, zero value otherwise.
func (o *Fossil) GetUpdatedAt() time.Time {
	if o == nil || IsNil(o.UpdatedAt) {
		var ret time.Time
		return ret
	}
	return *o.UpdatedAt
}

// GetUpdatedAtOk returns a tuple with the UpdatedAt field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *Fossil) GetUpdatedAtOk() (*time.Time, bool) {
	if o == nil || IsNil(o.UpdatedAt) {
		return nil, false
	}
	return o.UpdatedAt, true
}

// HasUpdatedAt returns a boolean if a field has been set.
func (o *Fossil) HasUpdatedAt() bool {
	if o != nil && !IsNil(o.UpdatedAt) {
		return true
	}

	return false
}

// SetUpdatedAt gets a reference to the given time.Time and assigns it to the UpdatedAt field.
func (o *Fossil) SetUpdatedAt(v time.Time) {
	o.UpdatedAt = &v
}

// GetDiscoveryLocation returns the DiscoveryLocation field value
func (o *Fossil) GetDiscoveryLocation() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.DiscoveryLocation
}

// GetDiscoveryLocationOk returns a tuple with the DiscoveryLocation field value
// and a boolean to check if the value has been set.
func (o *Fossil) GetDiscoveryLocationOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.DiscoveryLocation, true
}

// SetDiscoveryLocation sets field value
func (o *Fossil) SetDiscoveryLocation(v string) {
	o.DiscoveryLocation = v
}

// GetEstimatedAge returns the EstimatedAge field value if set, zero value otherwise.
func (o *Fossil) GetEstimatedAge() int32 {
	if o == nil || IsNil(o.EstimatedAge) {
		var ret int32
		return ret
	}
	return *o.EstimatedAge
}

// GetEstimatedAgeOk returns a tuple with the EstimatedAge field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *Fossil) GetEstimatedAgeOk() (*int32, bool) {
	if o == nil || IsNil(o.EstimatedAge) {
		return nil, false
	}
	return o.EstimatedAge, true
}

// HasEstimatedAge returns a boolean if a field has been set.
func (o *Fossil) HasEstimatedAge() bool {
	if o != nil && !IsNil(o.EstimatedAge) {
		return true
	}

	return false
}

// SetEstimatedAge gets a reference to the given int32 and assigns it to the EstimatedAge field.
func (o *Fossil) SetEstimatedAge(v int32) {
	o.EstimatedAge = &v
}

// GetFossilType returns the FossilType field value if set, zero value otherwise.
func (o *Fossil) GetFossilType() string {
	if o == nil || IsNil(o.FossilType) {
		var ret string
		return ret
	}
	return *o.FossilType
}

// GetFossilTypeOk returns a tuple with the FossilType field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *Fossil) GetFossilTypeOk() (*string, bool) {
	if o == nil || IsNil(o.FossilType) {
		return nil, false
	}
	return o.FossilType, true
}

// HasFossilType returns a boolean if a field has been set.
func (o *Fossil) HasFossilType() bool {
	if o != nil && !IsNil(o.FossilType) {
		return true
	}

	return false
}

// SetFossilType gets a reference to the given string and assigns it to the FossilType field.
func (o *Fossil) SetFossilType(v string) {
	o.FossilType = &v
}

// GetExcavatorName returns the ExcavatorName field value if set, zero value otherwise.
func (o *Fossil) GetExcavatorName() string {
	if o == nil || IsNil(o.ExcavatorName) {
		var ret string
		return ret
	}
	return *o.ExcavatorName
}

// GetExcavatorNameOk returns a tuple with the ExcavatorName field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *Fossil) GetExcavatorNameOk() (*string, bool) {
	if o == nil || IsNil(o.ExcavatorName) {
		return nil, false
	}
	return o.ExcavatorName, true
}

// HasExcavatorName returns a boolean if a field has been set.
func (o *Fossil) HasExcavatorName() bool {
	if o != nil && !IsNil(o.ExcavatorName) {
		return true
	}

	return false
}

// SetExcavatorName gets a reference to the given string and assigns it to the ExcavatorName field.
func (o *Fossil) SetExcavatorName(v string) {
	o.ExcavatorName = &v
}

func (o Fossil) MarshalJSON() ([]byte, error) {
	toSerialize, err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o Fossil) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.Id) {
		toSerialize["id"] = o.Id
	}
	if !IsNil(o.Kind) {
		toSerialize["kind"] = o.Kind
	}
	if !IsNil(o.Href) {
		toSerialize["href"] = o.Href
	}
	if !IsNil(o.CreatedAt) {
		toSerialize["created_at"] = o.CreatedAt
	}
	if !IsNil(o.UpdatedAt) {
		toSerialize["updated_at"] = o.UpdatedAt
	}
	toSerialize["discovery_location"] = o.DiscoveryLocation
	if !IsNil(o.EstimatedAge) {
		toSerialize["estimated_age"] = o.EstimatedAge
	}
	if !IsNil(o.FossilType) {
		toSerialize["fossil_type"] = o.FossilType
	}
	if !IsNil(o.ExcavatorName) {
		toSerialize["excavator_name"] = o.ExcavatorName
	}
	return toSerialize, nil
}

func (o *Fossil) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"discovery_location",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err
	}

	for _, requiredProperty := range requiredProperties {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varFossil := _Fossil{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varFossil)

	if err != nil {
		return err
	}

	*o = Fossil(varFossil)

	return err
}

type NullableFossil struct {
	value *Fossil
	isSet bool
}

func (v NullableFossil) Get() *Fossil {
	return v.value
}

func (v *NullableFossil) Set(val *Fossil) {
	v.value = val
	v.isSet = true
}

func (v NullableFossil) IsSet() bool {
	return v.isSet
}

func (v *NullableFossil) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableFossil(val *Fossil) *NullableFossil {
	return &NullableFossil{value: val, isSet: true}
}

func (v NullableFossil) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableFossil) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
