/*
rh-trex-ai Service API

rh-trex-ai Service API

API version: 0.0.1
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package openapi

import (
	"encoding/json"
)

// checks if the FossilPatchRequest type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &FossilPatchRequest{}

// FossilPatchRequest struct for FossilPatchRequest
type FossilPatchRequest struct {
	DiscoveryLocation *string `json:"discovery_location,omitempty"`
	EstimatedAge      *int32  `json:"estimated_age,omitempty"`
	FossilType        *string `json:"fossil_type,omitempty"`
	ExcavatorName     *string `json:"excavator_name,omitempty"`
}

// NewFossilPatchRequest instantiates a new FossilPatchRequest object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewFossilPatchRequest() *FossilPatchRequest {
	this := FossilPatchRequest{}
	return &this
}

// NewFossilPatchRequestWithDefaults instantiates a new FossilPatchRequest object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewFossilPatchRequestWithDefaults() *FossilPatchRequest {
	this := FossilPatchRequest{}
	return &this
}

// GetDiscoveryLocation returns the DiscoveryLocation field value if set, zero value otherwise.
func (o *FossilPatchRequest) GetDiscoveryLocation() string {
	if o == nil || IsNil(o.DiscoveryLocation) {
		var ret string
		return ret
	}
	return *o.DiscoveryLocation
}

// GetDiscoveryLocationOk returns a tuple with the DiscoveryLocation field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *FossilPatchRequest) GetDiscoveryLocationOk() (*string, bool) {
	if o == nil || IsNil(o.DiscoveryLocation) {
		return nil, false
	}
	return o.DiscoveryLocation, true
}

// HasDiscoveryLocation returns a boolean if a field has been set.
func (o *FossilPatchRequest) HasDiscoveryLocation() bool {
	if o != nil && !IsNil(o.DiscoveryLocation) {
		return true
	}

	return false
}

// SetDiscoveryLocation gets a reference to the given string and assigns it to the DiscoveryLocation field.
func (o *FossilPatchRequest) SetDiscoveryLocation(v string) {
	o.DiscoveryLocation = &v
}

// GetEstimatedAge returns the EstimatedAge field value if set, zero value otherwise.
func (o *FossilPatchRequest) GetEstimatedAge() int32 {
	if o == nil || IsNil(o.EstimatedAge) {
		var ret int32
		return ret
	}
	return *o.EstimatedAge
}

// GetEstimatedAgeOk returns a tuple with the EstimatedAge field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *FossilPatchRequest) GetEstimatedAgeOk() (*int32, bool) {
	if o == nil || IsNil(o.EstimatedAge) {
		return nil, false
	}
	return o.EstimatedAge, true
}

// HasEstimatedAge returns a boolean if a field has been set.
func (o *FossilPatchRequest) HasEstimatedAge() bool {
	if o != nil && !IsNil(o.EstimatedAge) {
		return true
	}

	return false
}

// SetEstimatedAge gets a reference to the given int32 and assigns it to the EstimatedAge field.
func (o *FossilPatchRequest) SetEstimatedAge(v int32) {
	o.EstimatedAge = &v
}

// GetFossilType returns the FossilType field value if set, zero value otherwise.
func (o *FossilPatchRequest) GetFossilType() string {
	if o == nil || IsNil(o.FossilType) {
		var ret string
		return ret
	}
	return *o.FossilType
}

// GetFossilTypeOk returns a tuple with the FossilType field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *FossilPatchRequest) GetFossilTypeOk() (*string, bool) {
	if o == nil || IsNil(o.FossilType) {
		return nil, false
	}
	return o.FossilType, true
}

// HasFossilType returns a boolean if a field has been set.
func (o *FossilPatchRequest) HasFossilType() bool {
	if o != nil && !IsNil(o.FossilType) {
		return true
	}

	return false
}

// SetFossilType gets a reference to the given string and assigns it to the FossilType field.
func (o *FossilPatchRequest) SetFossilType(v string) {
	o.FossilType = &v
}

// GetExcavatorName returns the ExcavatorName field value if set, zero value otherwise.
func (o *FossilPatchRequest) GetExcavatorName() string {
	if o == nil || IsNil(o.ExcavatorName) {
		var ret string
		return ret
	}
	return *o.ExcavatorName
}

// GetExcavatorNameOk returns a tuple with the ExcavatorName field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *FossilPatchRequest) GetExcavatorNameOk() (*string, bool) {
	if o == nil || IsNil(o.ExcavatorName) {
		return nil, false
	}
	return o.ExcavatorName, true
}

// HasExcavatorName returns a boolean if a field has been set.
func (o *FossilPatchRequest) HasExcavatorName() bool {
	if o != nil && !IsNil(o.ExcavatorName) {
		return true
	}

	return false
}

// SetExcavatorName gets a reference to the given string and assigns it to the ExcavatorName field.
func (o *FossilPatchRequest) SetExcavatorName(v string) {
	o.ExcavatorName = &v
}

func (o FossilPatchRequest) MarshalJSON() ([]byte, error) {
	toSerialize, err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o FossilPatchRequest) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.DiscoveryLocation) {
		toSerialize["discovery_location"] = o.DiscoveryLocation
	}
	if !IsNil(o.EstimatedAge) {
		toSerialize["estimated_age"] = o.EstimatedAge
	}
	if !IsNil(o.FossilType) {
		toSerialize["fossil_type"] = o.FossilType
	}
	if !IsNil(o.ExcavatorName) {
		toSerialize["excavator_name"] = o.ExcavatorName
	}
	return toSerialize, nil
}

type NullableFossilPatchRequest struct {
	value *FossilPatchRequest
	isSet bool
}

func (v NullableFossilPatchRequest) Get() *FossilPatchRequest {
	return v.value
}

func (v *NullableFossilPatchRequest) Set(val *FossilPatchRequest) {
	v.value = val
	v.isSet = true
}

func (v NullableFossilPatchRequest) IsSet() bool {
	return v.isSet
}

func (v *NullableFossilPatchRequest) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableFossilPatchRequest(val *FossilPatchRequest) *NullableFossilPatchRequest {
	return &NullableFossilPatchRequest{value: val, isSet: true}
}

func (v NullableFossilPatchRequest) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableFossilPatchRequest) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
