/*
rh-trex-ai Service API

rh-trex-ai Service API

API version: 0.0.1
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package openapi

import (
	"encoding/json"
)

// checks if the FieldDefinitionPatchRequest type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &FieldDefinitionPatchRequest{}

// FieldDefinitionPatchRequest struct for FieldDefinitionPatchRequest
type FieldDefinitionPatchRequest struct {
	EntityDefinitionId *string `json:"entity_definition_id,omitempty"`
	FieldName          *string `json:"field_name,omitempty"`
	FieldType          *string `json:"field_type,omitempty"`
	IsRequired         *bool   `json:"is_required,omitempty"`
}

// NewFieldDefinitionPatchRequest instantiates a new FieldDefinitionPatchRequest object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewFieldDefinitionPatchRequest() *FieldDefinitionPatchRequest {
	this := FieldDefinitionPatchRequest{}
	return &this
}

// NewFieldDefinitionPatchRequestWithDefaults instantiates a new FieldDefinitionPatchRequest object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewFieldDefinitionPatchRequestWithDefaults() *FieldDefinitionPatchRequest {
	this := FieldDefinitionPatchRequest{}
	return &this
}

// GetEntityDefinitionId returns the EntityDefinitionId field value if set, zero value otherwise.
func (o *FieldDefinitionPatchRequest) GetEntityDefinitionId() string {
	if o == nil || IsNil(o.EntityDefinitionId) {
		var ret string
		return ret
	}
	return *o.EntityDefinitionId
}

// GetEntityDefinitionIdOk returns a tuple with the EntityDefinitionId field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *FieldDefinitionPatchRequest) GetEntityDefinitionIdOk() (*string, bool) {
	if o == nil || IsNil(o.EntityDefinitionId) {
		return nil, false
	}
	return o.EntityDefinitionId, true
}

// HasEntityDefinitionId returns a boolean if a field has been set.
func (o *FieldDefinitionPatchRequest) HasEntityDefinitionId() bool {
	if o != nil && !IsNil(o.EntityDefinitionId) {
		return true
	}

	return false
}

// SetEntityDefinitionId gets a reference to the given string and assigns it to the EntityDefinitionId field.
func (o *FieldDefinitionPatchRequest) SetEntityDefinitionId(v string) {
	o.EntityDefinitionId = &v
}

// GetFieldName returns the FieldName field value if set, zero value otherwise.
func (o *FieldDefinitionPatchRequest) GetFieldName() string {
	if o == nil || IsNil(o.FieldName) {
		var ret string
		return ret
	}
	return *o.FieldName
}

// GetFieldNameOk returns a tuple with the FieldName field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *FieldDefinitionPatchRequest) GetFieldNameOk() (*string, bool) {
	if o == nil || IsNil(o.FieldName) {
		return nil, false
	}
	return o.FieldName, true
}

// HasFieldName returns a boolean if a field has been set.
func (o *FieldDefinitionPatchRequest) HasFieldName() bool {
	if o != nil && !IsNil(o.FieldName) {
		return true
	}

	return false
}

// SetFieldName gets a reference to the given string and assigns it to the FieldName field.
func (o *FieldDefinitionPatchRequest) SetFieldName(v string) {
	o.FieldName = &v
}

// GetFieldType returns the FieldType field value if set, zero value otherwise.
func (o *FieldDefinitionPatchRequest) GetFieldType() string {
	if o == nil || IsNil(o.FieldType) {
		var ret string
		return ret
	}
	return *o.FieldType
}

// GetFieldTypeOk returns a tuple with the FieldType field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *FieldDefinitionPatchRequest) GetFieldTypeOk() (*string, bool) {
	if o == nil || IsNil(o.FieldType) {
		return nil, false
	}
	return o.FieldType, true
}

// HasFieldType returns a boolean if a field has been set.
func (o *FieldDefinitionPatchRequest) HasFieldType() bool {
	if o != nil && !IsNil(o.FieldType) {
		return true
	}

	return false
}

// SetFieldType gets a reference to the given string and assigns it to the FieldType field.
func (o *FieldDefinitionPatchRequest) SetFieldType(v string) {
	o.FieldType = &v
}

// GetIsRequired returns the IsRequired field value if set, zero value otherwise.
func (o *FieldDefinitionPatchRequest) GetIsRequired() bool {
	if o == nil || IsNil(o.IsRequired) {
		var ret bool
		return ret
	}
	return *o.IsRequired
}

// GetIsRequiredOk returns a tuple with the IsRequired field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *FieldDefinitionPatchRequest) GetIsRequiredOk() (*bool, bool) {
	if o == nil || IsNil(o.IsRequired) {
		return nil, false
	}
	return o.IsRequired, true
}

// HasIsRequired returns a boolean if a field has been set.
func (o *FieldDefinitionPatchRequest) HasIsRequired() bool {
	if o != nil && !IsNil(o.IsRequired) {
		return true
	}

	return false
}

// SetIsRequired gets a reference to the given bool and assigns it to the IsRequired field.
func (o *FieldDefinitionPatchRequest) SetIsRequired(v bool) {
	o.IsRequired = &v
}

func (o FieldDefinitionPatchRequest) MarshalJSON() ([]byte, error) {
	toSerialize, err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o FieldDefinitionPatchRequest) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.EntityDefinitionId) {
		toSerialize["entity_definition_id"] = o.EntityDefinitionId
	}
	if !IsNil(o.FieldName) {
		toSerialize["field_name"] = o.FieldName
	}
	if !IsNil(o.FieldType) {
		toSerialize["field_type"] = o.FieldType
	}
	if !IsNil(o.IsRequired) {
		toSerialize["is_required"] = o.IsRequired
	}
	return toSerialize, nil
}

type NullableFieldDefinitionPatchRequest struct {
	value *FieldDefinitionPatchRequest
	isSet bool
}

func (v NullableFieldDefinitionPatchRequest) Get() *FieldDefinitionPatchRequest {
	return v.value
}

func (v *NullableFieldDefinitionPatchRequest) Set(val *FieldDefinitionPatchRequest) {
	v.value = val
	v.isSet = true
}

func (v NullableFieldDefinitionPatchRequest) IsSet() bool {
	return v.isSet
}

func (v *NullableFieldDefinitionPatchRequest) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableFieldDefinitionPatchRequest(val *FieldDefinitionPatchRequest) *NullableFieldDefinitionPatchRequest {
	return &NullableFieldDefinitionPatchRequest{value: val, isSet: true}
}

func (v NullableFieldDefinitionPatchRequest) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableFieldDefinitionPatchRequest) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
