/*
rh-trex-ai Service API

rh-trex-ai Service API

API version: 0.0.1
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package openapi

import (
	"bytes"
	"encoding/json"
	"fmt"
	"time"
)

// checks if the FieldDefinition type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &FieldDefinition{}

// FieldDefinition struct for FieldDefinition
type FieldDefinition struct {
	Id                 *string    `json:"id,omitempty"`
	Kind               *string    `json:"kind,omitempty"`
	Href               *string    `json:"href,omitempty"`
	CreatedAt          *time.Time `json:"created_at,omitempty"`
	UpdatedAt          *time.Time `json:"updated_at,omitempty"`
	EntityDefinitionId string     `json:"entity_definition_id"`
	FieldName          string     `json:"field_name"`
	FieldType          string     `json:"field_type"`
	IsRequired         *bool      `json:"is_required,omitempty"`
}

type _FieldDefinition FieldDefinition

// NewFieldDefinition instantiates a new FieldDefinition object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewFieldDefinition(entityDefinitionId string, fieldName string, fieldType string) *FieldDefinition {
	this := FieldDefinition{}
	this.EntityDefinitionId = entityDefinitionId
	this.FieldName = fieldName
	this.FieldType = fieldType
	return &this
}

// NewFieldDefinitionWithDefaults instantiates a new FieldDefinition object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewFieldDefinitionWithDefaults() *FieldDefinition {
	this := FieldDefinition{}
	return &this
}

// GetId returns the Id field value if set, zero value otherwise.
func (o *FieldDefinition) GetId() string {
	if o == nil || IsNil(o.Id) {
		var ret string
		return ret
	}
	return *o.Id
}

// GetIdOk returns a tuple with the Id field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *FieldDefinition) GetIdOk() (*string, bool) {
	if o == nil || IsNil(o.Id) {
		return nil, false
	}
	return o.Id, true
}

// HasId returns a boolean if a field has been set.
func (o *FieldDefinition) HasId() bool {
	if o != nil && !IsNil(o.Id) {
		return true
	}

	return false
}

// SetId gets a reference to the given string and assigns it to the Id field.
func (o *FieldDefinition) SetId(v string) {
	o.Id = &v
}

// GetKind returns the Kind field value if set, zero value otherwise.
func (o *FieldDefinition) GetKind() string {
	if o == nil || IsNil(o.Kind) {
		var ret string
		return ret
	}
	return *o.Kind
}

// GetKindOk returns a tuple with the Kind field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *FieldDefinition) GetKindOk() (*string, bool) {
	if o == nil || IsNil(o.Kind) {
		return nil, false
	}
	return o.Kind, true
}

// HasKind returns a boolean if a field has been set.
func (o *FieldDefinition) HasKind() bool {
	if o != nil && !IsNil(o.Kind) {
		return true
	}

	return false
}

// SetKind gets a reference to the given string and assigns it to the Kind field.
func (o *FieldDefinition) SetKind(v string) {
	o.Kind = &v
}

// GetHref returns the Href field value if set, zero value otherwise.
func (o *FieldDefinition) GetHref() string {
	if o == nil || IsNil(o.Href) {
		var ret string
		return ret
	}
	return *o.Href
}

// GetHrefOk returns a tuple with the Href field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *FieldDefinition) GetHrefOk() (*string, bool) {
	if o == nil || IsNil(o.Href) {
		return nil, false
	}
	return o.Href, true
}

// HasHref returns a boolean if a field has been set.
func (o *FieldDefinition) HasHref() bool {
	if o != nil && !IsNil(o.Href) {
		return true
	}

	return false
}

// SetHref gets a reference to the given string and assigns it to the Href field.
func (o *FieldDefinition) SetHref(v string) {
	o.Href = &v
}

// GetCreatedAt returns the CreatedAt field value if set, zero value otherwise.
func (o *FieldDefinition) GetCreatedAt() time.Time {
	if o == nil || IsNil(o.CreatedAt) {
		var ret time.Time
		return ret
	}
	return *o.CreatedAt
}

// GetCreatedAtOk returns a tuple with the CreatedAt field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *FieldDefinition) GetCreatedAtOk() (*time.Time, bool) {
	if o == nil || IsNil(o.CreatedAt) {
		return nil, false
	}
	return o.CreatedAt, true
}

// HasCreatedAt returns a boolean if a field has been set.
func (o *FieldDefinition) HasCreatedAt() bool {
	if o != nil && !IsNil(o.CreatedAt) {
		return true
	}

	return false
}

// SetCreatedAt gets a reference to the given time.Time and assigns it to the CreatedAt field.
func (o *FieldDefinition) SetCreatedAt(v time.Time) {
	o.CreatedAt = &v
}

// GetUpdatedAt returns the UpdatedAt field value if set, zero value otherwise.
func (o *FieldDefinition) GetUpdatedAt() time.Time {
	if o == nil || IsNil(o.UpdatedAt) {
		var ret time.Time
		return ret
	}
	return *o.UpdatedAt
}

// GetUpdatedAtOk returns a tuple with the UpdatedAt field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *FieldDefinition) GetUpdatedAtOk() (*time.Time, bool) {
	if o == nil || IsNil(o.UpdatedAt) {
		return nil, false
	}
	return o.UpdatedAt, true
}

// HasUpdatedAt returns a boolean if a field has been set.
func (o *FieldDefinition) HasUpdatedAt() bool {
	if o != nil && !IsNil(o.UpdatedAt) {
		return true
	}

	return false
}

// SetUpdatedAt gets a reference to the given time.Time and assigns it to the UpdatedAt field.
func (o *FieldDefinition) SetUpdatedAt(v time.Time) {
	o.UpdatedAt = &v
}

// GetEntityDefinitionId returns the EntityDefinitionId field value
func (o *FieldDefinition) GetEntityDefinitionId() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.EntityDefinitionId
}

// GetEntityDefinitionIdOk returns a tuple with the EntityDefinitionId field value
// and a boolean to check if the value has been set.
func (o *FieldDefinition) GetEntityDefinitionIdOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.EntityDefinitionId, true
}

// SetEntityDefinitionId sets field value
func (o *FieldDefinition) SetEntityDefinitionId(v string) {
	o.EntityDefinitionId = v
}

// GetFieldName returns the FieldName field value
func (o *FieldDefinition) GetFieldName() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.FieldName
}

// GetFieldNameOk returns a tuple with the FieldName field value
// and a boolean to check if the value has been set.
func (o *FieldDefinition) GetFieldNameOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.FieldName, true
}

// SetFieldName sets field value
func (o *FieldDefinition) SetFieldName(v string) {
	o.FieldName = v
}

// GetFieldType returns the FieldType field value
func (o *FieldDefinition) GetFieldType() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.FieldType
}

// GetFieldTypeOk returns a tuple with the FieldType field value
// and a boolean to check if the value has been set.
func (o *FieldDefinition) GetFieldTypeOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.FieldType, true
}

// SetFieldType sets field value
func (o *FieldDefinition) SetFieldType(v string) {
	o.FieldType = v
}

// GetIsRequired returns the IsRequired field value if set, zero value otherwise.
func (o *FieldDefinition) GetIsRequired() bool {
	if o == nil || IsNil(o.IsRequired) {
		var ret bool
		return ret
	}
	return *o.IsRequired
}

// GetIsRequiredOk returns a tuple with the IsRequired field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *FieldDefinition) GetIsRequiredOk() (*bool, bool) {
	if o == nil || IsNil(o.IsRequired) {
		return nil, false
	}
	return o.IsRequired, true
}

// HasIsRequired returns a boolean if a field has been set.
func (o *FieldDefinition) HasIsRequired() bool {
	if o != nil && !IsNil(o.IsRequired) {
		return true
	}

	return false
}

// SetIsRequired gets a reference to the given bool and assigns it to the IsRequired field.
func (o *FieldDefinition) SetIsRequired(v bool) {
	o.IsRequired = &v
}

func (o FieldDefinition) MarshalJSON() ([]byte, error) {
	toSerialize, err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o FieldDefinition) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.Id) {
		toSerialize["id"] = o.Id
	}
	if !IsNil(o.Kind) {
		toSerialize["kind"] = o.Kind
	}
	if !IsNil(o.Href) {
		toSerialize["href"] = o.Href
	}
	if !IsNil(o.CreatedAt) {
		toSerialize["created_at"] = o.CreatedAt
	}
	if !IsNil(o.UpdatedAt) {
		toSerialize["updated_at"] = o.UpdatedAt
	}
	toSerialize["entity_definition_id"] = o.EntityDefinitionId
	toSerialize["field_name"] = o.FieldName
	toSerialize["field_type"] = o.FieldType
	if !IsNil(o.IsRequired) {
		toSerialize["is_required"] = o.IsRequired
	}
	return toSerialize, nil
}

func (o *FieldDefinition) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"entity_definition_id",
		"field_name",
		"field_type",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err
	}

	for _, requiredProperty := range requiredProperties {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varFieldDefinition := _FieldDefinition{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varFieldDefinition)

	if err != nil {
		return err
	}

	*o = FieldDefinition(varFieldDefinition)

	return err
}

type NullableFieldDefinition struct {
	value *FieldDefinition
	isSet bool
}

func (v NullableFieldDefinition) Get() *FieldDefinition {
	return v.value
}

func (v *NullableFieldDefinition) Set(val *FieldDefinition) {
	v.value = val
	v.isSet = true
}

func (v NullableFieldDefinition) IsSet() bool {
	return v.isSet
}

func (v *NullableFieldDefinition) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableFieldDefinition(val *FieldDefinition) *NullableFieldDefinition {
	return &NullableFieldDefinition{value: val, isSet: true}
}

func (v NullableFieldDefinition) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableFieldDefinition) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
