/*
rh-trex-ai Service API

rh-trex-ai Service API

API version: 0.0.1
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package openapi

import (
	"bytes"
	"encoding/json"
	"fmt"
)

// checks if the FieldDefinitionList type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &FieldDefinitionList{}

// FieldDefinitionList struct for FieldDefinitionList
type FieldDefinitionList struct {
	Kind  string            `json:"kind"`
	Page  int32             `json:"page"`
	Size  int32             `json:"size"`
	Total int32             `json:"total"`
	Items []FieldDefinition `json:"items"`
}

type _FieldDefinitionList FieldDefinitionList

// NewFieldDefinitionList instantiates a new FieldDefinitionList object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewFieldDefinitionList(kind string, page int32, size int32, total int32, items []FieldDefinition) *FieldDefinitionList {
	this := FieldDefinitionList{}
	this.Kind = kind
	this.Page = page
	this.Size = size
	this.Total = total
	this.Items = items
	return &this
}

// NewFieldDefinitionListWithDefaults instantiates a new FieldDefinitionList object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewFieldDefinitionListWithDefaults() *FieldDefinitionList {
	this := FieldDefinitionList{}
	return &this
}

// GetKind returns the Kind field value
func (o *FieldDefinitionList) GetKind() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Kind
}

// GetKindOk returns a tuple with the Kind field value
// and a boolean to check if the value has been set.
func (o *FieldDefinitionList) GetKindOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Kind, true
}

// SetKind sets field value
func (o *FieldDefinitionList) SetKind(v string) {
	o.Kind = v
}

// GetPage returns the Page field value
func (o *FieldDefinitionList) GetPage() int32 {
	if o == nil {
		var ret int32
		return ret
	}

	return o.Page
}

// GetPageOk returns a tuple with the Page field value
// and a boolean to check if the value has been set.
func (o *FieldDefinitionList) GetPageOk() (*int32, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Page, true
}

// SetPage sets field value
func (o *FieldDefinitionList) SetPage(v int32) {
	o.Page = v
}

// GetSize returns the Size field value
func (o *FieldDefinitionList) GetSize() int32 {
	if o == nil {
		var ret int32
		return ret
	}

	return o.Size
}

// GetSizeOk returns a tuple with the Size field value
// and a boolean to check if the value has been set.
func (o *FieldDefinitionList) GetSizeOk() (*int32, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Size, true
}

// SetSize sets field value
func (o *FieldDefinitionList) SetSize(v int32) {
	o.Size = v
}

// GetTotal returns the Total field value
func (o *FieldDefinitionList) GetTotal() int32 {
	if o == nil {
		var ret int32
		return ret
	}

	return o.Total
}

// GetTotalOk returns a tuple with the Total field value
// and a boolean to check if the value has been set.
func (o *FieldDefinitionList) GetTotalOk() (*int32, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Total, true
}

// SetTotal sets field value
func (o *FieldDefinitionList) SetTotal(v int32) {
	o.Total = v
}

// GetItems returns the Items field value
func (o *FieldDefinitionList) GetItems() []FieldDefinition {
	if o == nil {
		var ret []FieldDefinition
		return ret
	}

	return o.Items
}

// GetItemsOk returns a tuple with the Items field value
// and a boolean to check if the value has been set.
func (o *FieldDefinitionList) GetItemsOk() ([]FieldDefinition, bool) {
	if o == nil {
		return nil, false
	}
	return o.Items, true
}

// SetItems sets field value
func (o *FieldDefinitionList) SetItems(v []FieldDefinition) {
	o.Items = v
}

func (o FieldDefinitionList) MarshalJSON() ([]byte, error) {
	toSerialize, err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o FieldDefinitionList) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["kind"] = o.Kind
	toSerialize["page"] = o.Page
	toSerialize["size"] = o.Size
	toSerialize["total"] = o.Total
	toSerialize["items"] = o.Items
	return toSerialize, nil
}

func (o *FieldDefinitionList) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"kind",
		"page",
		"size",
		"total",
		"items",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err
	}

	for _, requiredProperty := range requiredProperties {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varFieldDefinitionList := _FieldDefinitionList{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varFieldDefinitionList)

	if err != nil {
		return err
	}

	*o = FieldDefinitionList(varFieldDefinitionList)

	return err
}

type NullableFieldDefinitionList struct {
	value *FieldDefinitionList
	isSet bool
}

func (v NullableFieldDefinitionList) Get() *FieldDefinitionList {
	return v.value
}

func (v *NullableFieldDefinitionList) Set(val *FieldDefinitionList) {
	v.value = val
	v.isSet = true
}

func (v NullableFieldDefinitionList) IsSet() bool {
	return v.isSet
}

func (v *NullableFieldDefinitionList) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableFieldDefinitionList(val *FieldDefinitionList) *NullableFieldDefinitionList {
	return &NullableFieldDefinitionList{value: val, isSet: true}
}

func (v NullableFieldDefinitionList) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableFieldDefinitionList) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
