/*
rh-trex-ai Service API

rh-trex-ai Service API

API version: 0.0.1
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package openapi

import (
	"bytes"
	"encoding/json"
	"fmt"
	"time"
)

// checks if the Relationship type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &Relationship{}

// Relationship struct for Relationship
type Relationship struct {
	Id               *string    `json:"id,omitempty"`
	Kind             *string    `json:"kind,omitempty"`
	Href             *string    `json:"href,omitempty"`
	CreatedAt        *time.Time `json:"created_at,omitempty"`
	UpdatedAt        *time.Time `json:"updated_at,omitempty"`
	ProjectId        string     `json:"project_id"`
	SourceEntityId   string     `json:"source_entity_id"`
	TargetEntityId   string     `json:"target_entity_id"`
	RelationshipType string     `json:"relationship_type"`
	ForeignKey       *string    `json:"foreign_key,omitempty"`
}

type _Relationship Relationship

// NewRelationship instantiates a new Relationship object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewRelationship(projectId string, sourceEntityId string, targetEntityId string, relationshipType string) *Relationship {
	this := Relationship{}
	this.ProjectId = projectId
	this.SourceEntityId = sourceEntityId
	this.TargetEntityId = targetEntityId
	this.RelationshipType = relationshipType
	return &this
}

// NewRelationshipWithDefaults instantiates a new Relationship object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewRelationshipWithDefaults() *Relationship {
	this := Relationship{}
	return &this
}

// GetId returns the Id field value if set, zero value otherwise.
func (o *Relationship) GetId() string {
	if o == nil || IsNil(o.Id) {
		var ret string
		return ret
	}
	return *o.Id
}

// GetIdOk returns a tuple with the Id field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *Relationship) GetIdOk() (*string, bool) {
	if o == nil || IsNil(o.Id) {
		return nil, false
	}
	return o.Id, true
}

// HasId returns a boolean if a field has been set.
func (o *Relationship) HasId() bool {
	if o != nil && !IsNil(o.Id) {
		return true
	}

	return false
}

// SetId gets a reference to the given string and assigns it to the Id field.
func (o *Relationship) SetId(v string) {
	o.Id = &v
}

// GetKind returns the Kind field value if set, zero value otherwise.
func (o *Relationship) GetKind() string {
	if o == nil || IsNil(o.Kind) {
		var ret string
		return ret
	}
	return *o.Kind
}

// GetKindOk returns a tuple with the Kind field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *Relationship) GetKindOk() (*string, bool) {
	if o == nil || IsNil(o.Kind) {
		return nil, false
	}
	return o.Kind, true
}

// HasKind returns a boolean if a field has been set.
func (o *Relationship) HasKind() bool {
	if o != nil && !IsNil(o.Kind) {
		return true
	}

	return false
}

// SetKind gets a reference to the given string and assigns it to the Kind field.
func (o *Relationship) SetKind(v string) {
	o.Kind = &v
}

// GetHref returns the Href field value if set, zero value otherwise.
func (o *Relationship) GetHref() string {
	if o == nil || IsNil(o.Href) {
		var ret string
		return ret
	}
	return *o.Href
}

// GetHrefOk returns a tuple with the Href field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *Relationship) GetHrefOk() (*string, bool) {
	if o == nil || IsNil(o.Href) {
		return nil, false
	}
	return o.Href, true
}

// HasHref returns a boolean if a field has been set.
func (o *Relationship) HasHref() bool {
	if o != nil && !IsNil(o.Href) {
		return true
	}

	return false
}

// SetHref gets a reference to the given string and assigns it to the Href field.
func (o *Relationship) SetHref(v string) {
	o.Href = &v
}

// GetCreatedAt returns the CreatedAt field value if set, zero value otherwise.
func (o *Relationship) GetCreatedAt() time.Time {
	if o == nil || IsNil(o.CreatedAt) {
		var ret time.Time
		return ret
	}
	return *o.CreatedAt
}

// GetCreatedAtOk returns a tuple with the CreatedAt field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *Relationship) GetCreatedAtOk() (*time.Time, bool) {
	if o == nil || IsNil(o.CreatedAt) {
		return nil, false
	}
	return o.CreatedAt, true
}

// HasCreatedAt returns a boolean if a field has been set.
func (o *Relationship) HasCreatedAt() bool {
	if o != nil && !IsNil(o.CreatedAt) {
		return true
	}

	return false
}

// SetCreatedAt gets a reference to the given time.Time and assigns it to the CreatedAt field.
func (o *Relationship) SetCreatedAt(v time.Time) {
	o.CreatedAt = &v
}

// GetUpdatedAt returns the UpdatedAt field value if set, zero value otherwise.
func (o *Relationship) GetUpdatedAt() time.Time {
	if o == nil || IsNil(o.UpdatedAt) {
		var ret time.Time
		return ret
	}
	return *o.UpdatedAt
}

// GetUpdatedAtOk returns a tuple with the UpdatedAt field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *Relationship) GetUpdatedAtOk() (*time.Time, bool) {
	if o == nil || IsNil(o.UpdatedAt) {
		return nil, false
	}
	return o.UpdatedAt, true
}

// HasUpdatedAt returns a boolean if a field has been set.
func (o *Relationship) HasUpdatedAt() bool {
	if o != nil && !IsNil(o.UpdatedAt) {
		return true
	}

	return false
}

// SetUpdatedAt gets a reference to the given time.Time and assigns it to the UpdatedAt field.
func (o *Relationship) SetUpdatedAt(v time.Time) {
	o.UpdatedAt = &v
}

// GetProjectId returns the ProjectId field value
func (o *Relationship) GetProjectId() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.ProjectId
}

// GetProjectIdOk returns a tuple with the ProjectId field value
// and a boolean to check if the value has been set.
func (o *Relationship) GetProjectIdOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.ProjectId, true
}

// SetProjectId sets field value
func (o *Relationship) SetProjectId(v string) {
	o.ProjectId = v
}

// GetSourceEntityId returns the SourceEntityId field value
func (o *Relationship) GetSourceEntityId() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.SourceEntityId
}

// GetSourceEntityIdOk returns a tuple with the SourceEntityId field value
// and a boolean to check if the value has been set.
func (o *Relationship) GetSourceEntityIdOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.SourceEntityId, true
}

// SetSourceEntityId sets field value
func (o *Relationship) SetSourceEntityId(v string) {
	o.SourceEntityId = v
}

// GetTargetEntityId returns the TargetEntityId field value
func (o *Relationship) GetTargetEntityId() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.TargetEntityId
}

// GetTargetEntityIdOk returns a tuple with the TargetEntityId field value
// and a boolean to check if the value has been set.
func (o *Relationship) GetTargetEntityIdOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.TargetEntityId, true
}

// SetTargetEntityId sets field value
func (o *Relationship) SetTargetEntityId(v string) {
	o.TargetEntityId = v
}

// GetRelationshipType returns the RelationshipType field value
func (o *Relationship) GetRelationshipType() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.RelationshipType
}

// GetRelationshipTypeOk returns a tuple with the RelationshipType field value
// and a boolean to check if the value has been set.
func (o *Relationship) GetRelationshipTypeOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.RelationshipType, true
}

// SetRelationshipType sets field value
func (o *Relationship) SetRelationshipType(v string) {
	o.RelationshipType = v
}

// GetForeignKey returns the ForeignKey field value if set, zero value otherwise.
func (o *Relationship) GetForeignKey() string {
	if o == nil || IsNil(o.ForeignKey) {
		var ret string
		return ret
	}
	return *o.ForeignKey
}

// GetForeignKeyOk returns a tuple with the ForeignKey field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *Relationship) GetForeignKeyOk() (*string, bool) {
	if o == nil || IsNil(o.ForeignKey) {
		return nil, false
	}
	return o.ForeignKey, true
}

// HasForeignKey returns a boolean if a field has been set.
func (o *Relationship) HasForeignKey() bool {
	if o != nil && !IsNil(o.ForeignKey) {
		return true
	}

	return false
}

// SetForeignKey gets a reference to the given string and assigns it to the ForeignKey field.
func (o *Relationship) SetForeignKey(v string) {
	o.ForeignKey = &v
}

func (o Relationship) MarshalJSON() ([]byte, error) {
	toSerialize, err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o Relationship) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.Id) {
		toSerialize["id"] = o.Id
	}
	if !IsNil(o.Kind) {
		toSerialize["kind"] = o.Kind
	}
	if !IsNil(o.Href) {
		toSerialize["href"] = o.Href
	}
	if !IsNil(o.CreatedAt) {
		toSerialize["created_at"] = o.CreatedAt
	}
	if !IsNil(o.UpdatedAt) {
		toSerialize["updated_at"] = o.UpdatedAt
	}
	toSerialize["project_id"] = o.ProjectId
	toSerialize["source_entity_id"] = o.SourceEntityId
	toSerialize["target_entity_id"] = o.TargetEntityId
	toSerialize["relationship_type"] = o.RelationshipType
	if !IsNil(o.ForeignKey) {
		toSerialize["foreign_key"] = o.ForeignKey
	}
	return toSerialize, nil
}

func (o *Relationship) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"project_id",
		"source_entity_id",
		"target_entity_id",
		"relationship_type",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err
	}

	for _, requiredProperty := range requiredProperties {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varRelationship := _Relationship{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varRelationship)

	if err != nil {
		return err
	}

	*o = Relationship(varRelationship)

	return err
}

type NullableRelationship struct {
	value *Relationship
	isSet bool
}

func (v NullableRelationship) Get() *Relationship {
	return v.value
}

func (v *NullableRelationship) Set(val *Relationship) {
	v.value = val
	v.isSet = true
}

func (v NullableRelationship) IsSet() bool {
	return v.isSet
}

func (v *NullableRelationship) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableRelationship(val *Relationship) *NullableRelationship {
	return &NullableRelationship{value: val, isSet: true}
}

func (v NullableRelationship) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableRelationship) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
