/*
rh-trex-ai Service API

rh-trex-ai Service API

API version: 0.0.1
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package openapi

import (
	"encoding/json"
)

// checks if the EntityDefinitionPatchRequest type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &EntityDefinitionPatchRequest{}

// EntityDefinitionPatchRequest struct for EntityDefinitionPatchRequest
type EntityDefinitionPatchRequest struct {
	ProjectId      *string `json:"project_id,omitempty"`
	KindName       *string `json:"kind_name,omitempty"`
	PluralOverride *string `json:"plural_override,omitempty"`
	Description    *string `json:"description,omitempty"`
}

// NewEntityDefinitionPatchRequest instantiates a new EntityDefinitionPatchRequest object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewEntityDefinitionPatchRequest() *EntityDefinitionPatchRequest {
	this := EntityDefinitionPatchRequest{}
	return &this
}

// NewEntityDefinitionPatchRequestWithDefaults instantiates a new EntityDefinitionPatchRequest object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewEntityDefinitionPatchRequestWithDefaults() *EntityDefinitionPatchRequest {
	this := EntityDefinitionPatchRequest{}
	return &this
}

// GetProjectId returns the ProjectId field value if set, zero value otherwise.
func (o *EntityDefinitionPatchRequest) GetProjectId() string {
	if o == nil || IsNil(o.ProjectId) {
		var ret string
		return ret
	}
	return *o.ProjectId
}

// GetProjectIdOk returns a tuple with the ProjectId field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *EntityDefinitionPatchRequest) GetProjectIdOk() (*string, bool) {
	if o == nil || IsNil(o.ProjectId) {
		return nil, false
	}
	return o.ProjectId, true
}

// HasProjectId returns a boolean if a field has been set.
func (o *EntityDefinitionPatchRequest) HasProjectId() bool {
	if o != nil && !IsNil(o.ProjectId) {
		return true
	}

	return false
}

// SetProjectId gets a reference to the given string and assigns it to the ProjectId field.
func (o *EntityDefinitionPatchRequest) SetProjectId(v string) {
	o.ProjectId = &v
}

// GetKindName returns the KindName field value if set, zero value otherwise.
func (o *EntityDefinitionPatchRequest) GetKindName() string {
	if o == nil || IsNil(o.KindName) {
		var ret string
		return ret
	}
	return *o.KindName
}

// GetKindNameOk returns a tuple with the KindName field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *EntityDefinitionPatchRequest) GetKindNameOk() (*string, bool) {
	if o == nil || IsNil(o.KindName) {
		return nil, false
	}
	return o.KindName, true
}

// HasKindName returns a boolean if a field has been set.
func (o *EntityDefinitionPatchRequest) HasKindName() bool {
	if o != nil && !IsNil(o.KindName) {
		return true
	}

	return false
}

// SetKindName gets a reference to the given string and assigns it to the KindName field.
func (o *EntityDefinitionPatchRequest) SetKindName(v string) {
	o.KindName = &v
}

// GetPluralOverride returns the PluralOverride field value if set, zero value otherwise.
func (o *EntityDefinitionPatchRequest) GetPluralOverride() string {
	if o == nil || IsNil(o.PluralOverride) {
		var ret string
		return ret
	}
	return *o.PluralOverride
}

// GetPluralOverrideOk returns a tuple with the PluralOverride field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *EntityDefinitionPatchRequest) GetPluralOverrideOk() (*string, bool) {
	if o == nil || IsNil(o.PluralOverride) {
		return nil, false
	}
	return o.PluralOverride, true
}

// HasPluralOverride returns a boolean if a field has been set.
func (o *EntityDefinitionPatchRequest) HasPluralOverride() bool {
	if o != nil && !IsNil(o.PluralOverride) {
		return true
	}

	return false
}

// SetPluralOverride gets a reference to the given string and assigns it to the PluralOverride field.
func (o *EntityDefinitionPatchRequest) SetPluralOverride(v string) {
	o.PluralOverride = &v
}

// GetDescription returns the Description field value if set, zero value otherwise.
func (o *EntityDefinitionPatchRequest) GetDescription() string {
	if o == nil || IsNil(o.Description) {
		var ret string
		return ret
	}
	return *o.Description
}

// GetDescriptionOk returns a tuple with the Description field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *EntityDefinitionPatchRequest) GetDescriptionOk() (*string, bool) {
	if o == nil || IsNil(o.Description) {
		return nil, false
	}
	return o.Description, true
}

// HasDescription returns a boolean if a field has been set.
func (o *EntityDefinitionPatchRequest) HasDescription() bool {
	if o != nil && !IsNil(o.Description) {
		return true
	}

	return false
}

// SetDescription gets a reference to the given string and assigns it to the Description field.
func (o *EntityDefinitionPatchRequest) SetDescription(v string) {
	o.Description = &v
}

func (o EntityDefinitionPatchRequest) MarshalJSON() ([]byte, error) {
	toSerialize, err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o EntityDefinitionPatchRequest) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.ProjectId) {
		toSerialize["project_id"] = o.ProjectId
	}
	if !IsNil(o.KindName) {
		toSerialize["kind_name"] = o.KindName
	}
	if !IsNil(o.PluralOverride) {
		toSerialize["plural_override"] = o.PluralOverride
	}
	if !IsNil(o.Description) {
		toSerialize["description"] = o.Description
	}
	return toSerialize, nil
}

type NullableEntityDefinitionPatchRequest struct {
	value *EntityDefinitionPatchRequest
	isSet bool
}

func (v NullableEntityDefinitionPatchRequest) Get() *EntityDefinitionPatchRequest {
	return v.value
}

func (v *NullableEntityDefinitionPatchRequest) Set(val *EntityDefinitionPatchRequest) {
	v.value = val
	v.isSet = true
}

func (v NullableEntityDefinitionPatchRequest) IsSet() bool {
	return v.isSet
}

func (v *NullableEntityDefinitionPatchRequest) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableEntityDefinitionPatchRequest(val *EntityDefinitionPatchRequest) *NullableEntityDefinitionPatchRequest {
	return &NullableEntityDefinitionPatchRequest{value: val, isSet: true}
}

func (v NullableEntityDefinitionPatchRequest) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableEntityDefinitionPatchRequest) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
