/*
rh-trex-ai Service API

rh-trex-ai Service API

API version: 0.0.1
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package openapi

import (
	"bytes"
	"encoding/json"
	"fmt"
	"time"
)

// checks if the EntityDefinition type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &EntityDefinition{}

// EntityDefinition struct for EntityDefinition
type EntityDefinition struct {
	Id             *string    `json:"id,omitempty"`
	Kind           *string    `json:"kind,omitempty"`
	Href           *string    `json:"href,omitempty"`
	CreatedAt      *time.Time `json:"created_at,omitempty"`
	UpdatedAt      *time.Time `json:"updated_at,omitempty"`
	ProjectId      string     `json:"project_id"`
	KindName       string     `json:"kind_name"`
	PluralOverride *string    `json:"plural_override,omitempty"`
	Description    *string    `json:"description,omitempty"`
}

type _EntityDefinition EntityDefinition

// NewEntityDefinition instantiates a new EntityDefinition object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewEntityDefinition(projectId string, kindName string) *EntityDefinition {
	this := EntityDefinition{}
	this.ProjectId = projectId
	this.KindName = kindName
	return &this
}

// NewEntityDefinitionWithDefaults instantiates a new EntityDefinition object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewEntityDefinitionWithDefaults() *EntityDefinition {
	this := EntityDefinition{}
	return &this
}

// GetId returns the Id field value if set, zero value otherwise.
func (o *EntityDefinition) GetId() string {
	if o == nil || IsNil(o.Id) {
		var ret string
		return ret
	}
	return *o.Id
}

// GetIdOk returns a tuple with the Id field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *EntityDefinition) GetIdOk() (*string, bool) {
	if o == nil || IsNil(o.Id) {
		return nil, false
	}
	return o.Id, true
}

// HasId returns a boolean if a field has been set.
func (o *EntityDefinition) HasId() bool {
	if o != nil && !IsNil(o.Id) {
		return true
	}

	return false
}

// SetId gets a reference to the given string and assigns it to the Id field.
func (o *EntityDefinition) SetId(v string) {
	o.Id = &v
}

// GetKind returns the Kind field value if set, zero value otherwise.
func (o *EntityDefinition) GetKind() string {
	if o == nil || IsNil(o.Kind) {
		var ret string
		return ret
	}
	return *o.Kind
}

// GetKindOk returns a tuple with the Kind field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *EntityDefinition) GetKindOk() (*string, bool) {
	if o == nil || IsNil(o.Kind) {
		return nil, false
	}
	return o.Kind, true
}

// HasKind returns a boolean if a field has been set.
func (o *EntityDefinition) HasKind() bool {
	if o != nil && !IsNil(o.Kind) {
		return true
	}

	return false
}

// SetKind gets a reference to the given string and assigns it to the Kind field.
func (o *EntityDefinition) SetKind(v string) {
	o.Kind = &v
}

// GetHref returns the Href field value if set, zero value otherwise.
func (o *EntityDefinition) GetHref() string {
	if o == nil || IsNil(o.Href) {
		var ret string
		return ret
	}
	return *o.Href
}

// GetHrefOk returns a tuple with the Href field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *EntityDefinition) GetHrefOk() (*string, bool) {
	if o == nil || IsNil(o.Href) {
		return nil, false
	}
	return o.Href, true
}

// HasHref returns a boolean if a field has been set.
func (o *EntityDefinition) HasHref() bool {
	if o != nil && !IsNil(o.Href) {
		return true
	}

	return false
}

// SetHref gets a reference to the given string and assigns it to the Href field.
func (o *EntityDefinition) SetHref(v string) {
	o.Href = &v
}

// GetCreatedAt returns the CreatedAt field value if set, zero value otherwise.
func (o *EntityDefinition) GetCreatedAt() time.Time {
	if o == nil || IsNil(o.CreatedAt) {
		var ret time.Time
		return ret
	}
	return *o.CreatedAt
}

// GetCreatedAtOk returns a tuple with the CreatedAt field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *EntityDefinition) GetCreatedAtOk() (*time.Time, bool) {
	if o == nil || IsNil(o.CreatedAt) {
		return nil, false
	}
	return o.CreatedAt, true
}

// HasCreatedAt returns a boolean if a field has been set.
func (o *EntityDefinition) HasCreatedAt() bool {
	if o != nil && !IsNil(o.CreatedAt) {
		return true
	}

	return false
}

// SetCreatedAt gets a reference to the given time.Time and assigns it to the CreatedAt field.
func (o *EntityDefinition) SetCreatedAt(v time.Time) {
	o.CreatedAt = &v
}

// GetUpdatedAt returns the UpdatedAt field value if set, zero value otherwise.
func (o *EntityDefinition) GetUpdatedAt() time.Time {
	if o == nil || IsNil(o.UpdatedAt) {
		var ret time.Time
		return ret
	}
	return *o.UpdatedAt
}

// GetUpdatedAtOk returns a tuple with the UpdatedAt field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *EntityDefinition) GetUpdatedAtOk() (*time.Time, bool) {
	if o == nil || IsNil(o.UpdatedAt) {
		return nil, false
	}
	return o.UpdatedAt, true
}

// HasUpdatedAt returns a boolean if a field has been set.
func (o *EntityDefinition) HasUpdatedAt() bool {
	if o != nil && !IsNil(o.UpdatedAt) {
		return true
	}

	return false
}

// SetUpdatedAt gets a reference to the given time.Time and assigns it to the UpdatedAt field.
func (o *EntityDefinition) SetUpdatedAt(v time.Time) {
	o.UpdatedAt = &v
}

// GetProjectId returns the ProjectId field value
func (o *EntityDefinition) GetProjectId() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.ProjectId
}

// GetProjectIdOk returns a tuple with the ProjectId field value
// and a boolean to check if the value has been set.
func (o *EntityDefinition) GetProjectIdOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.ProjectId, true
}

// SetProjectId sets field value
func (o *EntityDefinition) SetProjectId(v string) {
	o.ProjectId = v
}

// GetKindName returns the KindName field value
func (o *EntityDefinition) GetKindName() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.KindName
}

// GetKindNameOk returns a tuple with the KindName field value
// and a boolean to check if the value has been set.
func (o *EntityDefinition) GetKindNameOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.KindName, true
}

// SetKindName sets field value
func (o *EntityDefinition) SetKindName(v string) {
	o.KindName = v
}

// GetPluralOverride returns the PluralOverride field value if set, zero value otherwise.
func (o *EntityDefinition) GetPluralOverride() string {
	if o == nil || IsNil(o.PluralOverride) {
		var ret string
		return ret
	}
	return *o.PluralOverride
}

// GetPluralOverrideOk returns a tuple with the PluralOverride field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *EntityDefinition) GetPluralOverrideOk() (*string, bool) {
	if o == nil || IsNil(o.PluralOverride) {
		return nil, false
	}
	return o.PluralOverride, true
}

// HasPluralOverride returns a boolean if a field has been set.
func (o *EntityDefinition) HasPluralOverride() bool {
	if o != nil && !IsNil(o.PluralOverride) {
		return true
	}

	return false
}

// SetPluralOverride gets a reference to the given string and assigns it to the PluralOverride field.
func (o *EntityDefinition) SetPluralOverride(v string) {
	o.PluralOverride = &v
}

// GetDescription returns the Description field value if set, zero value otherwise.
func (o *EntityDefinition) GetDescription() string {
	if o == nil || IsNil(o.Description) {
		var ret string
		return ret
	}
	return *o.Description
}

// GetDescriptionOk returns a tuple with the Description field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *EntityDefinition) GetDescriptionOk() (*string, bool) {
	if o == nil || IsNil(o.Description) {
		return nil, false
	}
	return o.Description, true
}

// HasDescription returns a boolean if a field has been set.
func (o *EntityDefinition) HasDescription() bool {
	if o != nil && !IsNil(o.Description) {
		return true
	}

	return false
}

// SetDescription gets a reference to the given string and assigns it to the Description field.
func (o *EntityDefinition) SetDescription(v string) {
	o.Description = &v
}

func (o EntityDefinition) MarshalJSON() ([]byte, error) {
	toSerialize, err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o EntityDefinition) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.Id) {
		toSerialize["id"] = o.Id
	}
	if !IsNil(o.Kind) {
		toSerialize["kind"] = o.Kind
	}
	if !IsNil(o.Href) {
		toSerialize["href"] = o.Href
	}
	if !IsNil(o.CreatedAt) {
		toSerialize["created_at"] = o.CreatedAt
	}
	if !IsNil(o.UpdatedAt) {
		toSerialize["updated_at"] = o.UpdatedAt
	}
	toSerialize["project_id"] = o.ProjectId
	toSerialize["kind_name"] = o.KindName
	if !IsNil(o.PluralOverride) {
		toSerialize["plural_override"] = o.PluralOverride
	}
	if !IsNil(o.Description) {
		toSerialize["description"] = o.Description
	}
	return toSerialize, nil
}

func (o *EntityDefinition) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"project_id",
		"kind_name",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err
	}

	for _, requiredProperty := range requiredProperties {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varEntityDefinition := _EntityDefinition{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varEntityDefinition)

	if err != nil {
		return err
	}

	*o = EntityDefinition(varEntityDefinition)

	return err
}

type NullableEntityDefinition struct {
	value *EntityDefinition
	isSet bool
}

func (v NullableEntityDefinition) Get() *EntityDefinition {
	return v.value
}

func (v *NullableEntityDefinition) Set(val *EntityDefinition) {
	v.value = val
	v.isSet = true
}

func (v NullableEntityDefinition) IsSet() bool {
	return v.isSet
}

func (v *NullableEntityDefinition) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableEntityDefinition(val *EntityDefinition) *NullableEntityDefinition {
	return &NullableEntityDefinition{value: val, isSet: true}
}

func (v NullableEntityDefinition) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableEntityDefinition) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
