/*
rh-trex-ai Service API

rh-trex-ai Service API

API version: 0.0.1
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package openapi

import (
	"encoding/json"
	"time"
)

// checks if the BuildPatchRequest type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &BuildPatchRequest{}

// BuildPatchRequest struct for BuildPatchRequest
type BuildPatchRequest struct {
	ProjectId   *string    `json:"project_id,omitempty"`
	Status      *string    `json:"status,omitempty"`
	BuildLog    *string    `json:"build_log,omitempty"`
	TriggeredBy *string    `json:"triggered_by,omitempty"`
	CompletedAt *time.Time `json:"completed_at,omitempty"`
}

// NewBuildPatchRequest instantiates a new BuildPatchRequest object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewBuildPatchRequest() *BuildPatchRequest {
	this := BuildPatchRequest{}
	return &this
}

// NewBuildPatchRequestWithDefaults instantiates a new BuildPatchRequest object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewBuildPatchRequestWithDefaults() *BuildPatchRequest {
	this := BuildPatchRequest{}
	return &this
}

// GetProjectId returns the ProjectId field value if set, zero value otherwise.
func (o *BuildPatchRequest) GetProjectId() string {
	if o == nil || IsNil(o.ProjectId) {
		var ret string
		return ret
	}
	return *o.ProjectId
}

// GetProjectIdOk returns a tuple with the ProjectId field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *BuildPatchRequest) GetProjectIdOk() (*string, bool) {
	if o == nil || IsNil(o.ProjectId) {
		return nil, false
	}
	return o.ProjectId, true
}

// HasProjectId returns a boolean if a field has been set.
func (o *BuildPatchRequest) HasProjectId() bool {
	if o != nil && !IsNil(o.ProjectId) {
		return true
	}

	return false
}

// SetProjectId gets a reference to the given string and assigns it to the ProjectId field.
func (o *BuildPatchRequest) SetProjectId(v string) {
	o.ProjectId = &v
}

// GetStatus returns the Status field value if set, zero value otherwise.
func (o *BuildPatchRequest) GetStatus() string {
	if o == nil || IsNil(o.Status) {
		var ret string
		return ret
	}
	return *o.Status
}

// GetStatusOk returns a tuple with the Status field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *BuildPatchRequest) GetStatusOk() (*string, bool) {
	if o == nil || IsNil(o.Status) {
		return nil, false
	}
	return o.Status, true
}

// HasStatus returns a boolean if a field has been set.
func (o *BuildPatchRequest) HasStatus() bool {
	if o != nil && !IsNil(o.Status) {
		return true
	}

	return false
}

// SetStatus gets a reference to the given string and assigns it to the Status field.
func (o *BuildPatchRequest) SetStatus(v string) {
	o.Status = &v
}

// GetBuildLog returns the BuildLog field value if set, zero value otherwise.
func (o *BuildPatchRequest) GetBuildLog() string {
	if o == nil || IsNil(o.BuildLog) {
		var ret string
		return ret
	}
	return *o.BuildLog
}

// GetBuildLogOk returns a tuple with the BuildLog field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *BuildPatchRequest) GetBuildLogOk() (*string, bool) {
	if o == nil || IsNil(o.BuildLog) {
		return nil, false
	}
	return o.BuildLog, true
}

// HasBuildLog returns a boolean if a field has been set.
func (o *BuildPatchRequest) HasBuildLog() bool {
	if o != nil && !IsNil(o.BuildLog) {
		return true
	}

	return false
}

// SetBuildLog gets a reference to the given string and assigns it to the BuildLog field.
func (o *BuildPatchRequest) SetBuildLog(v string) {
	o.BuildLog = &v
}

// GetTriggeredBy returns the TriggeredBy field value if set, zero value otherwise.
func (o *BuildPatchRequest) GetTriggeredBy() string {
	if o == nil || IsNil(o.TriggeredBy) {
		var ret string
		return ret
	}
	return *o.TriggeredBy
}

// GetTriggeredByOk returns a tuple with the TriggeredBy field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *BuildPatchRequest) GetTriggeredByOk() (*string, bool) {
	if o == nil || IsNil(o.TriggeredBy) {
		return nil, false
	}
	return o.TriggeredBy, true
}

// HasTriggeredBy returns a boolean if a field has been set.
func (o *BuildPatchRequest) HasTriggeredBy() bool {
	if o != nil && !IsNil(o.TriggeredBy) {
		return true
	}

	return false
}

// SetTriggeredBy gets a reference to the given string and assigns it to the TriggeredBy field.
func (o *BuildPatchRequest) SetTriggeredBy(v string) {
	o.TriggeredBy = &v
}

// GetCompletedAt returns the CompletedAt field value if set, zero value otherwise.
func (o *BuildPatchRequest) GetCompletedAt() time.Time {
	if o == nil || IsNil(o.CompletedAt) {
		var ret time.Time
		return ret
	}
	return *o.CompletedAt
}

// GetCompletedAtOk returns a tuple with the CompletedAt field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *BuildPatchRequest) GetCompletedAtOk() (*time.Time, bool) {
	if o == nil || IsNil(o.CompletedAt) {
		return nil, false
	}
	return o.CompletedAt, true
}

// HasCompletedAt returns a boolean if a field has been set.
func (o *BuildPatchRequest) HasCompletedAt() bool {
	if o != nil && !IsNil(o.CompletedAt) {
		return true
	}

	return false
}

// SetCompletedAt gets a reference to the given time.Time and assigns it to the CompletedAt field.
func (o *BuildPatchRequest) SetCompletedAt(v time.Time) {
	o.CompletedAt = &v
}

func (o BuildPatchRequest) MarshalJSON() ([]byte, error) {
	toSerialize, err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o BuildPatchRequest) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.ProjectId) {
		toSerialize["project_id"] = o.ProjectId
	}
	if !IsNil(o.Status) {
		toSerialize["status"] = o.Status
	}
	if !IsNil(o.BuildLog) {
		toSerialize["build_log"] = o.BuildLog
	}
	if !IsNil(o.TriggeredBy) {
		toSerialize["triggered_by"] = o.TriggeredBy
	}
	if !IsNil(o.CompletedAt) {
		toSerialize["completed_at"] = o.CompletedAt
	}
	return toSerialize, nil
}

type NullableBuildPatchRequest struct {
	value *BuildPatchRequest
	isSet bool
}

func (v NullableBuildPatchRequest) Get() *BuildPatchRequest {
	return v.value
}

func (v *NullableBuildPatchRequest) Set(val *BuildPatchRequest) {
	v.value = val
	v.isSet = true
}

func (v NullableBuildPatchRequest) IsSet() bool {
	return v.isSet
}

func (v *NullableBuildPatchRequest) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableBuildPatchRequest(val *BuildPatchRequest) *NullableBuildPatchRequest {
	return &NullableBuildPatchRequest{value: val, isSet: true}
}

func (v NullableBuildPatchRequest) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableBuildPatchRequest) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
