// Vendored subset of the OpenShell inference proto.
// Source: github.com/nvidia/openshell  proto/inference.proto
// Only SetInferenceRoute and GetInferenceRoute are needed for ACP.

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        (unknown)
// source: openshell/inference/v1/inference.proto

package v1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type SetInferenceRouteRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ProviderName  string                 `protobuf:"bytes,1,opt,name=provider_name,json=providerName,proto3" json:"provider_name,omitempty"`
	ModelId       string                 `protobuf:"bytes,2,opt,name=model_id,json=modelId,proto3" json:"model_id,omitempty"`
	RouteName     string                 `protobuf:"bytes,3,opt,name=route_name,json=routeName,proto3" json:"route_name,omitempty"`
	Verify        bool                   `protobuf:"varint,4,opt,name=verify,proto3" json:"verify,omitempty"`
	NoVerify      bool                   `protobuf:"varint,5,opt,name=no_verify,json=noVerify,proto3" json:"no_verify,omitempty"`
	TimeoutSecs   uint64                 `protobuf:"varint,6,opt,name=timeout_secs,json=timeoutSecs,proto3" json:"timeout_secs,omitempty"`
	Workspace     string                 `protobuf:"bytes,7,opt,name=workspace,proto3" json:"workspace,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SetInferenceRouteRequest) Reset() {
	*x = SetInferenceRouteRequest{}
	mi := &file_openshell_inference_v1_inference_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SetInferenceRouteRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SetInferenceRouteRequest) ProtoMessage() {}

func (x *SetInferenceRouteRequest) ProtoReflect() protoreflect.Message {
	mi := &file_openshell_inference_v1_inference_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SetInferenceRouteRequest.ProtoReflect.Descriptor instead.
func (*SetInferenceRouteRequest) Descriptor() ([]byte, []int) {
	return file_openshell_inference_v1_inference_proto_rawDescGZIP(), []int{0}
}

func (x *SetInferenceRouteRequest) GetProviderName() string {
	if x != nil {
		return x.ProviderName
	}
	return ""
}

func (x *SetInferenceRouteRequest) GetModelId() string {
	if x != nil {
		return x.ModelId
	}
	return ""
}

func (x *SetInferenceRouteRequest) GetRouteName() string {
	if x != nil {
		return x.RouteName
	}
	return ""
}

func (x *SetInferenceRouteRequest) GetVerify() bool {
	if x != nil {
		return x.Verify
	}
	return false
}

func (x *SetInferenceRouteRequest) GetNoVerify() bool {
	if x != nil {
		return x.NoVerify
	}
	return false
}

func (x *SetInferenceRouteRequest) GetTimeoutSecs() uint64 {
	if x != nil {
		return x.TimeoutSecs
	}
	return 0
}

func (x *SetInferenceRouteRequest) GetWorkspace() string {
	if x != nil {
		return x.Workspace
	}
	return ""
}

type SetInferenceRouteResponse struct {
	state               protoimpl.MessageState `protogen:"open.v1"`
	ProviderName        string                 `protobuf:"bytes,1,opt,name=provider_name,json=providerName,proto3" json:"provider_name,omitempty"`
	ModelId             string                 `protobuf:"bytes,2,opt,name=model_id,json=modelId,proto3" json:"model_id,omitempty"`
	Version             uint64                 `protobuf:"varint,3,opt,name=version,proto3" json:"version,omitempty"`
	RouteName           string                 `protobuf:"bytes,4,opt,name=route_name,json=routeName,proto3" json:"route_name,omitempty"`
	ValidationPerformed bool                   `protobuf:"varint,5,opt,name=validation_performed,json=validationPerformed,proto3" json:"validation_performed,omitempty"`
	TimeoutSecs         uint64                 `protobuf:"varint,7,opt,name=timeout_secs,json=timeoutSecs,proto3" json:"timeout_secs,omitempty"`
	Workspace           string                 `protobuf:"bytes,8,opt,name=workspace,proto3" json:"workspace,omitempty"`
	unknownFields       protoimpl.UnknownFields
	sizeCache           protoimpl.SizeCache
}

func (x *SetInferenceRouteResponse) Reset() {
	*x = SetInferenceRouteResponse{}
	mi := &file_openshell_inference_v1_inference_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SetInferenceRouteResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SetInferenceRouteResponse) ProtoMessage() {}

func (x *SetInferenceRouteResponse) ProtoReflect() protoreflect.Message {
	mi := &file_openshell_inference_v1_inference_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SetInferenceRouteResponse.ProtoReflect.Descriptor instead.
func (*SetInferenceRouteResponse) Descriptor() ([]byte, []int) {
	return file_openshell_inference_v1_inference_proto_rawDescGZIP(), []int{1}
}

func (x *SetInferenceRouteResponse) GetProviderName() string {
	if x != nil {
		return x.ProviderName
	}
	return ""
}

func (x *SetInferenceRouteResponse) GetModelId() string {
	if x != nil {
		return x.ModelId
	}
	return ""
}

func (x *SetInferenceRouteResponse) GetVersion() uint64 {
	if x != nil {
		return x.Version
	}
	return 0
}

func (x *SetInferenceRouteResponse) GetRouteName() string {
	if x != nil {
		return x.RouteName
	}
	return ""
}

func (x *SetInferenceRouteResponse) GetValidationPerformed() bool {
	if x != nil {
		return x.ValidationPerformed
	}
	return false
}

func (x *SetInferenceRouteResponse) GetTimeoutSecs() uint64 {
	if x != nil {
		return x.TimeoutSecs
	}
	return 0
}

func (x *SetInferenceRouteResponse) GetWorkspace() string {
	if x != nil {
		return x.Workspace
	}
	return ""
}

type GetInferenceRouteRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	RouteName     string                 `protobuf:"bytes,1,opt,name=route_name,json=routeName,proto3" json:"route_name,omitempty"`
	Workspace     string                 `protobuf:"bytes,2,opt,name=workspace,proto3" json:"workspace,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetInferenceRouteRequest) Reset() {
	*x = GetInferenceRouteRequest{}
	mi := &file_openshell_inference_v1_inference_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetInferenceRouteRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetInferenceRouteRequest) ProtoMessage() {}

func (x *GetInferenceRouteRequest) ProtoReflect() protoreflect.Message {
	mi := &file_openshell_inference_v1_inference_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetInferenceRouteRequest.ProtoReflect.Descriptor instead.
func (*GetInferenceRouteRequest) Descriptor() ([]byte, []int) {
	return file_openshell_inference_v1_inference_proto_rawDescGZIP(), []int{2}
}

func (x *GetInferenceRouteRequest) GetRouteName() string {
	if x != nil {
		return x.RouteName
	}
	return ""
}

func (x *GetInferenceRouteRequest) GetWorkspace() string {
	if x != nil {
		return x.Workspace
	}
	return ""
}

type GetInferenceRouteResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ProviderName  string                 `protobuf:"bytes,1,opt,name=provider_name,json=providerName,proto3" json:"provider_name,omitempty"`
	ModelId       string                 `protobuf:"bytes,2,opt,name=model_id,json=modelId,proto3" json:"model_id,omitempty"`
	Version       uint64                 `protobuf:"varint,3,opt,name=version,proto3" json:"version,omitempty"`
	RouteName     string                 `protobuf:"bytes,4,opt,name=route_name,json=routeName,proto3" json:"route_name,omitempty"`
	TimeoutSecs   uint64                 `protobuf:"varint,5,opt,name=timeout_secs,json=timeoutSecs,proto3" json:"timeout_secs,omitempty"`
	Workspace     string                 `protobuf:"bytes,6,opt,name=workspace,proto3" json:"workspace,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetInferenceRouteResponse) Reset() {
	*x = GetInferenceRouteResponse{}
	mi := &file_openshell_inference_v1_inference_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetInferenceRouteResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetInferenceRouteResponse) ProtoMessage() {}

func (x *GetInferenceRouteResponse) ProtoReflect() protoreflect.Message {
	mi := &file_openshell_inference_v1_inference_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetInferenceRouteResponse.ProtoReflect.Descriptor instead.
func (*GetInferenceRouteResponse) Descriptor() ([]byte, []int) {
	return file_openshell_inference_v1_inference_proto_rawDescGZIP(), []int{3}
}

func (x *GetInferenceRouteResponse) GetProviderName() string {
	if x != nil {
		return x.ProviderName
	}
	return ""
}

func (x *GetInferenceRouteResponse) GetModelId() string {
	if x != nil {
		return x.ModelId
	}
	return ""
}

func (x *GetInferenceRouteResponse) GetVersion() uint64 {
	if x != nil {
		return x.Version
	}
	return 0
}

func (x *GetInferenceRouteResponse) GetRouteName() string {
	if x != nil {
		return x.RouteName
	}
	return ""
}

func (x *GetInferenceRouteResponse) GetTimeoutSecs() uint64 {
	if x != nil {
		return x.TimeoutSecs
	}
	return 0
}

func (x *GetInferenceRouteResponse) GetWorkspace() string {
	if x != nil {
		return x.Workspace
	}
	return ""
}

var File_openshell_inference_v1_inference_proto protoreflect.FileDescriptor

const file_openshell_inference_v1_inference_proto_rawDesc = "" +
	"\n" +
	"&openshell/inference/v1/inference.proto\x12\x16openshell.inference.v1\"\xef\x01\n" +
	"\x18SetInferenceRouteRequest\x12#\n" +
	"\rprovider_name\x18\x01 \x01(\tR\fproviderName\x12\x19\n" +
	"\bmodel_id\x18\x02 \x01(\tR\amodelId\x12\x1d\n" +
	"\n" +
	"route_name\x18\x03 \x01(\tR\trouteName\x12\x16\n" +
	"\x06verify\x18\x04 \x01(\bR\x06verify\x12\x1b\n" +
	"\tno_verify\x18\x05 \x01(\bR\bnoVerify\x12!\n" +
	"\ftimeout_secs\x18\x06 \x01(\x04R\vtimeoutSecs\x12\x1c\n" +
	"\tworkspace\x18\a \x01(\tR\tworkspace\"\x88\x02\n" +
	"\x19SetInferenceRouteResponse\x12#\n" +
	"\rprovider_name\x18\x01 \x01(\tR\fproviderName\x12\x19\n" +
	"\bmodel_id\x18\x02 \x01(\tR\amodelId\x12\x18\n" +
	"\aversion\x18\x03 \x01(\x04R\aversion\x12\x1d\n" +
	"\n" +
	"route_name\x18\x04 \x01(\tR\trouteName\x121\n" +
	"\x14validation_performed\x18\x05 \x01(\bR\x13validationPerformed\x12!\n" +
	"\ftimeout_secs\x18\a \x01(\x04R\vtimeoutSecs\x12\x1c\n" +
	"\tworkspace\x18\b \x01(\tR\tworkspace\"W\n" +
	"\x18GetInferenceRouteRequest\x12\x1d\n" +
	"\n" +
	"route_name\x18\x01 \x01(\tR\trouteName\x12\x1c\n" +
	"\tworkspace\x18\x02 \x01(\tR\tworkspace\"\xd5\x01\n" +
	"\x19GetInferenceRouteResponse\x12#\n" +
	"\rprovider_name\x18\x01 \x01(\tR\fproviderName\x12\x19\n" +
	"\bmodel_id\x18\x02 \x01(\tR\amodelId\x12\x18\n" +
	"\aversion\x18\x03 \x01(\x04R\aversion\x12\x1d\n" +
	"\n" +
	"route_name\x18\x04 \x01(\tR\trouteName\x12!\n" +
	"\ftimeout_secs\x18\x05 \x01(\x04R\vtimeoutSecs\x12\x1c\n" +
	"\tworkspace\x18\x06 \x01(\tR\tworkspace2\xff\x01\n" +
	"\tInference\x12x\n" +
	"\x11SetInferenceRoute\x120.openshell.inference.v1.SetInferenceRouteRequest\x1a1.openshell.inference.v1.SetInferenceRouteResponse\x12x\n" +
	"\x11GetInferenceRoute\x120.openshell.inference.v1.GetInferenceRouteRequest\x1a1.openshell.inference.v1.GetInferenceRouteResponseB\x81\x01Z\x7fgithub.com/openshift-online/agent-control-plane/components/ambient-control-plane/internal/openshell/grpc/openshell/inference/v1b\x06proto3"

var (
	file_openshell_inference_v1_inference_proto_rawDescOnce sync.Once
	file_openshell_inference_v1_inference_proto_rawDescData []byte
)

func file_openshell_inference_v1_inference_proto_rawDescGZIP() []byte {
	file_openshell_inference_v1_inference_proto_rawDescOnce.Do(func() {
		file_openshell_inference_v1_inference_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_openshell_inference_v1_inference_proto_rawDesc), len(file_openshell_inference_v1_inference_proto_rawDesc)))
	})
	return file_openshell_inference_v1_inference_proto_rawDescData
}

var file_openshell_inference_v1_inference_proto_msgTypes = make([]protoimpl.MessageInfo, 4)
var file_openshell_inference_v1_inference_proto_goTypes = []any{
	(*SetInferenceRouteRequest)(nil),  // 0: openshell.inference.v1.SetInferenceRouteRequest
	(*SetInferenceRouteResponse)(nil), // 1: openshell.inference.v1.SetInferenceRouteResponse
	(*GetInferenceRouteRequest)(nil),  // 2: openshell.inference.v1.GetInferenceRouteRequest
	(*GetInferenceRouteResponse)(nil), // 3: openshell.inference.v1.GetInferenceRouteResponse
}
var file_openshell_inference_v1_inference_proto_depIdxs = []int32{
	0, // 0: openshell.inference.v1.Inference.SetInferenceRoute:input_type -> openshell.inference.v1.SetInferenceRouteRequest
	2, // 1: openshell.inference.v1.Inference.GetInferenceRoute:input_type -> openshell.inference.v1.GetInferenceRouteRequest
	1, // 2: openshell.inference.v1.Inference.SetInferenceRoute:output_type -> openshell.inference.v1.SetInferenceRouteResponse
	3, // 3: openshell.inference.v1.Inference.GetInferenceRoute:output_type -> openshell.inference.v1.GetInferenceRouteResponse
	2, // [2:4] is the sub-list for method output_type
	0, // [0:2] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_openshell_inference_v1_inference_proto_init() }
func file_openshell_inference_v1_inference_proto_init() {
	if File_openshell_inference_v1_inference_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_openshell_inference_v1_inference_proto_rawDesc), len(file_openshell_inference_v1_inference_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   4,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_openshell_inference_v1_inference_proto_goTypes,
		DependencyIndexes: file_openshell_inference_v1_inference_proto_depIdxs,
		MessageInfos:      file_openshell_inference_v1_inference_proto_msgTypes,
	}.Build()
	File_openshell_inference_v1_inference_proto = out.File
	file_openshell_inference_v1_inference_proto_goTypes = nil
	file_openshell_inference_v1_inference_proto_depIdxs = nil
}
