apiVersion: v1
kind: Service
metadata:
  name: trex-console
  labels:
    app: trex-console
    app.kubernetes.io/name: trex-console
    app.kubernetes.io/part-of: rh-trex-ai
  annotations:
    service.beta.openshift.io/serving-cert-secret-name: trex-console-cert
spec:
  ports:
    - name: 9443-tcp
      protocol: TCP
      port: 9443
      targetPort: 9443
  selector:
    app: trex-console
  type: ClusterIP
