// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        (unknown)
// source: rh_trex/v1/builds.proto

package rh_trex_v1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Build struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Metadata      *ObjectReference       `protobuf:"bytes,1,opt,name=metadata,proto3" json:"metadata,omitempty"`
	ProjectId     string                 `protobuf:"bytes,2,opt,name=project_id,json=projectId,proto3" json:"project_id,omitempty"`
	Status        string                 `protobuf:"bytes,3,opt,name=status,proto3" json:"status,omitempty"`
	BuildLog      *string                `protobuf:"bytes,4,opt,name=build_log,json=buildLog,proto3,oneof" json:"build_log,omitempty"`
	TriggeredBy   *string                `protobuf:"bytes,5,opt,name=triggered_by,json=triggeredBy,proto3,oneof" json:"triggered_by,omitempty"`
	CompletedAt   *timestamppb.Timestamp `protobuf:"bytes,6,opt,name=completed_at,json=completedAt,proto3,oneof" json:"completed_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Build) Reset() {
	*x = Build{}
	mi := &file_rh_trex_v1_builds_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Build) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Build) ProtoMessage() {}

func (x *Build) ProtoReflect() protoreflect.Message {
	mi := &file_rh_trex_v1_builds_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Build.ProtoReflect.Descriptor instead.
func (*Build) Descriptor() ([]byte, []int) {
	return file_rh_trex_v1_builds_proto_rawDescGZIP(), []int{0}
}

func (x *Build) GetMetadata() *ObjectReference {
	if x != nil {
		return x.Metadata
	}
	return nil
}

func (x *Build) GetProjectId() string {
	if x != nil {
		return x.ProjectId
	}
	return ""
}

func (x *Build) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *Build) GetBuildLog() string {
	if x != nil && x.BuildLog != nil {
		return *x.BuildLog
	}
	return ""
}

func (x *Build) GetTriggeredBy() string {
	if x != nil && x.TriggeredBy != nil {
		return *x.TriggeredBy
	}
	return ""
}

func (x *Build) GetCompletedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.CompletedAt
	}
	return nil
}

type CreateBuildRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ProjectId     string                 `protobuf:"bytes,1,opt,name=project_id,json=projectId,proto3" json:"project_id,omitempty"`
	Status        string                 `protobuf:"bytes,2,opt,name=status,proto3" json:"status,omitempty"`
	BuildLog      *string                `protobuf:"bytes,3,opt,name=build_log,json=buildLog,proto3,oneof" json:"build_log,omitempty"`
	TriggeredBy   *string                `protobuf:"bytes,4,opt,name=triggered_by,json=triggeredBy,proto3,oneof" json:"triggered_by,omitempty"`
	CompletedAt   *timestamppb.Timestamp `protobuf:"bytes,5,opt,name=completed_at,json=completedAt,proto3,oneof" json:"completed_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateBuildRequest) Reset() {
	*x = CreateBuildRequest{}
	mi := &file_rh_trex_v1_builds_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateBuildRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateBuildRequest) ProtoMessage() {}

func (x *CreateBuildRequest) ProtoReflect() protoreflect.Message {
	mi := &file_rh_trex_v1_builds_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateBuildRequest.ProtoReflect.Descriptor instead.
func (*CreateBuildRequest) Descriptor() ([]byte, []int) {
	return file_rh_trex_v1_builds_proto_rawDescGZIP(), []int{1}
}

func (x *CreateBuildRequest) GetProjectId() string {
	if x != nil {
		return x.ProjectId
	}
	return ""
}

func (x *CreateBuildRequest) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *CreateBuildRequest) GetBuildLog() string {
	if x != nil && x.BuildLog != nil {
		return *x.BuildLog
	}
	return ""
}

func (x *CreateBuildRequest) GetTriggeredBy() string {
	if x != nil && x.TriggeredBy != nil {
		return *x.TriggeredBy
	}
	return ""
}

func (x *CreateBuildRequest) GetCompletedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.CompletedAt
	}
	return nil
}

type GetBuildRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetBuildRequest) Reset() {
	*x = GetBuildRequest{}
	mi := &file_rh_trex_v1_builds_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetBuildRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetBuildRequest) ProtoMessage() {}

func (x *GetBuildRequest) ProtoReflect() protoreflect.Message {
	mi := &file_rh_trex_v1_builds_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetBuildRequest.ProtoReflect.Descriptor instead.
func (*GetBuildRequest) Descriptor() ([]byte, []int) {
	return file_rh_trex_v1_builds_proto_rawDescGZIP(), []int{2}
}

func (x *GetBuildRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

type UpdateBuildRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	ProjectId     *string                `protobuf:"bytes,2,opt,name=project_id,json=projectId,proto3,oneof" json:"project_id,omitempty"`
	Status        *string                `protobuf:"bytes,3,opt,name=status,proto3,oneof" json:"status,omitempty"`
	BuildLog      *string                `protobuf:"bytes,4,opt,name=build_log,json=buildLog,proto3,oneof" json:"build_log,omitempty"`
	TriggeredBy   *string                `protobuf:"bytes,5,opt,name=triggered_by,json=triggeredBy,proto3,oneof" json:"triggered_by,omitempty"`
	CompletedAt   *timestamppb.Timestamp `protobuf:"bytes,6,opt,name=completed_at,json=completedAt,proto3,oneof" json:"completed_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateBuildRequest) Reset() {
	*x = UpdateBuildRequest{}
	mi := &file_rh_trex_v1_builds_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateBuildRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateBuildRequest) ProtoMessage() {}

func (x *UpdateBuildRequest) ProtoReflect() protoreflect.Message {
	mi := &file_rh_trex_v1_builds_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateBuildRequest.ProtoReflect.Descriptor instead.
func (*UpdateBuildRequest) Descriptor() ([]byte, []int) {
	return file_rh_trex_v1_builds_proto_rawDescGZIP(), []int{3}
}

func (x *UpdateBuildRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *UpdateBuildRequest) GetProjectId() string {
	if x != nil && x.ProjectId != nil {
		return *x.ProjectId
	}
	return ""
}

func (x *UpdateBuildRequest) GetStatus() string {
	if x != nil && x.Status != nil {
		return *x.Status
	}
	return ""
}

func (x *UpdateBuildRequest) GetBuildLog() string {
	if x != nil && x.BuildLog != nil {
		return *x.BuildLog
	}
	return ""
}

func (x *UpdateBuildRequest) GetTriggeredBy() string {
	if x != nil && x.TriggeredBy != nil {
		return *x.TriggeredBy
	}
	return ""
}

func (x *UpdateBuildRequest) GetCompletedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.CompletedAt
	}
	return nil
}

type DeleteBuildRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteBuildRequest) Reset() {
	*x = DeleteBuildRequest{}
	mi := &file_rh_trex_v1_builds_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteBuildRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteBuildRequest) ProtoMessage() {}

func (x *DeleteBuildRequest) ProtoReflect() protoreflect.Message {
	mi := &file_rh_trex_v1_builds_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteBuildRequest.ProtoReflect.Descriptor instead.
func (*DeleteBuildRequest) Descriptor() ([]byte, []int) {
	return file_rh_trex_v1_builds_proto_rawDescGZIP(), []int{4}
}

func (x *DeleteBuildRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

type ListBuildsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Page          int32                  `protobuf:"varint,1,opt,name=page,proto3" json:"page,omitempty"`
	Size          int32                  `protobuf:"varint,2,opt,name=size,proto3" json:"size,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListBuildsRequest) Reset() {
	*x = ListBuildsRequest{}
	mi := &file_rh_trex_v1_builds_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListBuildsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListBuildsRequest) ProtoMessage() {}

func (x *ListBuildsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_rh_trex_v1_builds_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListBuildsRequest.ProtoReflect.Descriptor instead.
func (*ListBuildsRequest) Descriptor() ([]byte, []int) {
	return file_rh_trex_v1_builds_proto_rawDescGZIP(), []int{5}
}

func (x *ListBuildsRequest) GetPage() int32 {
	if x != nil {
		return x.Page
	}
	return 0
}

func (x *ListBuildsRequest) GetSize() int32 {
	if x != nil {
		return x.Size
	}
	return 0
}

type ListBuildsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Items         []*Build               `protobuf:"bytes,1,rep,name=items,proto3" json:"items,omitempty"`
	Metadata      *ListMeta              `protobuf:"bytes,2,opt,name=metadata,proto3" json:"metadata,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListBuildsResponse) Reset() {
	*x = ListBuildsResponse{}
	mi := &file_rh_trex_v1_builds_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListBuildsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListBuildsResponse) ProtoMessage() {}

func (x *ListBuildsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_rh_trex_v1_builds_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListBuildsResponse.ProtoReflect.Descriptor instead.
func (*ListBuildsResponse) Descriptor() ([]byte, []int) {
	return file_rh_trex_v1_builds_proto_rawDescGZIP(), []int{6}
}

func (x *ListBuildsResponse) GetItems() []*Build {
	if x != nil {
		return x.Items
	}
	return nil
}

func (x *ListBuildsResponse) GetMetadata() *ListMeta {
	if x != nil {
		return x.Metadata
	}
	return nil
}

type DeleteBuildResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteBuildResponse) Reset() {
	*x = DeleteBuildResponse{}
	mi := &file_rh_trex_v1_builds_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteBuildResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteBuildResponse) ProtoMessage() {}

func (x *DeleteBuildResponse) ProtoReflect() protoreflect.Message {
	mi := &file_rh_trex_v1_builds_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteBuildResponse.ProtoReflect.Descriptor instead.
func (*DeleteBuildResponse) Descriptor() ([]byte, []int) {
	return file_rh_trex_v1_builds_proto_rawDescGZIP(), []int{7}
}

type WatchBuildsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *WatchBuildsRequest) Reset() {
	*x = WatchBuildsRequest{}
	mi := &file_rh_trex_v1_builds_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *WatchBuildsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*WatchBuildsRequest) ProtoMessage() {}

func (x *WatchBuildsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_rh_trex_v1_builds_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use WatchBuildsRequest.ProtoReflect.Descriptor instead.
func (*WatchBuildsRequest) Descriptor() ([]byte, []int) {
	return file_rh_trex_v1_builds_proto_rawDescGZIP(), []int{8}
}

type BuildWatchEvent struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Type          EventType              `protobuf:"varint,1,opt,name=type,proto3,enum=rh_trex.v1.EventType" json:"type,omitempty"`
	Build         *Build                 `protobuf:"bytes,2,opt,name=build,proto3" json:"build,omitempty"`
	ResourceId    string                 `protobuf:"bytes,3,opt,name=resource_id,json=resourceId,proto3" json:"resource_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *BuildWatchEvent) Reset() {
	*x = BuildWatchEvent{}
	mi := &file_rh_trex_v1_builds_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BuildWatchEvent) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BuildWatchEvent) ProtoMessage() {}

func (x *BuildWatchEvent) ProtoReflect() protoreflect.Message {
	mi := &file_rh_trex_v1_builds_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BuildWatchEvent.ProtoReflect.Descriptor instead.
func (*BuildWatchEvent) Descriptor() ([]byte, []int) {
	return file_rh_trex_v1_builds_proto_rawDescGZIP(), []int{9}
}

func (x *BuildWatchEvent) GetType() EventType {
	if x != nil {
		return x.Type
	}
	return EventType_EVENT_TYPE_UNSPECIFIED
}

func (x *BuildWatchEvent) GetBuild() *Build {
	if x != nil {
		return x.Build
	}
	return nil
}

func (x *BuildWatchEvent) GetResourceId() string {
	if x != nil {
		return x.ResourceId
	}
	return ""
}

var File_rh_trex_v1_builds_proto protoreflect.FileDescriptor

const file_rh_trex_v1_builds_proto_rawDesc = "" +
	"\n" +
	"\x17rh_trex/v1/builds.proto\x12\n" +
	"rh_trex.v1\x1a\x17rh_trex/v1/common.proto\x1a\x1fgoogle/protobuf/timestamp.proto\"\xb5\x02\n" +
	"\x05Build\x127\n" +
	"\bmetadata\x18\x01 \x01(\v2\x1b.rh_trex.v1.ObjectReferenceR\bmetadata\x12\x1d\n" +
	"\n" +
	"project_id\x18\x02 \x01(\tR\tprojectId\x12\x16\n" +
	"\x06status\x18\x03 \x01(\tR\x06status\x12 \n" +
	"\tbuild_log\x18\x04 \x01(\tH\x00R\bbuildLog\x88\x01\x01\x12&\n" +
	"\ftriggered_by\x18\x05 \x01(\tH\x01R\vtriggeredBy\x88\x01\x01\x12B\n" +
	"\fcompleted_at\x18\x06 \x01(\v2\x1a.google.protobuf.TimestampH\x02R\vcompletedAt\x88\x01\x01B\f\n" +
	"\n" +
	"_build_logB\x0f\n" +
	"\r_triggered_byB\x0f\n" +
	"\r_completed_at\"\x89\x02\n" +
	"\x12CreateBuildRequest\x12\x1d\n" +
	"\n" +
	"project_id\x18\x01 \x01(\tR\tprojectId\x12\x16\n" +
	"\x06status\x18\x02 \x01(\tR\x06status\x12 \n" +
	"\tbuild_log\x18\x03 \x01(\tH\x00R\bbuildLog\x88\x01\x01\x12&\n" +
	"\ftriggered_by\x18\x04 \x01(\tH\x01R\vtriggeredBy\x88\x01\x01\x12B\n" +
	"\fcompleted_at\x18\x05 \x01(\v2\x1a.google.protobuf.TimestampH\x02R\vcompletedAt\x88\x01\x01B\f\n" +
	"\n" +
	"_build_logB\x0f\n" +
	"\r_triggered_byB\x0f\n" +
	"\r_completed_at\"!\n" +
	"\x0fGetBuildRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\"\xbd\x02\n" +
	"\x12UpdateBuildRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\"\n" +
	"\n" +
	"project_id\x18\x02 \x01(\tH\x00R\tprojectId\x88\x01\x01\x12\x1b\n" +
	"\x06status\x18\x03 \x01(\tH\x01R\x06status\x88\x01\x01\x12 \n" +
	"\tbuild_log\x18\x04 \x01(\tH\x02R\bbuildLog\x88\x01\x01\x12&\n" +
	"\ftriggered_by\x18\x05 \x01(\tH\x03R\vtriggeredBy\x88\x01\x01\x12B\n" +
	"\fcompleted_at\x18\x06 \x01(\v2\x1a.google.protobuf.TimestampH\x04R\vcompletedAt\x88\x01\x01B\r\n" +
	"\v_project_idB\t\n" +
	"\a_statusB\f\n" +
	"\n" +
	"_build_logB\x0f\n" +
	"\r_triggered_byB\x0f\n" +
	"\r_completed_at\"$\n" +
	"\x12DeleteBuildRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\";\n" +
	"\x11ListBuildsRequest\x12\x12\n" +
	"\x04page\x18\x01 \x01(\x05R\x04page\x12\x12\n" +
	"\x04size\x18\x02 \x01(\x05R\x04size\"o\n" +
	"\x12ListBuildsResponse\x12'\n" +
	"\x05items\x18\x01 \x03(\v2\x11.rh_trex.v1.BuildR\x05items\x120\n" +
	"\bmetadata\x18\x02 \x01(\v2\x14.rh_trex.v1.ListMetaR\bmetadata\"\x15\n" +
	"\x13DeleteBuildResponse\"\x14\n" +
	"\x12WatchBuildsRequest\"\x86\x01\n" +
	"\x0fBuildWatchEvent\x12)\n" +
	"\x04type\x18\x01 \x01(\x0e2\x15.rh_trex.v1.EventTypeR\x04type\x12'\n" +
	"\x05build\x18\x02 \x01(\v2\x11.rh_trex.v1.BuildR\x05build\x12\x1f\n" +
	"\vresource_id\x18\x03 \x01(\tR\n" +
	"resourceId2\xb9\x03\n" +
	"\fBuildService\x12:\n" +
	"\bGetBuild\x12\x1b.rh_trex.v1.GetBuildRequest\x1a\x11.rh_trex.v1.Build\x12@\n" +
	"\vCreateBuild\x12\x1e.rh_trex.v1.CreateBuildRequest\x1a\x11.rh_trex.v1.Build\x12@\n" +
	"\vUpdateBuild\x12\x1e.rh_trex.v1.UpdateBuildRequest\x1a\x11.rh_trex.v1.Build\x12N\n" +
	"\vDeleteBuild\x12\x1e.rh_trex.v1.DeleteBuildRequest\x1a\x1f.rh_trex.v1.DeleteBuildResponse\x12K\n" +
	"\n" +
	"ListBuilds\x12\x1d.rh_trex.v1.ListBuildsRequest\x1a\x1e.rh_trex.v1.ListBuildsResponse\x12L\n" +
	"\vWatchBuilds\x12\x1e.rh_trex.v1.WatchBuildsRequest\x1a\x1b.rh_trex.v1.BuildWatchEvent0\x01BKZIgithub.com/openshift-online/rh-trex-ai/pkg/api/grpc/rh_trex/v1;rh_trex_v1b\x06proto3"

var (
	file_rh_trex_v1_builds_proto_rawDescOnce sync.Once
	file_rh_trex_v1_builds_proto_rawDescData []byte
)

func file_rh_trex_v1_builds_proto_rawDescGZIP() []byte {
	file_rh_trex_v1_builds_proto_rawDescOnce.Do(func() {
		file_rh_trex_v1_builds_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_rh_trex_v1_builds_proto_rawDesc), len(file_rh_trex_v1_builds_proto_rawDesc)))
	})
	return file_rh_trex_v1_builds_proto_rawDescData
}

var file_rh_trex_v1_builds_proto_msgTypes = make([]protoimpl.MessageInfo, 10)
var file_rh_trex_v1_builds_proto_goTypes = []any{
	(*Build)(nil),                 // 0: rh_trex.v1.Build
	(*CreateBuildRequest)(nil),    // 1: rh_trex.v1.CreateBuildRequest
	(*GetBuildRequest)(nil),       // 2: rh_trex.v1.GetBuildRequest
	(*UpdateBuildRequest)(nil),    // 3: rh_trex.v1.UpdateBuildRequest
	(*DeleteBuildRequest)(nil),    // 4: rh_trex.v1.DeleteBuildRequest
	(*ListBuildsRequest)(nil),     // 5: rh_trex.v1.ListBuildsRequest
	(*ListBuildsResponse)(nil),    // 6: rh_trex.v1.ListBuildsResponse
	(*DeleteBuildResponse)(nil),   // 7: rh_trex.v1.DeleteBuildResponse
	(*WatchBuildsRequest)(nil),    // 8: rh_trex.v1.WatchBuildsRequest
	(*BuildWatchEvent)(nil),       // 9: rh_trex.v1.BuildWatchEvent
	(*ObjectReference)(nil),       // 10: rh_trex.v1.ObjectReference
	(*timestamppb.Timestamp)(nil), // 11: google.protobuf.Timestamp
	(*ListMeta)(nil),              // 12: rh_trex.v1.ListMeta
	(EventType)(0),                // 13: rh_trex.v1.EventType
}
var file_rh_trex_v1_builds_proto_depIdxs = []int32{
	10, // 0: rh_trex.v1.Build.metadata:type_name -> rh_trex.v1.ObjectReference
	11, // 1: rh_trex.v1.Build.completed_at:type_name -> google.protobuf.Timestamp
	11, // 2: rh_trex.v1.CreateBuildRequest.completed_at:type_name -> google.protobuf.Timestamp
	11, // 3: rh_trex.v1.UpdateBuildRequest.completed_at:type_name -> google.protobuf.Timestamp
	0,  // 4: rh_trex.v1.ListBuildsResponse.items:type_name -> rh_trex.v1.Build
	12, // 5: rh_trex.v1.ListBuildsResponse.metadata:type_name -> rh_trex.v1.ListMeta
	13, // 6: rh_trex.v1.BuildWatchEvent.type:type_name -> rh_trex.v1.EventType
	0,  // 7: rh_trex.v1.BuildWatchEvent.build:type_name -> rh_trex.v1.Build
	2,  // 8: rh_trex.v1.BuildService.GetBuild:input_type -> rh_trex.v1.GetBuildRequest
	1,  // 9: rh_trex.v1.BuildService.CreateBuild:input_type -> rh_trex.v1.CreateBuildRequest
	3,  // 10: rh_trex.v1.BuildService.UpdateBuild:input_type -> rh_trex.v1.UpdateBuildRequest
	4,  // 11: rh_trex.v1.BuildService.DeleteBuild:input_type -> rh_trex.v1.DeleteBuildRequest
	5,  // 12: rh_trex.v1.BuildService.ListBuilds:input_type -> rh_trex.v1.ListBuildsRequest
	8,  // 13: rh_trex.v1.BuildService.WatchBuilds:input_type -> rh_trex.v1.WatchBuildsRequest
	0,  // 14: rh_trex.v1.BuildService.GetBuild:output_type -> rh_trex.v1.Build
	0,  // 15: rh_trex.v1.BuildService.CreateBuild:output_type -> rh_trex.v1.Build
	0,  // 16: rh_trex.v1.BuildService.UpdateBuild:output_type -> rh_trex.v1.Build
	7,  // 17: rh_trex.v1.BuildService.DeleteBuild:output_type -> rh_trex.v1.DeleteBuildResponse
	6,  // 18: rh_trex.v1.BuildService.ListBuilds:output_type -> rh_trex.v1.ListBuildsResponse
	9,  // 19: rh_trex.v1.BuildService.WatchBuilds:output_type -> rh_trex.v1.BuildWatchEvent
	14, // [14:20] is the sub-list for method output_type
	8,  // [8:14] is the sub-list for method input_type
	8,  // [8:8] is the sub-list for extension type_name
	8,  // [8:8] is the sub-list for extension extendee
	0,  // [0:8] is the sub-list for field type_name
}

func init() { file_rh_trex_v1_builds_proto_init() }
func file_rh_trex_v1_builds_proto_init() {
	if File_rh_trex_v1_builds_proto != nil {
		return
	}
	file_rh_trex_v1_common_proto_init()
	file_rh_trex_v1_builds_proto_msgTypes[0].OneofWrappers = []any{}
	file_rh_trex_v1_builds_proto_msgTypes[1].OneofWrappers = []any{}
	file_rh_trex_v1_builds_proto_msgTypes[3].OneofWrappers = []any{}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_rh_trex_v1_builds_proto_rawDesc), len(file_rh_trex_v1_builds_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   10,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_rh_trex_v1_builds_proto_goTypes,
		DependencyIndexes: file_rh_trex_v1_builds_proto_depIdxs,
		MessageInfos:      file_rh_trex_v1_builds_proto_msgTypes,
	}.Build()
	File_rh_trex_v1_builds_proto = out.File
	file_rh_trex_v1_builds_proto_goTypes = nil
	file_rh_trex_v1_builds_proto_depIdxs = nil
}
