// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.2
// - protoc             (unknown)
// source: rh_trex/v1/entity_definitions.proto

package rh_trex_v1

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	EntityDefinitionService_GetEntityDefinition_FullMethodName    = "/rh_trex.v1.EntityDefinitionService/GetEntityDefinition"
	EntityDefinitionService_CreateEntityDefinition_FullMethodName = "/rh_trex.v1.EntityDefinitionService/CreateEntityDefinition"
	EntityDefinitionService_UpdateEntityDefinition_FullMethodName = "/rh_trex.v1.EntityDefinitionService/UpdateEntityDefinition"
	EntityDefinitionService_DeleteEntityDefinition_FullMethodName = "/rh_trex.v1.EntityDefinitionService/DeleteEntityDefinition"
	EntityDefinitionService_ListEntityDefinitions_FullMethodName  = "/rh_trex.v1.EntityDefinitionService/ListEntityDefinitions"
	EntityDefinitionService_WatchEntityDefinitions_FullMethodName = "/rh_trex.v1.EntityDefinitionService/WatchEntityDefinitions"
)

// EntityDefinitionServiceClient is the client API for EntityDefinitionService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type EntityDefinitionServiceClient interface {
	GetEntityDefinition(ctx context.Context, in *GetEntityDefinitionRequest, opts ...grpc.CallOption) (*EntityDefinition, error)
	CreateEntityDefinition(ctx context.Context, in *CreateEntityDefinitionRequest, opts ...grpc.CallOption) (*EntityDefinition, error)
	UpdateEntityDefinition(ctx context.Context, in *UpdateEntityDefinitionRequest, opts ...grpc.CallOption) (*EntityDefinition, error)
	DeleteEntityDefinition(ctx context.Context, in *DeleteEntityDefinitionRequest, opts ...grpc.CallOption) (*DeleteEntityDefinitionResponse, error)
	ListEntityDefinitions(ctx context.Context, in *ListEntityDefinitionsRequest, opts ...grpc.CallOption) (*ListEntityDefinitionsResponse, error)
	WatchEntityDefinitions(ctx context.Context, in *WatchEntityDefinitionsRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[EntityDefinitionWatchEvent], error)
}

type entityDefinitionServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewEntityDefinitionServiceClient(cc grpc.ClientConnInterface) EntityDefinitionServiceClient {
	return &entityDefinitionServiceClient{cc}
}

func (c *entityDefinitionServiceClient) GetEntityDefinition(ctx context.Context, in *GetEntityDefinitionRequest, opts ...grpc.CallOption) (*EntityDefinition, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(EntityDefinition)
	err := c.cc.Invoke(ctx, EntityDefinitionService_GetEntityDefinition_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *entityDefinitionServiceClient) CreateEntityDefinition(ctx context.Context, in *CreateEntityDefinitionRequest, opts ...grpc.CallOption) (*EntityDefinition, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(EntityDefinition)
	err := c.cc.Invoke(ctx, EntityDefinitionService_CreateEntityDefinition_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *entityDefinitionServiceClient) UpdateEntityDefinition(ctx context.Context, in *UpdateEntityDefinitionRequest, opts ...grpc.CallOption) (*EntityDefinition, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(EntityDefinition)
	err := c.cc.Invoke(ctx, EntityDefinitionService_UpdateEntityDefinition_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *entityDefinitionServiceClient) DeleteEntityDefinition(ctx context.Context, in *DeleteEntityDefinitionRequest, opts ...grpc.CallOption) (*DeleteEntityDefinitionResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(DeleteEntityDefinitionResponse)
	err := c.cc.Invoke(ctx, EntityDefinitionService_DeleteEntityDefinition_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *entityDefinitionServiceClient) ListEntityDefinitions(ctx context.Context, in *ListEntityDefinitionsRequest, opts ...grpc.CallOption) (*ListEntityDefinitionsResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ListEntityDefinitionsResponse)
	err := c.cc.Invoke(ctx, EntityDefinitionService_ListEntityDefinitions_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *entityDefinitionServiceClient) WatchEntityDefinitions(ctx context.Context, in *WatchEntityDefinitionsRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[EntityDefinitionWatchEvent], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &EntityDefinitionService_ServiceDesc.Streams[0], EntityDefinitionService_WatchEntityDefinitions_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[WatchEntityDefinitionsRequest, EntityDefinitionWatchEvent]{ClientStream: stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type EntityDefinitionService_WatchEntityDefinitionsClient = grpc.ServerStreamingClient[EntityDefinitionWatchEvent]

// EntityDefinitionServiceServer is the server API for EntityDefinitionService service.
// All implementations must embed UnimplementedEntityDefinitionServiceServer
// for forward compatibility.
type EntityDefinitionServiceServer interface {
	GetEntityDefinition(context.Context, *GetEntityDefinitionRequest) (*EntityDefinition, error)
	CreateEntityDefinition(context.Context, *CreateEntityDefinitionRequest) (*EntityDefinition, error)
	UpdateEntityDefinition(context.Context, *UpdateEntityDefinitionRequest) (*EntityDefinition, error)
	DeleteEntityDefinition(context.Context, *DeleteEntityDefinitionRequest) (*DeleteEntityDefinitionResponse, error)
	ListEntityDefinitions(context.Context, *ListEntityDefinitionsRequest) (*ListEntityDefinitionsResponse, error)
	WatchEntityDefinitions(*WatchEntityDefinitionsRequest, grpc.ServerStreamingServer[EntityDefinitionWatchEvent]) error
	mustEmbedUnimplementedEntityDefinitionServiceServer()
}

// UnimplementedEntityDefinitionServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedEntityDefinitionServiceServer struct{}

func (UnimplementedEntityDefinitionServiceServer) GetEntityDefinition(context.Context, *GetEntityDefinitionRequest) (*EntityDefinition, error) {
	return nil, status.Error(codes.Unimplemented, "method GetEntityDefinition not implemented")
}
func (UnimplementedEntityDefinitionServiceServer) CreateEntityDefinition(context.Context, *CreateEntityDefinitionRequest) (*EntityDefinition, error) {
	return nil, status.Error(codes.Unimplemented, "method CreateEntityDefinition not implemented")
}
func (UnimplementedEntityDefinitionServiceServer) UpdateEntityDefinition(context.Context, *UpdateEntityDefinitionRequest) (*EntityDefinition, error) {
	return nil, status.Error(codes.Unimplemented, "method UpdateEntityDefinition not implemented")
}
func (UnimplementedEntityDefinitionServiceServer) DeleteEntityDefinition(context.Context, *DeleteEntityDefinitionRequest) (*DeleteEntityDefinitionResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method DeleteEntityDefinition not implemented")
}
func (UnimplementedEntityDefinitionServiceServer) ListEntityDefinitions(context.Context, *ListEntityDefinitionsRequest) (*ListEntityDefinitionsResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ListEntityDefinitions not implemented")
}
func (UnimplementedEntityDefinitionServiceServer) WatchEntityDefinitions(*WatchEntityDefinitionsRequest, grpc.ServerStreamingServer[EntityDefinitionWatchEvent]) error {
	return status.Error(codes.Unimplemented, "method WatchEntityDefinitions not implemented")
}
func (UnimplementedEntityDefinitionServiceServer) mustEmbedUnimplementedEntityDefinitionServiceServer() {
}
func (UnimplementedEntityDefinitionServiceServer) testEmbeddedByValue() {}

// UnsafeEntityDefinitionServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to EntityDefinitionServiceServer will
// result in compilation errors.
type UnsafeEntityDefinitionServiceServer interface {
	mustEmbedUnimplementedEntityDefinitionServiceServer()
}

func RegisterEntityDefinitionServiceServer(s grpc.ServiceRegistrar, srv EntityDefinitionServiceServer) {
	// If the following call panics, it indicates UnimplementedEntityDefinitionServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&EntityDefinitionService_ServiceDesc, srv)
}

func _EntityDefinitionService_GetEntityDefinition_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetEntityDefinitionRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(EntityDefinitionServiceServer).GetEntityDefinition(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: EntityDefinitionService_GetEntityDefinition_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(EntityDefinitionServiceServer).GetEntityDefinition(ctx, req.(*GetEntityDefinitionRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _EntityDefinitionService_CreateEntityDefinition_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateEntityDefinitionRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(EntityDefinitionServiceServer).CreateEntityDefinition(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: EntityDefinitionService_CreateEntityDefinition_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(EntityDefinitionServiceServer).CreateEntityDefinition(ctx, req.(*CreateEntityDefinitionRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _EntityDefinitionService_UpdateEntityDefinition_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UpdateEntityDefinitionRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(EntityDefinitionServiceServer).UpdateEntityDefinition(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: EntityDefinitionService_UpdateEntityDefinition_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(EntityDefinitionServiceServer).UpdateEntityDefinition(ctx, req.(*UpdateEntityDefinitionRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _EntityDefinitionService_DeleteEntityDefinition_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DeleteEntityDefinitionRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(EntityDefinitionServiceServer).DeleteEntityDefinition(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: EntityDefinitionService_DeleteEntityDefinition_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(EntityDefinitionServiceServer).DeleteEntityDefinition(ctx, req.(*DeleteEntityDefinitionRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _EntityDefinitionService_ListEntityDefinitions_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListEntityDefinitionsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(EntityDefinitionServiceServer).ListEntityDefinitions(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: EntityDefinitionService_ListEntityDefinitions_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(EntityDefinitionServiceServer).ListEntityDefinitions(ctx, req.(*ListEntityDefinitionsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _EntityDefinitionService_WatchEntityDefinitions_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(WatchEntityDefinitionsRequest)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(EntityDefinitionServiceServer).WatchEntityDefinitions(m, &grpc.GenericServerStream[WatchEntityDefinitionsRequest, EntityDefinitionWatchEvent]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type EntityDefinitionService_WatchEntityDefinitionsServer = grpc.ServerStreamingServer[EntityDefinitionWatchEvent]

// EntityDefinitionService_ServiceDesc is the grpc.ServiceDesc for EntityDefinitionService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var EntityDefinitionService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "rh_trex.v1.EntityDefinitionService",
	HandlerType: (*EntityDefinitionServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetEntityDefinition",
			Handler:    _EntityDefinitionService_GetEntityDefinition_Handler,
		},
		{
			MethodName: "CreateEntityDefinition",
			Handler:    _EntityDefinitionService_CreateEntityDefinition_Handler,
		},
		{
			MethodName: "UpdateEntityDefinition",
			Handler:    _EntityDefinitionService_UpdateEntityDefinition_Handler,
		},
		{
			MethodName: "DeleteEntityDefinition",
			Handler:    _EntityDefinitionService_DeleteEntityDefinition_Handler,
		},
		{
			MethodName: "ListEntityDefinitions",
			Handler:    _EntityDefinitionService_ListEntityDefinitions_Handler,
		},
	},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "WatchEntityDefinitions",
			Handler:       _EntityDefinitionService_WatchEntityDefinitions_Handler,
			ServerStreams: true,
		},
	},
	Metadata: "rh_trex/v1/entity_definitions.proto",
}
