// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        (unknown)
// source: rh_trex/v1/entity_definitions.proto

package rh_trex_v1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type EntityDefinition struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	Metadata       *ObjectReference       `protobuf:"bytes,1,opt,name=metadata,proto3" json:"metadata,omitempty"`
	ProjectId      string                 `protobuf:"bytes,2,opt,name=project_id,json=projectId,proto3" json:"project_id,omitempty"`
	KindName       string                 `protobuf:"bytes,3,opt,name=kind_name,json=kindName,proto3" json:"kind_name,omitempty"`
	PluralOverride *string                `protobuf:"bytes,4,opt,name=plural_override,json=pluralOverride,proto3,oneof" json:"plural_override,omitempty"`
	Description    *string                `protobuf:"bytes,5,opt,name=description,proto3,oneof" json:"description,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *EntityDefinition) Reset() {
	*x = EntityDefinition{}
	mi := &file_rh_trex_v1_entity_definitions_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *EntityDefinition) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EntityDefinition) ProtoMessage() {}

func (x *EntityDefinition) ProtoReflect() protoreflect.Message {
	mi := &file_rh_trex_v1_entity_definitions_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EntityDefinition.ProtoReflect.Descriptor instead.
func (*EntityDefinition) Descriptor() ([]byte, []int) {
	return file_rh_trex_v1_entity_definitions_proto_rawDescGZIP(), []int{0}
}

func (x *EntityDefinition) GetMetadata() *ObjectReference {
	if x != nil {
		return x.Metadata
	}
	return nil
}

func (x *EntityDefinition) GetProjectId() string {
	if x != nil {
		return x.ProjectId
	}
	return ""
}

func (x *EntityDefinition) GetKindName() string {
	if x != nil {
		return x.KindName
	}
	return ""
}

func (x *EntityDefinition) GetPluralOverride() string {
	if x != nil && x.PluralOverride != nil {
		return *x.PluralOverride
	}
	return ""
}

func (x *EntityDefinition) GetDescription() string {
	if x != nil && x.Description != nil {
		return *x.Description
	}
	return ""
}

type CreateEntityDefinitionRequest struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	ProjectId      string                 `protobuf:"bytes,1,opt,name=project_id,json=projectId,proto3" json:"project_id,omitempty"`
	KindName       string                 `protobuf:"bytes,2,opt,name=kind_name,json=kindName,proto3" json:"kind_name,omitempty"`
	PluralOverride *string                `protobuf:"bytes,3,opt,name=plural_override,json=pluralOverride,proto3,oneof" json:"plural_override,omitempty"`
	Description    *string                `protobuf:"bytes,4,opt,name=description,proto3,oneof" json:"description,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *CreateEntityDefinitionRequest) Reset() {
	*x = CreateEntityDefinitionRequest{}
	mi := &file_rh_trex_v1_entity_definitions_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateEntityDefinitionRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateEntityDefinitionRequest) ProtoMessage() {}

func (x *CreateEntityDefinitionRequest) ProtoReflect() protoreflect.Message {
	mi := &file_rh_trex_v1_entity_definitions_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateEntityDefinitionRequest.ProtoReflect.Descriptor instead.
func (*CreateEntityDefinitionRequest) Descriptor() ([]byte, []int) {
	return file_rh_trex_v1_entity_definitions_proto_rawDescGZIP(), []int{1}
}

func (x *CreateEntityDefinitionRequest) GetProjectId() string {
	if x != nil {
		return x.ProjectId
	}
	return ""
}

func (x *CreateEntityDefinitionRequest) GetKindName() string {
	if x != nil {
		return x.KindName
	}
	return ""
}

func (x *CreateEntityDefinitionRequest) GetPluralOverride() string {
	if x != nil && x.PluralOverride != nil {
		return *x.PluralOverride
	}
	return ""
}

func (x *CreateEntityDefinitionRequest) GetDescription() string {
	if x != nil && x.Description != nil {
		return *x.Description
	}
	return ""
}

type GetEntityDefinitionRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetEntityDefinitionRequest) Reset() {
	*x = GetEntityDefinitionRequest{}
	mi := &file_rh_trex_v1_entity_definitions_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetEntityDefinitionRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetEntityDefinitionRequest) ProtoMessage() {}

func (x *GetEntityDefinitionRequest) ProtoReflect() protoreflect.Message {
	mi := &file_rh_trex_v1_entity_definitions_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetEntityDefinitionRequest.ProtoReflect.Descriptor instead.
func (*GetEntityDefinitionRequest) Descriptor() ([]byte, []int) {
	return file_rh_trex_v1_entity_definitions_proto_rawDescGZIP(), []int{2}
}

func (x *GetEntityDefinitionRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

type UpdateEntityDefinitionRequest struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	Id             string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	ProjectId      *string                `protobuf:"bytes,2,opt,name=project_id,json=projectId,proto3,oneof" json:"project_id,omitempty"`
	KindName       *string                `protobuf:"bytes,3,opt,name=kind_name,json=kindName,proto3,oneof" json:"kind_name,omitempty"`
	PluralOverride *string                `protobuf:"bytes,4,opt,name=plural_override,json=pluralOverride,proto3,oneof" json:"plural_override,omitempty"`
	Description    *string                `protobuf:"bytes,5,opt,name=description,proto3,oneof" json:"description,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *UpdateEntityDefinitionRequest) Reset() {
	*x = UpdateEntityDefinitionRequest{}
	mi := &file_rh_trex_v1_entity_definitions_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateEntityDefinitionRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateEntityDefinitionRequest) ProtoMessage() {}

func (x *UpdateEntityDefinitionRequest) ProtoReflect() protoreflect.Message {
	mi := &file_rh_trex_v1_entity_definitions_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateEntityDefinitionRequest.ProtoReflect.Descriptor instead.
func (*UpdateEntityDefinitionRequest) Descriptor() ([]byte, []int) {
	return file_rh_trex_v1_entity_definitions_proto_rawDescGZIP(), []int{3}
}

func (x *UpdateEntityDefinitionRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *UpdateEntityDefinitionRequest) GetProjectId() string {
	if x != nil && x.ProjectId != nil {
		return *x.ProjectId
	}
	return ""
}

func (x *UpdateEntityDefinitionRequest) GetKindName() string {
	if x != nil && x.KindName != nil {
		return *x.KindName
	}
	return ""
}

func (x *UpdateEntityDefinitionRequest) GetPluralOverride() string {
	if x != nil && x.PluralOverride != nil {
		return *x.PluralOverride
	}
	return ""
}

func (x *UpdateEntityDefinitionRequest) GetDescription() string {
	if x != nil && x.Description != nil {
		return *x.Description
	}
	return ""
}

type DeleteEntityDefinitionRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteEntityDefinitionRequest) Reset() {
	*x = DeleteEntityDefinitionRequest{}
	mi := &file_rh_trex_v1_entity_definitions_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteEntityDefinitionRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteEntityDefinitionRequest) ProtoMessage() {}

func (x *DeleteEntityDefinitionRequest) ProtoReflect() protoreflect.Message {
	mi := &file_rh_trex_v1_entity_definitions_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteEntityDefinitionRequest.ProtoReflect.Descriptor instead.
func (*DeleteEntityDefinitionRequest) Descriptor() ([]byte, []int) {
	return file_rh_trex_v1_entity_definitions_proto_rawDescGZIP(), []int{4}
}

func (x *DeleteEntityDefinitionRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

type ListEntityDefinitionsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Page          int32                  `protobuf:"varint,1,opt,name=page,proto3" json:"page,omitempty"`
	Size          int32                  `protobuf:"varint,2,opt,name=size,proto3" json:"size,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListEntityDefinitionsRequest) Reset() {
	*x = ListEntityDefinitionsRequest{}
	mi := &file_rh_trex_v1_entity_definitions_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListEntityDefinitionsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListEntityDefinitionsRequest) ProtoMessage() {}

func (x *ListEntityDefinitionsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_rh_trex_v1_entity_definitions_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListEntityDefinitionsRequest.ProtoReflect.Descriptor instead.
func (*ListEntityDefinitionsRequest) Descriptor() ([]byte, []int) {
	return file_rh_trex_v1_entity_definitions_proto_rawDescGZIP(), []int{5}
}

func (x *ListEntityDefinitionsRequest) GetPage() int32 {
	if x != nil {
		return x.Page
	}
	return 0
}

func (x *ListEntityDefinitionsRequest) GetSize() int32 {
	if x != nil {
		return x.Size
	}
	return 0
}

type ListEntityDefinitionsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Items         []*EntityDefinition    `protobuf:"bytes,1,rep,name=items,proto3" json:"items,omitempty"`
	Metadata      *ListMeta              `protobuf:"bytes,2,opt,name=metadata,proto3" json:"metadata,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListEntityDefinitionsResponse) Reset() {
	*x = ListEntityDefinitionsResponse{}
	mi := &file_rh_trex_v1_entity_definitions_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListEntityDefinitionsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListEntityDefinitionsResponse) ProtoMessage() {}

func (x *ListEntityDefinitionsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_rh_trex_v1_entity_definitions_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListEntityDefinitionsResponse.ProtoReflect.Descriptor instead.
func (*ListEntityDefinitionsResponse) Descriptor() ([]byte, []int) {
	return file_rh_trex_v1_entity_definitions_proto_rawDescGZIP(), []int{6}
}

func (x *ListEntityDefinitionsResponse) GetItems() []*EntityDefinition {
	if x != nil {
		return x.Items
	}
	return nil
}

func (x *ListEntityDefinitionsResponse) GetMetadata() *ListMeta {
	if x != nil {
		return x.Metadata
	}
	return nil
}

type DeleteEntityDefinitionResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteEntityDefinitionResponse) Reset() {
	*x = DeleteEntityDefinitionResponse{}
	mi := &file_rh_trex_v1_entity_definitions_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteEntityDefinitionResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteEntityDefinitionResponse) ProtoMessage() {}

func (x *DeleteEntityDefinitionResponse) ProtoReflect() protoreflect.Message {
	mi := &file_rh_trex_v1_entity_definitions_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteEntityDefinitionResponse.ProtoReflect.Descriptor instead.
func (*DeleteEntityDefinitionResponse) Descriptor() ([]byte, []int) {
	return file_rh_trex_v1_entity_definitions_proto_rawDescGZIP(), []int{7}
}

type WatchEntityDefinitionsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *WatchEntityDefinitionsRequest) Reset() {
	*x = WatchEntityDefinitionsRequest{}
	mi := &file_rh_trex_v1_entity_definitions_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *WatchEntityDefinitionsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*WatchEntityDefinitionsRequest) ProtoMessage() {}

func (x *WatchEntityDefinitionsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_rh_trex_v1_entity_definitions_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use WatchEntityDefinitionsRequest.ProtoReflect.Descriptor instead.
func (*WatchEntityDefinitionsRequest) Descriptor() ([]byte, []int) {
	return file_rh_trex_v1_entity_definitions_proto_rawDescGZIP(), []int{8}
}

type EntityDefinitionWatchEvent struct {
	state            protoimpl.MessageState `protogen:"open.v1"`
	Type             EventType              `protobuf:"varint,1,opt,name=type,proto3,enum=rh_trex.v1.EventType" json:"type,omitempty"`
	EntityDefinition *EntityDefinition      `protobuf:"bytes,2,opt,name=entityDefinition,proto3" json:"entityDefinition,omitempty"`
	ResourceId       string                 `protobuf:"bytes,3,opt,name=resource_id,json=resourceId,proto3" json:"resource_id,omitempty"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *EntityDefinitionWatchEvent) Reset() {
	*x = EntityDefinitionWatchEvent{}
	mi := &file_rh_trex_v1_entity_definitions_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *EntityDefinitionWatchEvent) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EntityDefinitionWatchEvent) ProtoMessage() {}

func (x *EntityDefinitionWatchEvent) ProtoReflect() protoreflect.Message {
	mi := &file_rh_trex_v1_entity_definitions_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EntityDefinitionWatchEvent.ProtoReflect.Descriptor instead.
func (*EntityDefinitionWatchEvent) Descriptor() ([]byte, []int) {
	return file_rh_trex_v1_entity_definitions_proto_rawDescGZIP(), []int{9}
}

func (x *EntityDefinitionWatchEvent) GetType() EventType {
	if x != nil {
		return x.Type
	}
	return EventType_EVENT_TYPE_UNSPECIFIED
}

func (x *EntityDefinitionWatchEvent) GetEntityDefinition() *EntityDefinition {
	if x != nil {
		return x.EntityDefinition
	}
	return nil
}

func (x *EntityDefinitionWatchEvent) GetResourceId() string {
	if x != nil {
		return x.ResourceId
	}
	return ""
}

var File_rh_trex_v1_entity_definitions_proto protoreflect.FileDescriptor

const file_rh_trex_v1_entity_definitions_proto_rawDesc = "" +
	"\n" +
	"#rh_trex/v1/entity_definitions.proto\x12\n" +
	"rh_trex.v1\x1a\x17rh_trex/v1/common.proto\"\x80\x02\n" +
	"\x10EntityDefinition\x127\n" +
	"\bmetadata\x18\x01 \x01(\v2\x1b.rh_trex.v1.ObjectReferenceR\bmetadata\x12\x1d\n" +
	"\n" +
	"project_id\x18\x02 \x01(\tR\tprojectId\x12\x1b\n" +
	"\tkind_name\x18\x03 \x01(\tR\bkindName\x12,\n" +
	"\x0fplural_override\x18\x04 \x01(\tH\x00R\x0epluralOverride\x88\x01\x01\x12%\n" +
	"\vdescription\x18\x05 \x01(\tH\x01R\vdescription\x88\x01\x01B\x12\n" +
	"\x10_plural_overrideB\x0e\n" +
	"\f_description\"\xd4\x01\n" +
	"\x1dCreateEntityDefinitionRequest\x12\x1d\n" +
	"\n" +
	"project_id\x18\x01 \x01(\tR\tprojectId\x12\x1b\n" +
	"\tkind_name\x18\x02 \x01(\tR\bkindName\x12,\n" +
	"\x0fplural_override\x18\x03 \x01(\tH\x00R\x0epluralOverride\x88\x01\x01\x12%\n" +
	"\vdescription\x18\x04 \x01(\tH\x01R\vdescription\x88\x01\x01B\x12\n" +
	"\x10_plural_overrideB\x0e\n" +
	"\f_description\",\n" +
	"\x1aGetEntityDefinitionRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\"\x8b\x02\n" +
	"\x1dUpdateEntityDefinitionRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\"\n" +
	"\n" +
	"project_id\x18\x02 \x01(\tH\x00R\tprojectId\x88\x01\x01\x12 \n" +
	"\tkind_name\x18\x03 \x01(\tH\x01R\bkindName\x88\x01\x01\x12,\n" +
	"\x0fplural_override\x18\x04 \x01(\tH\x02R\x0epluralOverride\x88\x01\x01\x12%\n" +
	"\vdescription\x18\x05 \x01(\tH\x03R\vdescription\x88\x01\x01B\r\n" +
	"\v_project_idB\f\n" +
	"\n" +
	"_kind_nameB\x12\n" +
	"\x10_plural_overrideB\x0e\n" +
	"\f_description\"/\n" +
	"\x1dDeleteEntityDefinitionRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\"F\n" +
	"\x1cListEntityDefinitionsRequest\x12\x12\n" +
	"\x04page\x18\x01 \x01(\x05R\x04page\x12\x12\n" +
	"\x04size\x18\x02 \x01(\x05R\x04size\"\x85\x01\n" +
	"\x1dListEntityDefinitionsResponse\x122\n" +
	"\x05items\x18\x01 \x03(\v2\x1c.rh_trex.v1.EntityDefinitionR\x05items\x120\n" +
	"\bmetadata\x18\x02 \x01(\v2\x14.rh_trex.v1.ListMetaR\bmetadata\" \n" +
	"\x1eDeleteEntityDefinitionResponse\"\x1f\n" +
	"\x1dWatchEntityDefinitionsRequest\"\xb2\x01\n" +
	"\x1aEntityDefinitionWatchEvent\x12)\n" +
	"\x04type\x18\x01 \x01(\x0e2\x15.rh_trex.v1.EventTypeR\x04type\x12H\n" +
	"\x10entityDefinition\x18\x02 \x01(\v2\x1c.rh_trex.v1.EntityDefinitionR\x10entityDefinition\x12\x1f\n" +
	"\vresource_id\x18\x03 \x01(\tR\n" +
	"resourceId2\x8a\x05\n" +
	"\x17EntityDefinitionService\x12[\n" +
	"\x13GetEntityDefinition\x12&.rh_trex.v1.GetEntityDefinitionRequest\x1a\x1c.rh_trex.v1.EntityDefinition\x12a\n" +
	"\x16CreateEntityDefinition\x12).rh_trex.v1.CreateEntityDefinitionRequest\x1a\x1c.rh_trex.v1.EntityDefinition\x12a\n" +
	"\x16UpdateEntityDefinition\x12).rh_trex.v1.UpdateEntityDefinitionRequest\x1a\x1c.rh_trex.v1.EntityDefinition\x12o\n" +
	"\x16DeleteEntityDefinition\x12).rh_trex.v1.DeleteEntityDefinitionRequest\x1a*.rh_trex.v1.DeleteEntityDefinitionResponse\x12l\n" +
	"\x15ListEntityDefinitions\x12(.rh_trex.v1.ListEntityDefinitionsRequest\x1a).rh_trex.v1.ListEntityDefinitionsResponse\x12m\n" +
	"\x16WatchEntityDefinitions\x12).rh_trex.v1.WatchEntityDefinitionsRequest\x1a&.rh_trex.v1.EntityDefinitionWatchEvent0\x01BKZIgithub.com/openshift-online/rh-trex-ai/pkg/api/grpc/rh_trex/v1;rh_trex_v1b\x06proto3"

var (
	file_rh_trex_v1_entity_definitions_proto_rawDescOnce sync.Once
	file_rh_trex_v1_entity_definitions_proto_rawDescData []byte
)

func file_rh_trex_v1_entity_definitions_proto_rawDescGZIP() []byte {
	file_rh_trex_v1_entity_definitions_proto_rawDescOnce.Do(func() {
		file_rh_trex_v1_entity_definitions_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_rh_trex_v1_entity_definitions_proto_rawDesc), len(file_rh_trex_v1_entity_definitions_proto_rawDesc)))
	})
	return file_rh_trex_v1_entity_definitions_proto_rawDescData
}

var file_rh_trex_v1_entity_definitions_proto_msgTypes = make([]protoimpl.MessageInfo, 10)
var file_rh_trex_v1_entity_definitions_proto_goTypes = []any{
	(*EntityDefinition)(nil),               // 0: rh_trex.v1.EntityDefinition
	(*CreateEntityDefinitionRequest)(nil),  // 1: rh_trex.v1.CreateEntityDefinitionRequest
	(*GetEntityDefinitionRequest)(nil),     // 2: rh_trex.v1.GetEntityDefinitionRequest
	(*UpdateEntityDefinitionRequest)(nil),  // 3: rh_trex.v1.UpdateEntityDefinitionRequest
	(*DeleteEntityDefinitionRequest)(nil),  // 4: rh_trex.v1.DeleteEntityDefinitionRequest
	(*ListEntityDefinitionsRequest)(nil),   // 5: rh_trex.v1.ListEntityDefinitionsRequest
	(*ListEntityDefinitionsResponse)(nil),  // 6: rh_trex.v1.ListEntityDefinitionsResponse
	(*DeleteEntityDefinitionResponse)(nil), // 7: rh_trex.v1.DeleteEntityDefinitionResponse
	(*WatchEntityDefinitionsRequest)(nil),  // 8: rh_trex.v1.WatchEntityDefinitionsRequest
	(*EntityDefinitionWatchEvent)(nil),     // 9: rh_trex.v1.EntityDefinitionWatchEvent
	(*ObjectReference)(nil),                // 10: rh_trex.v1.ObjectReference
	(*ListMeta)(nil),                       // 11: rh_trex.v1.ListMeta
	(EventType)(0),                         // 12: rh_trex.v1.EventType
}
var file_rh_trex_v1_entity_definitions_proto_depIdxs = []int32{
	10, // 0: rh_trex.v1.EntityDefinition.metadata:type_name -> rh_trex.v1.ObjectReference
	0,  // 1: rh_trex.v1.ListEntityDefinitionsResponse.items:type_name -> rh_trex.v1.EntityDefinition
	11, // 2: rh_trex.v1.ListEntityDefinitionsResponse.metadata:type_name -> rh_trex.v1.ListMeta
	12, // 3: rh_trex.v1.EntityDefinitionWatchEvent.type:type_name -> rh_trex.v1.EventType
	0,  // 4: rh_trex.v1.EntityDefinitionWatchEvent.entityDefinition:type_name -> rh_trex.v1.EntityDefinition
	2,  // 5: rh_trex.v1.EntityDefinitionService.GetEntityDefinition:input_type -> rh_trex.v1.GetEntityDefinitionRequest
	1,  // 6: rh_trex.v1.EntityDefinitionService.CreateEntityDefinition:input_type -> rh_trex.v1.CreateEntityDefinitionRequest
	3,  // 7: rh_trex.v1.EntityDefinitionService.UpdateEntityDefinition:input_type -> rh_trex.v1.UpdateEntityDefinitionRequest
	4,  // 8: rh_trex.v1.EntityDefinitionService.DeleteEntityDefinition:input_type -> rh_trex.v1.DeleteEntityDefinitionRequest
	5,  // 9: rh_trex.v1.EntityDefinitionService.ListEntityDefinitions:input_type -> rh_trex.v1.ListEntityDefinitionsRequest
	8,  // 10: rh_trex.v1.EntityDefinitionService.WatchEntityDefinitions:input_type -> rh_trex.v1.WatchEntityDefinitionsRequest
	0,  // 11: rh_trex.v1.EntityDefinitionService.GetEntityDefinition:output_type -> rh_trex.v1.EntityDefinition
	0,  // 12: rh_trex.v1.EntityDefinitionService.CreateEntityDefinition:output_type -> rh_trex.v1.EntityDefinition
	0,  // 13: rh_trex.v1.EntityDefinitionService.UpdateEntityDefinition:output_type -> rh_trex.v1.EntityDefinition
	7,  // 14: rh_trex.v1.EntityDefinitionService.DeleteEntityDefinition:output_type -> rh_trex.v1.DeleteEntityDefinitionResponse
	6,  // 15: rh_trex.v1.EntityDefinitionService.ListEntityDefinitions:output_type -> rh_trex.v1.ListEntityDefinitionsResponse
	9,  // 16: rh_trex.v1.EntityDefinitionService.WatchEntityDefinitions:output_type -> rh_trex.v1.EntityDefinitionWatchEvent
	11, // [11:17] is the sub-list for method output_type
	5,  // [5:11] is the sub-list for method input_type
	5,  // [5:5] is the sub-list for extension type_name
	5,  // [5:5] is the sub-list for extension extendee
	0,  // [0:5] is the sub-list for field type_name
}

func init() { file_rh_trex_v1_entity_definitions_proto_init() }
func file_rh_trex_v1_entity_definitions_proto_init() {
	if File_rh_trex_v1_entity_definitions_proto != nil {
		return
	}
	file_rh_trex_v1_common_proto_init()
	file_rh_trex_v1_entity_definitions_proto_msgTypes[0].OneofWrappers = []any{}
	file_rh_trex_v1_entity_definitions_proto_msgTypes[1].OneofWrappers = []any{}
	file_rh_trex_v1_entity_definitions_proto_msgTypes[3].OneofWrappers = []any{}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_rh_trex_v1_entity_definitions_proto_rawDesc), len(file_rh_trex_v1_entity_definitions_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   10,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_rh_trex_v1_entity_definitions_proto_goTypes,
		DependencyIndexes: file_rh_trex_v1_entity_definitions_proto_depIdxs,
		MessageInfos:      file_rh_trex_v1_entity_definitions_proto_msgTypes,
	}.Build()
	File_rh_trex_v1_entity_definitions_proto = out.File
	file_rh_trex_v1_entity_definitions_proto_goTypes = nil
	file_rh_trex_v1_entity_definitions_proto_depIdxs = nil
}
