// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        (unknown)
// source: rh_trex/v1/field_definitions.proto

package rh_trex_v1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type FieldDefinition struct {
	state              protoimpl.MessageState `protogen:"open.v1"`
	Metadata           *ObjectReference       `protobuf:"bytes,1,opt,name=metadata,proto3" json:"metadata,omitempty"`
	EntityDefinitionId string                 `protobuf:"bytes,2,opt,name=entity_definition_id,json=entityDefinitionId,proto3" json:"entity_definition_id,omitempty"`
	FieldName          string                 `protobuf:"bytes,3,opt,name=field_name,json=fieldName,proto3" json:"field_name,omitempty"`
	FieldType          string                 `protobuf:"bytes,4,opt,name=field_type,json=fieldType,proto3" json:"field_type,omitempty"`
	IsRequired         *bool                  `protobuf:"varint,5,opt,name=is_required,json=isRequired,proto3,oneof" json:"is_required,omitempty"`
	unknownFields      protoimpl.UnknownFields
	sizeCache          protoimpl.SizeCache
}

func (x *FieldDefinition) Reset() {
	*x = FieldDefinition{}
	mi := &file_rh_trex_v1_field_definitions_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FieldDefinition) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FieldDefinition) ProtoMessage() {}

func (x *FieldDefinition) ProtoReflect() protoreflect.Message {
	mi := &file_rh_trex_v1_field_definitions_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FieldDefinition.ProtoReflect.Descriptor instead.
func (*FieldDefinition) Descriptor() ([]byte, []int) {
	return file_rh_trex_v1_field_definitions_proto_rawDescGZIP(), []int{0}
}

func (x *FieldDefinition) GetMetadata() *ObjectReference {
	if x != nil {
		return x.Metadata
	}
	return nil
}

func (x *FieldDefinition) GetEntityDefinitionId() string {
	if x != nil {
		return x.EntityDefinitionId
	}
	return ""
}

func (x *FieldDefinition) GetFieldName() string {
	if x != nil {
		return x.FieldName
	}
	return ""
}

func (x *FieldDefinition) GetFieldType() string {
	if x != nil {
		return x.FieldType
	}
	return ""
}

func (x *FieldDefinition) GetIsRequired() bool {
	if x != nil && x.IsRequired != nil {
		return *x.IsRequired
	}
	return false
}

type CreateFieldDefinitionRequest struct {
	state              protoimpl.MessageState `protogen:"open.v1"`
	EntityDefinitionId string                 `protobuf:"bytes,1,opt,name=entity_definition_id,json=entityDefinitionId,proto3" json:"entity_definition_id,omitempty"`
	FieldName          string                 `protobuf:"bytes,2,opt,name=field_name,json=fieldName,proto3" json:"field_name,omitempty"`
	FieldType          string                 `protobuf:"bytes,3,opt,name=field_type,json=fieldType,proto3" json:"field_type,omitempty"`
	IsRequired         *bool                  `protobuf:"varint,4,opt,name=is_required,json=isRequired,proto3,oneof" json:"is_required,omitempty"`
	unknownFields      protoimpl.UnknownFields
	sizeCache          protoimpl.SizeCache
}

func (x *CreateFieldDefinitionRequest) Reset() {
	*x = CreateFieldDefinitionRequest{}
	mi := &file_rh_trex_v1_field_definitions_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateFieldDefinitionRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateFieldDefinitionRequest) ProtoMessage() {}

func (x *CreateFieldDefinitionRequest) ProtoReflect() protoreflect.Message {
	mi := &file_rh_trex_v1_field_definitions_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateFieldDefinitionRequest.ProtoReflect.Descriptor instead.
func (*CreateFieldDefinitionRequest) Descriptor() ([]byte, []int) {
	return file_rh_trex_v1_field_definitions_proto_rawDescGZIP(), []int{1}
}

func (x *CreateFieldDefinitionRequest) GetEntityDefinitionId() string {
	if x != nil {
		return x.EntityDefinitionId
	}
	return ""
}

func (x *CreateFieldDefinitionRequest) GetFieldName() string {
	if x != nil {
		return x.FieldName
	}
	return ""
}

func (x *CreateFieldDefinitionRequest) GetFieldType() string {
	if x != nil {
		return x.FieldType
	}
	return ""
}

func (x *CreateFieldDefinitionRequest) GetIsRequired() bool {
	if x != nil && x.IsRequired != nil {
		return *x.IsRequired
	}
	return false
}

type GetFieldDefinitionRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetFieldDefinitionRequest) Reset() {
	*x = GetFieldDefinitionRequest{}
	mi := &file_rh_trex_v1_field_definitions_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetFieldDefinitionRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetFieldDefinitionRequest) ProtoMessage() {}

func (x *GetFieldDefinitionRequest) ProtoReflect() protoreflect.Message {
	mi := &file_rh_trex_v1_field_definitions_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetFieldDefinitionRequest.ProtoReflect.Descriptor instead.
func (*GetFieldDefinitionRequest) Descriptor() ([]byte, []int) {
	return file_rh_trex_v1_field_definitions_proto_rawDescGZIP(), []int{2}
}

func (x *GetFieldDefinitionRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

type UpdateFieldDefinitionRequest struct {
	state              protoimpl.MessageState `protogen:"open.v1"`
	Id                 string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	EntityDefinitionId *string                `protobuf:"bytes,2,opt,name=entity_definition_id,json=entityDefinitionId,proto3,oneof" json:"entity_definition_id,omitempty"`
	FieldName          *string                `protobuf:"bytes,3,opt,name=field_name,json=fieldName,proto3,oneof" json:"field_name,omitempty"`
	FieldType          *string                `protobuf:"bytes,4,opt,name=field_type,json=fieldType,proto3,oneof" json:"field_type,omitempty"`
	IsRequired         *bool                  `protobuf:"varint,5,opt,name=is_required,json=isRequired,proto3,oneof" json:"is_required,omitempty"`
	unknownFields      protoimpl.UnknownFields
	sizeCache          protoimpl.SizeCache
}

func (x *UpdateFieldDefinitionRequest) Reset() {
	*x = UpdateFieldDefinitionRequest{}
	mi := &file_rh_trex_v1_field_definitions_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateFieldDefinitionRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateFieldDefinitionRequest) ProtoMessage() {}

func (x *UpdateFieldDefinitionRequest) ProtoReflect() protoreflect.Message {
	mi := &file_rh_trex_v1_field_definitions_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateFieldDefinitionRequest.ProtoReflect.Descriptor instead.
func (*UpdateFieldDefinitionRequest) Descriptor() ([]byte, []int) {
	return file_rh_trex_v1_field_definitions_proto_rawDescGZIP(), []int{3}
}

func (x *UpdateFieldDefinitionRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *UpdateFieldDefinitionRequest) GetEntityDefinitionId() string {
	if x != nil && x.EntityDefinitionId != nil {
		return *x.EntityDefinitionId
	}
	return ""
}

func (x *UpdateFieldDefinitionRequest) GetFieldName() string {
	if x != nil && x.FieldName != nil {
		return *x.FieldName
	}
	return ""
}

func (x *UpdateFieldDefinitionRequest) GetFieldType() string {
	if x != nil && x.FieldType != nil {
		return *x.FieldType
	}
	return ""
}

func (x *UpdateFieldDefinitionRequest) GetIsRequired() bool {
	if x != nil && x.IsRequired != nil {
		return *x.IsRequired
	}
	return false
}

type DeleteFieldDefinitionRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteFieldDefinitionRequest) Reset() {
	*x = DeleteFieldDefinitionRequest{}
	mi := &file_rh_trex_v1_field_definitions_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteFieldDefinitionRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteFieldDefinitionRequest) ProtoMessage() {}

func (x *DeleteFieldDefinitionRequest) ProtoReflect() protoreflect.Message {
	mi := &file_rh_trex_v1_field_definitions_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteFieldDefinitionRequest.ProtoReflect.Descriptor instead.
func (*DeleteFieldDefinitionRequest) Descriptor() ([]byte, []int) {
	return file_rh_trex_v1_field_definitions_proto_rawDescGZIP(), []int{4}
}

func (x *DeleteFieldDefinitionRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

type ListFieldDefinitionsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Page          int32                  `protobuf:"varint,1,opt,name=page,proto3" json:"page,omitempty"`
	Size          int32                  `protobuf:"varint,2,opt,name=size,proto3" json:"size,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListFieldDefinitionsRequest) Reset() {
	*x = ListFieldDefinitionsRequest{}
	mi := &file_rh_trex_v1_field_definitions_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListFieldDefinitionsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListFieldDefinitionsRequest) ProtoMessage() {}

func (x *ListFieldDefinitionsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_rh_trex_v1_field_definitions_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListFieldDefinitionsRequest.ProtoReflect.Descriptor instead.
func (*ListFieldDefinitionsRequest) Descriptor() ([]byte, []int) {
	return file_rh_trex_v1_field_definitions_proto_rawDescGZIP(), []int{5}
}

func (x *ListFieldDefinitionsRequest) GetPage() int32 {
	if x != nil {
		return x.Page
	}
	return 0
}

func (x *ListFieldDefinitionsRequest) GetSize() int32 {
	if x != nil {
		return x.Size
	}
	return 0
}

type ListFieldDefinitionsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Items         []*FieldDefinition     `protobuf:"bytes,1,rep,name=items,proto3" json:"items,omitempty"`
	Metadata      *ListMeta              `protobuf:"bytes,2,opt,name=metadata,proto3" json:"metadata,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListFieldDefinitionsResponse) Reset() {
	*x = ListFieldDefinitionsResponse{}
	mi := &file_rh_trex_v1_field_definitions_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListFieldDefinitionsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListFieldDefinitionsResponse) ProtoMessage() {}

func (x *ListFieldDefinitionsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_rh_trex_v1_field_definitions_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListFieldDefinitionsResponse.ProtoReflect.Descriptor instead.
func (*ListFieldDefinitionsResponse) Descriptor() ([]byte, []int) {
	return file_rh_trex_v1_field_definitions_proto_rawDescGZIP(), []int{6}
}

func (x *ListFieldDefinitionsResponse) GetItems() []*FieldDefinition {
	if x != nil {
		return x.Items
	}
	return nil
}

func (x *ListFieldDefinitionsResponse) GetMetadata() *ListMeta {
	if x != nil {
		return x.Metadata
	}
	return nil
}

type DeleteFieldDefinitionResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteFieldDefinitionResponse) Reset() {
	*x = DeleteFieldDefinitionResponse{}
	mi := &file_rh_trex_v1_field_definitions_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteFieldDefinitionResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteFieldDefinitionResponse) ProtoMessage() {}

func (x *DeleteFieldDefinitionResponse) ProtoReflect() protoreflect.Message {
	mi := &file_rh_trex_v1_field_definitions_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteFieldDefinitionResponse.ProtoReflect.Descriptor instead.
func (*DeleteFieldDefinitionResponse) Descriptor() ([]byte, []int) {
	return file_rh_trex_v1_field_definitions_proto_rawDescGZIP(), []int{7}
}

type WatchFieldDefinitionsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *WatchFieldDefinitionsRequest) Reset() {
	*x = WatchFieldDefinitionsRequest{}
	mi := &file_rh_trex_v1_field_definitions_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *WatchFieldDefinitionsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*WatchFieldDefinitionsRequest) ProtoMessage() {}

func (x *WatchFieldDefinitionsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_rh_trex_v1_field_definitions_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use WatchFieldDefinitionsRequest.ProtoReflect.Descriptor instead.
func (*WatchFieldDefinitionsRequest) Descriptor() ([]byte, []int) {
	return file_rh_trex_v1_field_definitions_proto_rawDescGZIP(), []int{8}
}

type FieldDefinitionWatchEvent struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	Type            EventType              `protobuf:"varint,1,opt,name=type,proto3,enum=rh_trex.v1.EventType" json:"type,omitempty"`
	FieldDefinition *FieldDefinition       `protobuf:"bytes,2,opt,name=fieldDefinition,proto3" json:"fieldDefinition,omitempty"`
	ResourceId      string                 `protobuf:"bytes,3,opt,name=resource_id,json=resourceId,proto3" json:"resource_id,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *FieldDefinitionWatchEvent) Reset() {
	*x = FieldDefinitionWatchEvent{}
	mi := &file_rh_trex_v1_field_definitions_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FieldDefinitionWatchEvent) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FieldDefinitionWatchEvent) ProtoMessage() {}

func (x *FieldDefinitionWatchEvent) ProtoReflect() protoreflect.Message {
	mi := &file_rh_trex_v1_field_definitions_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FieldDefinitionWatchEvent.ProtoReflect.Descriptor instead.
func (*FieldDefinitionWatchEvent) Descriptor() ([]byte, []int) {
	return file_rh_trex_v1_field_definitions_proto_rawDescGZIP(), []int{9}
}

func (x *FieldDefinitionWatchEvent) GetType() EventType {
	if x != nil {
		return x.Type
	}
	return EventType_EVENT_TYPE_UNSPECIFIED
}

func (x *FieldDefinitionWatchEvent) GetFieldDefinition() *FieldDefinition {
	if x != nil {
		return x.FieldDefinition
	}
	return nil
}

func (x *FieldDefinitionWatchEvent) GetResourceId() string {
	if x != nil {
		return x.ResourceId
	}
	return ""
}

var File_rh_trex_v1_field_definitions_proto protoreflect.FileDescriptor

const file_rh_trex_v1_field_definitions_proto_rawDesc = "" +
	"\n" +
	"\"rh_trex/v1/field_definitions.proto\x12\n" +
	"rh_trex.v1\x1a\x17rh_trex/v1/common.proto\"\xf0\x01\n" +
	"\x0fFieldDefinition\x127\n" +
	"\bmetadata\x18\x01 \x01(\v2\x1b.rh_trex.v1.ObjectReferenceR\bmetadata\x120\n" +
	"\x14entity_definition_id\x18\x02 \x01(\tR\x12entityDefinitionId\x12\x1d\n" +
	"\n" +
	"field_name\x18\x03 \x01(\tR\tfieldName\x12\x1d\n" +
	"\n" +
	"field_type\x18\x04 \x01(\tR\tfieldType\x12$\n" +
	"\vis_required\x18\x05 \x01(\bH\x00R\n" +
	"isRequired\x88\x01\x01B\x0e\n" +
	"\f_is_required\"\xc4\x01\n" +
	"\x1cCreateFieldDefinitionRequest\x120\n" +
	"\x14entity_definition_id\x18\x01 \x01(\tR\x12entityDefinitionId\x12\x1d\n" +
	"\n" +
	"field_name\x18\x02 \x01(\tR\tfieldName\x12\x1d\n" +
	"\n" +
	"field_type\x18\x03 \x01(\tR\tfieldType\x12$\n" +
	"\vis_required\x18\x04 \x01(\bH\x00R\n" +
	"isRequired\x88\x01\x01B\x0e\n" +
	"\f_is_required\"+\n" +
	"\x19GetFieldDefinitionRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\"\x9a\x02\n" +
	"\x1cUpdateFieldDefinitionRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x125\n" +
	"\x14entity_definition_id\x18\x02 \x01(\tH\x00R\x12entityDefinitionId\x88\x01\x01\x12\"\n" +
	"\n" +
	"field_name\x18\x03 \x01(\tH\x01R\tfieldName\x88\x01\x01\x12\"\n" +
	"\n" +
	"field_type\x18\x04 \x01(\tH\x02R\tfieldType\x88\x01\x01\x12$\n" +
	"\vis_required\x18\x05 \x01(\bH\x03R\n" +
	"isRequired\x88\x01\x01B\x17\n" +
	"\x15_entity_definition_idB\r\n" +
	"\v_field_nameB\r\n" +
	"\v_field_typeB\x0e\n" +
	"\f_is_required\".\n" +
	"\x1cDeleteFieldDefinitionRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\"E\n" +
	"\x1bListFieldDefinitionsRequest\x12\x12\n" +
	"\x04page\x18\x01 \x01(\x05R\x04page\x12\x12\n" +
	"\x04size\x18\x02 \x01(\x05R\x04size\"\x83\x01\n" +
	"\x1cListFieldDefinitionsResponse\x121\n" +
	"\x05items\x18\x01 \x03(\v2\x1b.rh_trex.v1.FieldDefinitionR\x05items\x120\n" +
	"\bmetadata\x18\x02 \x01(\v2\x14.rh_trex.v1.ListMetaR\bmetadata\"\x1f\n" +
	"\x1dDeleteFieldDefinitionResponse\"\x1e\n" +
	"\x1cWatchFieldDefinitionsRequest\"\xae\x01\n" +
	"\x19FieldDefinitionWatchEvent\x12)\n" +
	"\x04type\x18\x01 \x01(\x0e2\x15.rh_trex.v1.EventTypeR\x04type\x12E\n" +
	"\x0ffieldDefinition\x18\x02 \x01(\v2\x1b.rh_trex.v1.FieldDefinitionR\x0ffieldDefinition\x12\x1f\n" +
	"\vresource_id\x18\x03 \x01(\tR\n" +
	"resourceId2\xf7\x04\n" +
	"\x16FieldDefinitionService\x12X\n" +
	"\x12GetFieldDefinition\x12%.rh_trex.v1.GetFieldDefinitionRequest\x1a\x1b.rh_trex.v1.FieldDefinition\x12^\n" +
	"\x15CreateFieldDefinition\x12(.rh_trex.v1.CreateFieldDefinitionRequest\x1a\x1b.rh_trex.v1.FieldDefinition\x12^\n" +
	"\x15UpdateFieldDefinition\x12(.rh_trex.v1.UpdateFieldDefinitionRequest\x1a\x1b.rh_trex.v1.FieldDefinition\x12l\n" +
	"\x15DeleteFieldDefinition\x12(.rh_trex.v1.DeleteFieldDefinitionRequest\x1a).rh_trex.v1.DeleteFieldDefinitionResponse\x12i\n" +
	"\x14ListFieldDefinitions\x12'.rh_trex.v1.ListFieldDefinitionsRequest\x1a(.rh_trex.v1.ListFieldDefinitionsResponse\x12j\n" +
	"\x15WatchFieldDefinitions\x12(.rh_trex.v1.WatchFieldDefinitionsRequest\x1a%.rh_trex.v1.FieldDefinitionWatchEvent0\x01BKZIgithub.com/openshift-online/rh-trex-ai/pkg/api/grpc/rh_trex/v1;rh_trex_v1b\x06proto3"

var (
	file_rh_trex_v1_field_definitions_proto_rawDescOnce sync.Once
	file_rh_trex_v1_field_definitions_proto_rawDescData []byte
)

func file_rh_trex_v1_field_definitions_proto_rawDescGZIP() []byte {
	file_rh_trex_v1_field_definitions_proto_rawDescOnce.Do(func() {
		file_rh_trex_v1_field_definitions_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_rh_trex_v1_field_definitions_proto_rawDesc), len(file_rh_trex_v1_field_definitions_proto_rawDesc)))
	})
	return file_rh_trex_v1_field_definitions_proto_rawDescData
}

var file_rh_trex_v1_field_definitions_proto_msgTypes = make([]protoimpl.MessageInfo, 10)
var file_rh_trex_v1_field_definitions_proto_goTypes = []any{
	(*FieldDefinition)(nil),               // 0: rh_trex.v1.FieldDefinition
	(*CreateFieldDefinitionRequest)(nil),  // 1: rh_trex.v1.CreateFieldDefinitionRequest
	(*GetFieldDefinitionRequest)(nil),     // 2: rh_trex.v1.GetFieldDefinitionRequest
	(*UpdateFieldDefinitionRequest)(nil),  // 3: rh_trex.v1.UpdateFieldDefinitionRequest
	(*DeleteFieldDefinitionRequest)(nil),  // 4: rh_trex.v1.DeleteFieldDefinitionRequest
	(*ListFieldDefinitionsRequest)(nil),   // 5: rh_trex.v1.ListFieldDefinitionsRequest
	(*ListFieldDefinitionsResponse)(nil),  // 6: rh_trex.v1.ListFieldDefinitionsResponse
	(*DeleteFieldDefinitionResponse)(nil), // 7: rh_trex.v1.DeleteFieldDefinitionResponse
	(*WatchFieldDefinitionsRequest)(nil),  // 8: rh_trex.v1.WatchFieldDefinitionsRequest
	(*FieldDefinitionWatchEvent)(nil),     // 9: rh_trex.v1.FieldDefinitionWatchEvent
	(*ObjectReference)(nil),               // 10: rh_trex.v1.ObjectReference
	(*ListMeta)(nil),                      // 11: rh_trex.v1.ListMeta
	(EventType)(0),                        // 12: rh_trex.v1.EventType
}
var file_rh_trex_v1_field_definitions_proto_depIdxs = []int32{
	10, // 0: rh_trex.v1.FieldDefinition.metadata:type_name -> rh_trex.v1.ObjectReference
	0,  // 1: rh_trex.v1.ListFieldDefinitionsResponse.items:type_name -> rh_trex.v1.FieldDefinition
	11, // 2: rh_trex.v1.ListFieldDefinitionsResponse.metadata:type_name -> rh_trex.v1.ListMeta
	12, // 3: rh_trex.v1.FieldDefinitionWatchEvent.type:type_name -> rh_trex.v1.EventType
	0,  // 4: rh_trex.v1.FieldDefinitionWatchEvent.fieldDefinition:type_name -> rh_trex.v1.FieldDefinition
	2,  // 5: rh_trex.v1.FieldDefinitionService.GetFieldDefinition:input_type -> rh_trex.v1.GetFieldDefinitionRequest
	1,  // 6: rh_trex.v1.FieldDefinitionService.CreateFieldDefinition:input_type -> rh_trex.v1.CreateFieldDefinitionRequest
	3,  // 7: rh_trex.v1.FieldDefinitionService.UpdateFieldDefinition:input_type -> rh_trex.v1.UpdateFieldDefinitionRequest
	4,  // 8: rh_trex.v1.FieldDefinitionService.DeleteFieldDefinition:input_type -> rh_trex.v1.DeleteFieldDefinitionRequest
	5,  // 9: rh_trex.v1.FieldDefinitionService.ListFieldDefinitions:input_type -> rh_trex.v1.ListFieldDefinitionsRequest
	8,  // 10: rh_trex.v1.FieldDefinitionService.WatchFieldDefinitions:input_type -> rh_trex.v1.WatchFieldDefinitionsRequest
	0,  // 11: rh_trex.v1.FieldDefinitionService.GetFieldDefinition:output_type -> rh_trex.v1.FieldDefinition
	0,  // 12: rh_trex.v1.FieldDefinitionService.CreateFieldDefinition:output_type -> rh_trex.v1.FieldDefinition
	0,  // 13: rh_trex.v1.FieldDefinitionService.UpdateFieldDefinition:output_type -> rh_trex.v1.FieldDefinition
	7,  // 14: rh_trex.v1.FieldDefinitionService.DeleteFieldDefinition:output_type -> rh_trex.v1.DeleteFieldDefinitionResponse
	6,  // 15: rh_trex.v1.FieldDefinitionService.ListFieldDefinitions:output_type -> rh_trex.v1.ListFieldDefinitionsResponse
	9,  // 16: rh_trex.v1.FieldDefinitionService.WatchFieldDefinitions:output_type -> rh_trex.v1.FieldDefinitionWatchEvent
	11, // [11:17] is the sub-list for method output_type
	5,  // [5:11] is the sub-list for method input_type
	5,  // [5:5] is the sub-list for extension type_name
	5,  // [5:5] is the sub-list for extension extendee
	0,  // [0:5] is the sub-list for field type_name
}

func init() { file_rh_trex_v1_field_definitions_proto_init() }
func file_rh_trex_v1_field_definitions_proto_init() {
	if File_rh_trex_v1_field_definitions_proto != nil {
		return
	}
	file_rh_trex_v1_common_proto_init()
	file_rh_trex_v1_field_definitions_proto_msgTypes[0].OneofWrappers = []any{}
	file_rh_trex_v1_field_definitions_proto_msgTypes[1].OneofWrappers = []any{}
	file_rh_trex_v1_field_definitions_proto_msgTypes[3].OneofWrappers = []any{}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_rh_trex_v1_field_definitions_proto_rawDesc), len(file_rh_trex_v1_field_definitions_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   10,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_rh_trex_v1_field_definitions_proto_goTypes,
		DependencyIndexes: file_rh_trex_v1_field_definitions_proto_depIdxs,
		MessageInfos:      file_rh_trex_v1_field_definitions_proto_msgTypes,
	}.Build()
	File_rh_trex_v1_field_definitions_proto = out.File
	file_rh_trex_v1_field_definitions_proto_goTypes = nil
	file_rh_trex_v1_field_definitions_proto_depIdxs = nil
}
