// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        (unknown)
// source: rh_trex/v1/projects.proto

package rh_trex_v1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Project struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Metadata      *ObjectReference       `protobuf:"bytes,1,opt,name=metadata,proto3" json:"metadata,omitempty"`
	Name          string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Description   *string                `protobuf:"bytes,3,opt,name=description,proto3,oneof" json:"description,omitempty"`
	RepositoryUrl *string                `protobuf:"bytes,4,opt,name=repository_url,json=repositoryUrl,proto3,oneof" json:"repository_url,omitempty"`
	Status        string                 `protobuf:"bytes,5,opt,name=status,proto3" json:"status,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Project) Reset() {
	*x = Project{}
	mi := &file_rh_trex_v1_projects_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Project) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Project) ProtoMessage() {}

func (x *Project) ProtoReflect() protoreflect.Message {
	mi := &file_rh_trex_v1_projects_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Project.ProtoReflect.Descriptor instead.
func (*Project) Descriptor() ([]byte, []int) {
	return file_rh_trex_v1_projects_proto_rawDescGZIP(), []int{0}
}

func (x *Project) GetMetadata() *ObjectReference {
	if x != nil {
		return x.Metadata
	}
	return nil
}

func (x *Project) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *Project) GetDescription() string {
	if x != nil && x.Description != nil {
		return *x.Description
	}
	return ""
}

func (x *Project) GetRepositoryUrl() string {
	if x != nil && x.RepositoryUrl != nil {
		return *x.RepositoryUrl
	}
	return ""
}

func (x *Project) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

type CreateProjectRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Description   *string                `protobuf:"bytes,2,opt,name=description,proto3,oneof" json:"description,omitempty"`
	RepositoryUrl *string                `protobuf:"bytes,3,opt,name=repository_url,json=repositoryUrl,proto3,oneof" json:"repository_url,omitempty"`
	Status        string                 `protobuf:"bytes,4,opt,name=status,proto3" json:"status,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateProjectRequest) Reset() {
	*x = CreateProjectRequest{}
	mi := &file_rh_trex_v1_projects_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateProjectRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateProjectRequest) ProtoMessage() {}

func (x *CreateProjectRequest) ProtoReflect() protoreflect.Message {
	mi := &file_rh_trex_v1_projects_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateProjectRequest.ProtoReflect.Descriptor instead.
func (*CreateProjectRequest) Descriptor() ([]byte, []int) {
	return file_rh_trex_v1_projects_proto_rawDescGZIP(), []int{1}
}

func (x *CreateProjectRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *CreateProjectRequest) GetDescription() string {
	if x != nil && x.Description != nil {
		return *x.Description
	}
	return ""
}

func (x *CreateProjectRequest) GetRepositoryUrl() string {
	if x != nil && x.RepositoryUrl != nil {
		return *x.RepositoryUrl
	}
	return ""
}

func (x *CreateProjectRequest) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

type GetProjectRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetProjectRequest) Reset() {
	*x = GetProjectRequest{}
	mi := &file_rh_trex_v1_projects_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetProjectRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetProjectRequest) ProtoMessage() {}

func (x *GetProjectRequest) ProtoReflect() protoreflect.Message {
	mi := &file_rh_trex_v1_projects_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetProjectRequest.ProtoReflect.Descriptor instead.
func (*GetProjectRequest) Descriptor() ([]byte, []int) {
	return file_rh_trex_v1_projects_proto_rawDescGZIP(), []int{2}
}

func (x *GetProjectRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

type UpdateProjectRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Name          *string                `protobuf:"bytes,2,opt,name=name,proto3,oneof" json:"name,omitempty"`
	Description   *string                `protobuf:"bytes,3,opt,name=description,proto3,oneof" json:"description,omitempty"`
	RepositoryUrl *string                `protobuf:"bytes,4,opt,name=repository_url,json=repositoryUrl,proto3,oneof" json:"repository_url,omitempty"`
	Status        *string                `protobuf:"bytes,5,opt,name=status,proto3,oneof" json:"status,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateProjectRequest) Reset() {
	*x = UpdateProjectRequest{}
	mi := &file_rh_trex_v1_projects_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateProjectRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateProjectRequest) ProtoMessage() {}

func (x *UpdateProjectRequest) ProtoReflect() protoreflect.Message {
	mi := &file_rh_trex_v1_projects_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateProjectRequest.ProtoReflect.Descriptor instead.
func (*UpdateProjectRequest) Descriptor() ([]byte, []int) {
	return file_rh_trex_v1_projects_proto_rawDescGZIP(), []int{3}
}

func (x *UpdateProjectRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *UpdateProjectRequest) GetName() string {
	if x != nil && x.Name != nil {
		return *x.Name
	}
	return ""
}

func (x *UpdateProjectRequest) GetDescription() string {
	if x != nil && x.Description != nil {
		return *x.Description
	}
	return ""
}

func (x *UpdateProjectRequest) GetRepositoryUrl() string {
	if x != nil && x.RepositoryUrl != nil {
		return *x.RepositoryUrl
	}
	return ""
}

func (x *UpdateProjectRequest) GetStatus() string {
	if x != nil && x.Status != nil {
		return *x.Status
	}
	return ""
}

type DeleteProjectRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteProjectRequest) Reset() {
	*x = DeleteProjectRequest{}
	mi := &file_rh_trex_v1_projects_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteProjectRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteProjectRequest) ProtoMessage() {}

func (x *DeleteProjectRequest) ProtoReflect() protoreflect.Message {
	mi := &file_rh_trex_v1_projects_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteProjectRequest.ProtoReflect.Descriptor instead.
func (*DeleteProjectRequest) Descriptor() ([]byte, []int) {
	return file_rh_trex_v1_projects_proto_rawDescGZIP(), []int{4}
}

func (x *DeleteProjectRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

type ListProjectsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Page          int32                  `protobuf:"varint,1,opt,name=page,proto3" json:"page,omitempty"`
	Size          int32                  `protobuf:"varint,2,opt,name=size,proto3" json:"size,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListProjectsRequest) Reset() {
	*x = ListProjectsRequest{}
	mi := &file_rh_trex_v1_projects_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListProjectsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListProjectsRequest) ProtoMessage() {}

func (x *ListProjectsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_rh_trex_v1_projects_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListProjectsRequest.ProtoReflect.Descriptor instead.
func (*ListProjectsRequest) Descriptor() ([]byte, []int) {
	return file_rh_trex_v1_projects_proto_rawDescGZIP(), []int{5}
}

func (x *ListProjectsRequest) GetPage() int32 {
	if x != nil {
		return x.Page
	}
	return 0
}

func (x *ListProjectsRequest) GetSize() int32 {
	if x != nil {
		return x.Size
	}
	return 0
}

type ListProjectsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Items         []*Project             `protobuf:"bytes,1,rep,name=items,proto3" json:"items,omitempty"`
	Metadata      *ListMeta              `protobuf:"bytes,2,opt,name=metadata,proto3" json:"metadata,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListProjectsResponse) Reset() {
	*x = ListProjectsResponse{}
	mi := &file_rh_trex_v1_projects_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListProjectsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListProjectsResponse) ProtoMessage() {}

func (x *ListProjectsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_rh_trex_v1_projects_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListProjectsResponse.ProtoReflect.Descriptor instead.
func (*ListProjectsResponse) Descriptor() ([]byte, []int) {
	return file_rh_trex_v1_projects_proto_rawDescGZIP(), []int{6}
}

func (x *ListProjectsResponse) GetItems() []*Project {
	if x != nil {
		return x.Items
	}
	return nil
}

func (x *ListProjectsResponse) GetMetadata() *ListMeta {
	if x != nil {
		return x.Metadata
	}
	return nil
}

type DeleteProjectResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteProjectResponse) Reset() {
	*x = DeleteProjectResponse{}
	mi := &file_rh_trex_v1_projects_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteProjectResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteProjectResponse) ProtoMessage() {}

func (x *DeleteProjectResponse) ProtoReflect() protoreflect.Message {
	mi := &file_rh_trex_v1_projects_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteProjectResponse.ProtoReflect.Descriptor instead.
func (*DeleteProjectResponse) Descriptor() ([]byte, []int) {
	return file_rh_trex_v1_projects_proto_rawDescGZIP(), []int{7}
}

type WatchProjectsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *WatchProjectsRequest) Reset() {
	*x = WatchProjectsRequest{}
	mi := &file_rh_trex_v1_projects_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *WatchProjectsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*WatchProjectsRequest) ProtoMessage() {}

func (x *WatchProjectsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_rh_trex_v1_projects_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use WatchProjectsRequest.ProtoReflect.Descriptor instead.
func (*WatchProjectsRequest) Descriptor() ([]byte, []int) {
	return file_rh_trex_v1_projects_proto_rawDescGZIP(), []int{8}
}

type ProjectWatchEvent struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Type          EventType              `protobuf:"varint,1,opt,name=type,proto3,enum=rh_trex.v1.EventType" json:"type,omitempty"`
	Project       *Project               `protobuf:"bytes,2,opt,name=project,proto3" json:"project,omitempty"`
	ResourceId    string                 `protobuf:"bytes,3,opt,name=resource_id,json=resourceId,proto3" json:"resource_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ProjectWatchEvent) Reset() {
	*x = ProjectWatchEvent{}
	mi := &file_rh_trex_v1_projects_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ProjectWatchEvent) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ProjectWatchEvent) ProtoMessage() {}

func (x *ProjectWatchEvent) ProtoReflect() protoreflect.Message {
	mi := &file_rh_trex_v1_projects_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ProjectWatchEvent.ProtoReflect.Descriptor instead.
func (*ProjectWatchEvent) Descriptor() ([]byte, []int) {
	return file_rh_trex_v1_projects_proto_rawDescGZIP(), []int{9}
}

func (x *ProjectWatchEvent) GetType() EventType {
	if x != nil {
		return x.Type
	}
	return EventType_EVENT_TYPE_UNSPECIFIED
}

func (x *ProjectWatchEvent) GetProject() *Project {
	if x != nil {
		return x.Project
	}
	return nil
}

func (x *ProjectWatchEvent) GetResourceId() string {
	if x != nil {
		return x.ResourceId
	}
	return ""
}

var File_rh_trex_v1_projects_proto protoreflect.FileDescriptor

const file_rh_trex_v1_projects_proto_rawDesc = "" +
	"\n" +
	"\x19rh_trex/v1/projects.proto\x12\n" +
	"rh_trex.v1\x1a\x17rh_trex/v1/common.proto\"\xe4\x01\n" +
	"\aProject\x127\n" +
	"\bmetadata\x18\x01 \x01(\v2\x1b.rh_trex.v1.ObjectReferenceR\bmetadata\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12%\n" +
	"\vdescription\x18\x03 \x01(\tH\x00R\vdescription\x88\x01\x01\x12*\n" +
	"\x0erepository_url\x18\x04 \x01(\tH\x01R\rrepositoryUrl\x88\x01\x01\x12\x16\n" +
	"\x06status\x18\x05 \x01(\tR\x06statusB\x0e\n" +
	"\f_descriptionB\x11\n" +
	"\x0f_repository_url\"\xb8\x01\n" +
	"\x14CreateProjectRequest\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12%\n" +
	"\vdescription\x18\x02 \x01(\tH\x00R\vdescription\x88\x01\x01\x12*\n" +
	"\x0erepository_url\x18\x03 \x01(\tH\x01R\rrepositoryUrl\x88\x01\x01\x12\x16\n" +
	"\x06status\x18\x04 \x01(\tR\x06statusB\x0e\n" +
	"\f_descriptionB\x11\n" +
	"\x0f_repository_url\"#\n" +
	"\x11GetProjectRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\"\xe6\x01\n" +
	"\x14UpdateProjectRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x17\n" +
	"\x04name\x18\x02 \x01(\tH\x00R\x04name\x88\x01\x01\x12%\n" +
	"\vdescription\x18\x03 \x01(\tH\x01R\vdescription\x88\x01\x01\x12*\n" +
	"\x0erepository_url\x18\x04 \x01(\tH\x02R\rrepositoryUrl\x88\x01\x01\x12\x1b\n" +
	"\x06status\x18\x05 \x01(\tH\x03R\x06status\x88\x01\x01B\a\n" +
	"\x05_nameB\x0e\n" +
	"\f_descriptionB\x11\n" +
	"\x0f_repository_urlB\t\n" +
	"\a_status\"&\n" +
	"\x14DeleteProjectRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\"=\n" +
	"\x13ListProjectsRequest\x12\x12\n" +
	"\x04page\x18\x01 \x01(\x05R\x04page\x12\x12\n" +
	"\x04size\x18\x02 \x01(\x05R\x04size\"s\n" +
	"\x14ListProjectsResponse\x12)\n" +
	"\x05items\x18\x01 \x03(\v2\x13.rh_trex.v1.ProjectR\x05items\x120\n" +
	"\bmetadata\x18\x02 \x01(\v2\x14.rh_trex.v1.ListMetaR\bmetadata\"\x17\n" +
	"\x15DeleteProjectResponse\"\x16\n" +
	"\x14WatchProjectsRequest\"\x8e\x01\n" +
	"\x11ProjectWatchEvent\x12)\n" +
	"\x04type\x18\x01 \x01(\x0e2\x15.rh_trex.v1.EventTypeR\x04type\x12-\n" +
	"\aproject\x18\x02 \x01(\v2\x13.rh_trex.v1.ProjectR\aproject\x12\x1f\n" +
	"\vresource_id\x18\x03 \x01(\tR\n" +
	"resourceId2\xdf\x03\n" +
	"\x0eProjectService\x12@\n" +
	"\n" +
	"GetProject\x12\x1d.rh_trex.v1.GetProjectRequest\x1a\x13.rh_trex.v1.Project\x12F\n" +
	"\rCreateProject\x12 .rh_trex.v1.CreateProjectRequest\x1a\x13.rh_trex.v1.Project\x12F\n" +
	"\rUpdateProject\x12 .rh_trex.v1.UpdateProjectRequest\x1a\x13.rh_trex.v1.Project\x12T\n" +
	"\rDeleteProject\x12 .rh_trex.v1.DeleteProjectRequest\x1a!.rh_trex.v1.DeleteProjectResponse\x12Q\n" +
	"\fListProjects\x12\x1f.rh_trex.v1.ListProjectsRequest\x1a .rh_trex.v1.ListProjectsResponse\x12R\n" +
	"\rWatchProjects\x12 .rh_trex.v1.WatchProjectsRequest\x1a\x1d.rh_trex.v1.ProjectWatchEvent0\x01BKZIgithub.com/openshift-online/rh-trex-ai/pkg/api/grpc/rh_trex/v1;rh_trex_v1b\x06proto3"

var (
	file_rh_trex_v1_projects_proto_rawDescOnce sync.Once
	file_rh_trex_v1_projects_proto_rawDescData []byte
)

func file_rh_trex_v1_projects_proto_rawDescGZIP() []byte {
	file_rh_trex_v1_projects_proto_rawDescOnce.Do(func() {
		file_rh_trex_v1_projects_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_rh_trex_v1_projects_proto_rawDesc), len(file_rh_trex_v1_projects_proto_rawDesc)))
	})
	return file_rh_trex_v1_projects_proto_rawDescData
}

var file_rh_trex_v1_projects_proto_msgTypes = make([]protoimpl.MessageInfo, 10)
var file_rh_trex_v1_projects_proto_goTypes = []any{
	(*Project)(nil),               // 0: rh_trex.v1.Project
	(*CreateProjectRequest)(nil),  // 1: rh_trex.v1.CreateProjectRequest
	(*GetProjectRequest)(nil),     // 2: rh_trex.v1.GetProjectRequest
	(*UpdateProjectRequest)(nil),  // 3: rh_trex.v1.UpdateProjectRequest
	(*DeleteProjectRequest)(nil),  // 4: rh_trex.v1.DeleteProjectRequest
	(*ListProjectsRequest)(nil),   // 5: rh_trex.v1.ListProjectsRequest
	(*ListProjectsResponse)(nil),  // 6: rh_trex.v1.ListProjectsResponse
	(*DeleteProjectResponse)(nil), // 7: rh_trex.v1.DeleteProjectResponse
	(*WatchProjectsRequest)(nil),  // 8: rh_trex.v1.WatchProjectsRequest
	(*ProjectWatchEvent)(nil),     // 9: rh_trex.v1.ProjectWatchEvent
	(*ObjectReference)(nil),       // 10: rh_trex.v1.ObjectReference
	(*ListMeta)(nil),              // 11: rh_trex.v1.ListMeta
	(EventType)(0),                // 12: rh_trex.v1.EventType
}
var file_rh_trex_v1_projects_proto_depIdxs = []int32{
	10, // 0: rh_trex.v1.Project.metadata:type_name -> rh_trex.v1.ObjectReference
	0,  // 1: rh_trex.v1.ListProjectsResponse.items:type_name -> rh_trex.v1.Project
	11, // 2: rh_trex.v1.ListProjectsResponse.metadata:type_name -> rh_trex.v1.ListMeta
	12, // 3: rh_trex.v1.ProjectWatchEvent.type:type_name -> rh_trex.v1.EventType
	0,  // 4: rh_trex.v1.ProjectWatchEvent.project:type_name -> rh_trex.v1.Project
	2,  // 5: rh_trex.v1.ProjectService.GetProject:input_type -> rh_trex.v1.GetProjectRequest
	1,  // 6: rh_trex.v1.ProjectService.CreateProject:input_type -> rh_trex.v1.CreateProjectRequest
	3,  // 7: rh_trex.v1.ProjectService.UpdateProject:input_type -> rh_trex.v1.UpdateProjectRequest
	4,  // 8: rh_trex.v1.ProjectService.DeleteProject:input_type -> rh_trex.v1.DeleteProjectRequest
	5,  // 9: rh_trex.v1.ProjectService.ListProjects:input_type -> rh_trex.v1.ListProjectsRequest
	8,  // 10: rh_trex.v1.ProjectService.WatchProjects:input_type -> rh_trex.v1.WatchProjectsRequest
	0,  // 11: rh_trex.v1.ProjectService.GetProject:output_type -> rh_trex.v1.Project
	0,  // 12: rh_trex.v1.ProjectService.CreateProject:output_type -> rh_trex.v1.Project
	0,  // 13: rh_trex.v1.ProjectService.UpdateProject:output_type -> rh_trex.v1.Project
	7,  // 14: rh_trex.v1.ProjectService.DeleteProject:output_type -> rh_trex.v1.DeleteProjectResponse
	6,  // 15: rh_trex.v1.ProjectService.ListProjects:output_type -> rh_trex.v1.ListProjectsResponse
	9,  // 16: rh_trex.v1.ProjectService.WatchProjects:output_type -> rh_trex.v1.ProjectWatchEvent
	11, // [11:17] is the sub-list for method output_type
	5,  // [5:11] is the sub-list for method input_type
	5,  // [5:5] is the sub-list for extension type_name
	5,  // [5:5] is the sub-list for extension extendee
	0,  // [0:5] is the sub-list for field type_name
}

func init() { file_rh_trex_v1_projects_proto_init() }
func file_rh_trex_v1_projects_proto_init() {
	if File_rh_trex_v1_projects_proto != nil {
		return
	}
	file_rh_trex_v1_common_proto_init()
	file_rh_trex_v1_projects_proto_msgTypes[0].OneofWrappers = []any{}
	file_rh_trex_v1_projects_proto_msgTypes[1].OneofWrappers = []any{}
	file_rh_trex_v1_projects_proto_msgTypes[3].OneofWrappers = []any{}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_rh_trex_v1_projects_proto_rawDesc), len(file_rh_trex_v1_projects_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   10,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_rh_trex_v1_projects_proto_goTypes,
		DependencyIndexes: file_rh_trex_v1_projects_proto_depIdxs,
		MessageInfos:      file_rh_trex_v1_projects_proto_msgTypes,
	}.Build()
	File_rh_trex_v1_projects_proto = out.File
	file_rh_trex_v1_projects_proto_goTypes = nil
	file_rh_trex_v1_projects_proto_depIdxs = nil
}
