// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        (unknown)
// source: rh_trex/v1/relationships.proto

package rh_trex_v1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Relationship struct {
	state            protoimpl.MessageState `protogen:"open.v1"`
	Metadata         *ObjectReference       `protobuf:"bytes,1,opt,name=metadata,proto3" json:"metadata,omitempty"`
	ProjectId        string                 `protobuf:"bytes,2,opt,name=project_id,json=projectId,proto3" json:"project_id,omitempty"`
	SourceEntityId   string                 `protobuf:"bytes,3,opt,name=source_entity_id,json=sourceEntityId,proto3" json:"source_entity_id,omitempty"`
	TargetEntityId   string                 `protobuf:"bytes,4,opt,name=target_entity_id,json=targetEntityId,proto3" json:"target_entity_id,omitempty"`
	RelationshipType string                 `protobuf:"bytes,5,opt,name=relationship_type,json=relationshipType,proto3" json:"relationship_type,omitempty"`
	ForeignKey       *string                `protobuf:"bytes,6,opt,name=foreign_key,json=foreignKey,proto3,oneof" json:"foreign_key,omitempty"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *Relationship) Reset() {
	*x = Relationship{}
	mi := &file_rh_trex_v1_relationships_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Relationship) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Relationship) ProtoMessage() {}

func (x *Relationship) ProtoReflect() protoreflect.Message {
	mi := &file_rh_trex_v1_relationships_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Relationship.ProtoReflect.Descriptor instead.
func (*Relationship) Descriptor() ([]byte, []int) {
	return file_rh_trex_v1_relationships_proto_rawDescGZIP(), []int{0}
}

func (x *Relationship) GetMetadata() *ObjectReference {
	if x != nil {
		return x.Metadata
	}
	return nil
}

func (x *Relationship) GetProjectId() string {
	if x != nil {
		return x.ProjectId
	}
	return ""
}

func (x *Relationship) GetSourceEntityId() string {
	if x != nil {
		return x.SourceEntityId
	}
	return ""
}

func (x *Relationship) GetTargetEntityId() string {
	if x != nil {
		return x.TargetEntityId
	}
	return ""
}

func (x *Relationship) GetRelationshipType() string {
	if x != nil {
		return x.RelationshipType
	}
	return ""
}

func (x *Relationship) GetForeignKey() string {
	if x != nil && x.ForeignKey != nil {
		return *x.ForeignKey
	}
	return ""
}

type CreateRelationshipRequest struct {
	state            protoimpl.MessageState `protogen:"open.v1"`
	ProjectId        string                 `protobuf:"bytes,1,opt,name=project_id,json=projectId,proto3" json:"project_id,omitempty"`
	SourceEntityId   string                 `protobuf:"bytes,2,opt,name=source_entity_id,json=sourceEntityId,proto3" json:"source_entity_id,omitempty"`
	TargetEntityId   string                 `protobuf:"bytes,3,opt,name=target_entity_id,json=targetEntityId,proto3" json:"target_entity_id,omitempty"`
	RelationshipType string                 `protobuf:"bytes,4,opt,name=relationship_type,json=relationshipType,proto3" json:"relationship_type,omitempty"`
	ForeignKey       *string                `protobuf:"bytes,5,opt,name=foreign_key,json=foreignKey,proto3,oneof" json:"foreign_key,omitempty"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *CreateRelationshipRequest) Reset() {
	*x = CreateRelationshipRequest{}
	mi := &file_rh_trex_v1_relationships_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateRelationshipRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateRelationshipRequest) ProtoMessage() {}

func (x *CreateRelationshipRequest) ProtoReflect() protoreflect.Message {
	mi := &file_rh_trex_v1_relationships_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateRelationshipRequest.ProtoReflect.Descriptor instead.
func (*CreateRelationshipRequest) Descriptor() ([]byte, []int) {
	return file_rh_trex_v1_relationships_proto_rawDescGZIP(), []int{1}
}

func (x *CreateRelationshipRequest) GetProjectId() string {
	if x != nil {
		return x.ProjectId
	}
	return ""
}

func (x *CreateRelationshipRequest) GetSourceEntityId() string {
	if x != nil {
		return x.SourceEntityId
	}
	return ""
}

func (x *CreateRelationshipRequest) GetTargetEntityId() string {
	if x != nil {
		return x.TargetEntityId
	}
	return ""
}

func (x *CreateRelationshipRequest) GetRelationshipType() string {
	if x != nil {
		return x.RelationshipType
	}
	return ""
}

func (x *CreateRelationshipRequest) GetForeignKey() string {
	if x != nil && x.ForeignKey != nil {
		return *x.ForeignKey
	}
	return ""
}

type GetRelationshipRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetRelationshipRequest) Reset() {
	*x = GetRelationshipRequest{}
	mi := &file_rh_trex_v1_relationships_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetRelationshipRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetRelationshipRequest) ProtoMessage() {}

func (x *GetRelationshipRequest) ProtoReflect() protoreflect.Message {
	mi := &file_rh_trex_v1_relationships_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetRelationshipRequest.ProtoReflect.Descriptor instead.
func (*GetRelationshipRequest) Descriptor() ([]byte, []int) {
	return file_rh_trex_v1_relationships_proto_rawDescGZIP(), []int{2}
}

func (x *GetRelationshipRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

type UpdateRelationshipRequest struct {
	state            protoimpl.MessageState `protogen:"open.v1"`
	Id               string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	ProjectId        *string                `protobuf:"bytes,2,opt,name=project_id,json=projectId,proto3,oneof" json:"project_id,omitempty"`
	SourceEntityId   *string                `protobuf:"bytes,3,opt,name=source_entity_id,json=sourceEntityId,proto3,oneof" json:"source_entity_id,omitempty"`
	TargetEntityId   *string                `protobuf:"bytes,4,opt,name=target_entity_id,json=targetEntityId,proto3,oneof" json:"target_entity_id,omitempty"`
	RelationshipType *string                `protobuf:"bytes,5,opt,name=relationship_type,json=relationshipType,proto3,oneof" json:"relationship_type,omitempty"`
	ForeignKey       *string                `protobuf:"bytes,6,opt,name=foreign_key,json=foreignKey,proto3,oneof" json:"foreign_key,omitempty"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *UpdateRelationshipRequest) Reset() {
	*x = UpdateRelationshipRequest{}
	mi := &file_rh_trex_v1_relationships_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateRelationshipRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateRelationshipRequest) ProtoMessage() {}

func (x *UpdateRelationshipRequest) ProtoReflect() protoreflect.Message {
	mi := &file_rh_trex_v1_relationships_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateRelationshipRequest.ProtoReflect.Descriptor instead.
func (*UpdateRelationshipRequest) Descriptor() ([]byte, []int) {
	return file_rh_trex_v1_relationships_proto_rawDescGZIP(), []int{3}
}

func (x *UpdateRelationshipRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *UpdateRelationshipRequest) GetProjectId() string {
	if x != nil && x.ProjectId != nil {
		return *x.ProjectId
	}
	return ""
}

func (x *UpdateRelationshipRequest) GetSourceEntityId() string {
	if x != nil && x.SourceEntityId != nil {
		return *x.SourceEntityId
	}
	return ""
}

func (x *UpdateRelationshipRequest) GetTargetEntityId() string {
	if x != nil && x.TargetEntityId != nil {
		return *x.TargetEntityId
	}
	return ""
}

func (x *UpdateRelationshipRequest) GetRelationshipType() string {
	if x != nil && x.RelationshipType != nil {
		return *x.RelationshipType
	}
	return ""
}

func (x *UpdateRelationshipRequest) GetForeignKey() string {
	if x != nil && x.ForeignKey != nil {
		return *x.ForeignKey
	}
	return ""
}

type DeleteRelationshipRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteRelationshipRequest) Reset() {
	*x = DeleteRelationshipRequest{}
	mi := &file_rh_trex_v1_relationships_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteRelationshipRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteRelationshipRequest) ProtoMessage() {}

func (x *DeleteRelationshipRequest) ProtoReflect() protoreflect.Message {
	mi := &file_rh_trex_v1_relationships_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteRelationshipRequest.ProtoReflect.Descriptor instead.
func (*DeleteRelationshipRequest) Descriptor() ([]byte, []int) {
	return file_rh_trex_v1_relationships_proto_rawDescGZIP(), []int{4}
}

func (x *DeleteRelationshipRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

type ListRelationshipsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Page          int32                  `protobuf:"varint,1,opt,name=page,proto3" json:"page,omitempty"`
	Size          int32                  `protobuf:"varint,2,opt,name=size,proto3" json:"size,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListRelationshipsRequest) Reset() {
	*x = ListRelationshipsRequest{}
	mi := &file_rh_trex_v1_relationships_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListRelationshipsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListRelationshipsRequest) ProtoMessage() {}

func (x *ListRelationshipsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_rh_trex_v1_relationships_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListRelationshipsRequest.ProtoReflect.Descriptor instead.
func (*ListRelationshipsRequest) Descriptor() ([]byte, []int) {
	return file_rh_trex_v1_relationships_proto_rawDescGZIP(), []int{5}
}

func (x *ListRelationshipsRequest) GetPage() int32 {
	if x != nil {
		return x.Page
	}
	return 0
}

func (x *ListRelationshipsRequest) GetSize() int32 {
	if x != nil {
		return x.Size
	}
	return 0
}

type ListRelationshipsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Items         []*Relationship        `protobuf:"bytes,1,rep,name=items,proto3" json:"items,omitempty"`
	Metadata      *ListMeta              `protobuf:"bytes,2,opt,name=metadata,proto3" json:"metadata,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListRelationshipsResponse) Reset() {
	*x = ListRelationshipsResponse{}
	mi := &file_rh_trex_v1_relationships_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListRelationshipsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListRelationshipsResponse) ProtoMessage() {}

func (x *ListRelationshipsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_rh_trex_v1_relationships_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListRelationshipsResponse.ProtoReflect.Descriptor instead.
func (*ListRelationshipsResponse) Descriptor() ([]byte, []int) {
	return file_rh_trex_v1_relationships_proto_rawDescGZIP(), []int{6}
}

func (x *ListRelationshipsResponse) GetItems() []*Relationship {
	if x != nil {
		return x.Items
	}
	return nil
}

func (x *ListRelationshipsResponse) GetMetadata() *ListMeta {
	if x != nil {
		return x.Metadata
	}
	return nil
}

type DeleteRelationshipResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteRelationshipResponse) Reset() {
	*x = DeleteRelationshipResponse{}
	mi := &file_rh_trex_v1_relationships_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteRelationshipResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteRelationshipResponse) ProtoMessage() {}

func (x *DeleteRelationshipResponse) ProtoReflect() protoreflect.Message {
	mi := &file_rh_trex_v1_relationships_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteRelationshipResponse.ProtoReflect.Descriptor instead.
func (*DeleteRelationshipResponse) Descriptor() ([]byte, []int) {
	return file_rh_trex_v1_relationships_proto_rawDescGZIP(), []int{7}
}

type WatchRelationshipsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *WatchRelationshipsRequest) Reset() {
	*x = WatchRelationshipsRequest{}
	mi := &file_rh_trex_v1_relationships_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *WatchRelationshipsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*WatchRelationshipsRequest) ProtoMessage() {}

func (x *WatchRelationshipsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_rh_trex_v1_relationships_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use WatchRelationshipsRequest.ProtoReflect.Descriptor instead.
func (*WatchRelationshipsRequest) Descriptor() ([]byte, []int) {
	return file_rh_trex_v1_relationships_proto_rawDescGZIP(), []int{8}
}

type RelationshipWatchEvent struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Type          EventType              `protobuf:"varint,1,opt,name=type,proto3,enum=rh_trex.v1.EventType" json:"type,omitempty"`
	Relationship  *Relationship          `protobuf:"bytes,2,opt,name=relationship,proto3" json:"relationship,omitempty"`
	ResourceId    string                 `protobuf:"bytes,3,opt,name=resource_id,json=resourceId,proto3" json:"resource_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RelationshipWatchEvent) Reset() {
	*x = RelationshipWatchEvent{}
	mi := &file_rh_trex_v1_relationships_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RelationshipWatchEvent) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RelationshipWatchEvent) ProtoMessage() {}

func (x *RelationshipWatchEvent) ProtoReflect() protoreflect.Message {
	mi := &file_rh_trex_v1_relationships_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RelationshipWatchEvent.ProtoReflect.Descriptor instead.
func (*RelationshipWatchEvent) Descriptor() ([]byte, []int) {
	return file_rh_trex_v1_relationships_proto_rawDescGZIP(), []int{9}
}

func (x *RelationshipWatchEvent) GetType() EventType {
	if x != nil {
		return x.Type
	}
	return EventType_EVENT_TYPE_UNSPECIFIED
}

func (x *RelationshipWatchEvent) GetRelationship() *Relationship {
	if x != nil {
		return x.Relationship
	}
	return nil
}

func (x *RelationshipWatchEvent) GetResourceId() string {
	if x != nil {
		return x.ResourceId
	}
	return ""
}

var File_rh_trex_v1_relationships_proto protoreflect.FileDescriptor

const file_rh_trex_v1_relationships_proto_rawDesc = "" +
	"\n" +
	"\x1erh_trex/v1/relationships.proto\x12\n" +
	"rh_trex.v1\x1a\x17rh_trex/v1/common.proto\"\x9d\x02\n" +
	"\fRelationship\x127\n" +
	"\bmetadata\x18\x01 \x01(\v2\x1b.rh_trex.v1.ObjectReferenceR\bmetadata\x12\x1d\n" +
	"\n" +
	"project_id\x18\x02 \x01(\tR\tprojectId\x12(\n" +
	"\x10source_entity_id\x18\x03 \x01(\tR\x0esourceEntityId\x12(\n" +
	"\x10target_entity_id\x18\x04 \x01(\tR\x0etargetEntityId\x12+\n" +
	"\x11relationship_type\x18\x05 \x01(\tR\x10relationshipType\x12$\n" +
	"\vforeign_key\x18\x06 \x01(\tH\x00R\n" +
	"foreignKey\x88\x01\x01B\x0e\n" +
	"\f_foreign_key\"\xf1\x01\n" +
	"\x19CreateRelationshipRequest\x12\x1d\n" +
	"\n" +
	"project_id\x18\x01 \x01(\tR\tprojectId\x12(\n" +
	"\x10source_entity_id\x18\x02 \x01(\tR\x0esourceEntityId\x12(\n" +
	"\x10target_entity_id\x18\x03 \x01(\tR\x0etargetEntityId\x12+\n" +
	"\x11relationship_type\x18\x04 \x01(\tR\x10relationshipType\x12$\n" +
	"\vforeign_key\x18\x05 \x01(\tH\x00R\n" +
	"foreignKey\x88\x01\x01B\x0e\n" +
	"\f_foreign_key\"(\n" +
	"\x16GetRelationshipRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\"\xe4\x02\n" +
	"\x19UpdateRelationshipRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\"\n" +
	"\n" +
	"project_id\x18\x02 \x01(\tH\x00R\tprojectId\x88\x01\x01\x12-\n" +
	"\x10source_entity_id\x18\x03 \x01(\tH\x01R\x0esourceEntityId\x88\x01\x01\x12-\n" +
	"\x10target_entity_id\x18\x04 \x01(\tH\x02R\x0etargetEntityId\x88\x01\x01\x120\n" +
	"\x11relationship_type\x18\x05 \x01(\tH\x03R\x10relationshipType\x88\x01\x01\x12$\n" +
	"\vforeign_key\x18\x06 \x01(\tH\x04R\n" +
	"foreignKey\x88\x01\x01B\r\n" +
	"\v_project_idB\x13\n" +
	"\x11_source_entity_idB\x13\n" +
	"\x11_target_entity_idB\x14\n" +
	"\x12_relationship_typeB\x0e\n" +
	"\f_foreign_key\"+\n" +
	"\x19DeleteRelationshipRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\"B\n" +
	"\x18ListRelationshipsRequest\x12\x12\n" +
	"\x04page\x18\x01 \x01(\x05R\x04page\x12\x12\n" +
	"\x04size\x18\x02 \x01(\x05R\x04size\"}\n" +
	"\x19ListRelationshipsResponse\x12.\n" +
	"\x05items\x18\x01 \x03(\v2\x18.rh_trex.v1.RelationshipR\x05items\x120\n" +
	"\bmetadata\x18\x02 \x01(\v2\x14.rh_trex.v1.ListMetaR\bmetadata\"\x1c\n" +
	"\x1aDeleteRelationshipResponse\"\x1b\n" +
	"\x19WatchRelationshipsRequest\"\xa2\x01\n" +
	"\x16RelationshipWatchEvent\x12)\n" +
	"\x04type\x18\x01 \x01(\x0e2\x15.rh_trex.v1.EventTypeR\x04type\x12<\n" +
	"\frelationship\x18\x02 \x01(\v2\x18.rh_trex.v1.RelationshipR\frelationship\x12\x1f\n" +
	"\vresource_id\x18\x03 \x01(\tR\n" +
	"resourceId2\xbe\x04\n" +
	"\x13RelationshipService\x12O\n" +
	"\x0fGetRelationship\x12\".rh_trex.v1.GetRelationshipRequest\x1a\x18.rh_trex.v1.Relationship\x12U\n" +
	"\x12CreateRelationship\x12%.rh_trex.v1.CreateRelationshipRequest\x1a\x18.rh_trex.v1.Relationship\x12U\n" +
	"\x12UpdateRelationship\x12%.rh_trex.v1.UpdateRelationshipRequest\x1a\x18.rh_trex.v1.Relationship\x12c\n" +
	"\x12DeleteRelationship\x12%.rh_trex.v1.DeleteRelationshipRequest\x1a&.rh_trex.v1.DeleteRelationshipResponse\x12`\n" +
	"\x11ListRelationships\x12$.rh_trex.v1.ListRelationshipsRequest\x1a%.rh_trex.v1.ListRelationshipsResponse\x12a\n" +
	"\x12WatchRelationships\x12%.rh_trex.v1.WatchRelationshipsRequest\x1a\".rh_trex.v1.RelationshipWatchEvent0\x01BKZIgithub.com/openshift-online/rh-trex-ai/pkg/api/grpc/rh_trex/v1;rh_trex_v1b\x06proto3"

var (
	file_rh_trex_v1_relationships_proto_rawDescOnce sync.Once
	file_rh_trex_v1_relationships_proto_rawDescData []byte
)

func file_rh_trex_v1_relationships_proto_rawDescGZIP() []byte {
	file_rh_trex_v1_relationships_proto_rawDescOnce.Do(func() {
		file_rh_trex_v1_relationships_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_rh_trex_v1_relationships_proto_rawDesc), len(file_rh_trex_v1_relationships_proto_rawDesc)))
	})
	return file_rh_trex_v1_relationships_proto_rawDescData
}

var file_rh_trex_v1_relationships_proto_msgTypes = make([]protoimpl.MessageInfo, 10)
var file_rh_trex_v1_relationships_proto_goTypes = []any{
	(*Relationship)(nil),               // 0: rh_trex.v1.Relationship
	(*CreateRelationshipRequest)(nil),  // 1: rh_trex.v1.CreateRelationshipRequest
	(*GetRelationshipRequest)(nil),     // 2: rh_trex.v1.GetRelationshipRequest
	(*UpdateRelationshipRequest)(nil),  // 3: rh_trex.v1.UpdateRelationshipRequest
	(*DeleteRelationshipRequest)(nil),  // 4: rh_trex.v1.DeleteRelationshipRequest
	(*ListRelationshipsRequest)(nil),   // 5: rh_trex.v1.ListRelationshipsRequest
	(*ListRelationshipsResponse)(nil),  // 6: rh_trex.v1.ListRelationshipsResponse
	(*DeleteRelationshipResponse)(nil), // 7: rh_trex.v1.DeleteRelationshipResponse
	(*WatchRelationshipsRequest)(nil),  // 8: rh_trex.v1.WatchRelationshipsRequest
	(*RelationshipWatchEvent)(nil),     // 9: rh_trex.v1.RelationshipWatchEvent
	(*ObjectReference)(nil),            // 10: rh_trex.v1.ObjectReference
	(*ListMeta)(nil),                   // 11: rh_trex.v1.ListMeta
	(EventType)(0),                     // 12: rh_trex.v1.EventType
}
var file_rh_trex_v1_relationships_proto_depIdxs = []int32{
	10, // 0: rh_trex.v1.Relationship.metadata:type_name -> rh_trex.v1.ObjectReference
	0,  // 1: rh_trex.v1.ListRelationshipsResponse.items:type_name -> rh_trex.v1.Relationship
	11, // 2: rh_trex.v1.ListRelationshipsResponse.metadata:type_name -> rh_trex.v1.ListMeta
	12, // 3: rh_trex.v1.RelationshipWatchEvent.type:type_name -> rh_trex.v1.EventType
	0,  // 4: rh_trex.v1.RelationshipWatchEvent.relationship:type_name -> rh_trex.v1.Relationship
	2,  // 5: rh_trex.v1.RelationshipService.GetRelationship:input_type -> rh_trex.v1.GetRelationshipRequest
	1,  // 6: rh_trex.v1.RelationshipService.CreateRelationship:input_type -> rh_trex.v1.CreateRelationshipRequest
	3,  // 7: rh_trex.v1.RelationshipService.UpdateRelationship:input_type -> rh_trex.v1.UpdateRelationshipRequest
	4,  // 8: rh_trex.v1.RelationshipService.DeleteRelationship:input_type -> rh_trex.v1.DeleteRelationshipRequest
	5,  // 9: rh_trex.v1.RelationshipService.ListRelationships:input_type -> rh_trex.v1.ListRelationshipsRequest
	8,  // 10: rh_trex.v1.RelationshipService.WatchRelationships:input_type -> rh_trex.v1.WatchRelationshipsRequest
	0,  // 11: rh_trex.v1.RelationshipService.GetRelationship:output_type -> rh_trex.v1.Relationship
	0,  // 12: rh_trex.v1.RelationshipService.CreateRelationship:output_type -> rh_trex.v1.Relationship
	0,  // 13: rh_trex.v1.RelationshipService.UpdateRelationship:output_type -> rh_trex.v1.Relationship
	7,  // 14: rh_trex.v1.RelationshipService.DeleteRelationship:output_type -> rh_trex.v1.DeleteRelationshipResponse
	6,  // 15: rh_trex.v1.RelationshipService.ListRelationships:output_type -> rh_trex.v1.ListRelationshipsResponse
	9,  // 16: rh_trex.v1.RelationshipService.WatchRelationships:output_type -> rh_trex.v1.RelationshipWatchEvent
	11, // [11:17] is the sub-list for method output_type
	5,  // [5:11] is the sub-list for method input_type
	5,  // [5:5] is the sub-list for extension type_name
	5,  // [5:5] is the sub-list for extension extendee
	0,  // [0:5] is the sub-list for field type_name
}

func init() { file_rh_trex_v1_relationships_proto_init() }
func file_rh_trex_v1_relationships_proto_init() {
	if File_rh_trex_v1_relationships_proto != nil {
		return
	}
	file_rh_trex_v1_common_proto_init()
	file_rh_trex_v1_relationships_proto_msgTypes[0].OneofWrappers = []any{}
	file_rh_trex_v1_relationships_proto_msgTypes[1].OneofWrappers = []any{}
	file_rh_trex_v1_relationships_proto_msgTypes[3].OneofWrappers = []any{}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_rh_trex_v1_relationships_proto_rawDesc), len(file_rh_trex_v1_relationships_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   10,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_rh_trex_v1_relationships_proto_goTypes,
		DependencyIndexes: file_rh_trex_v1_relationships_proto_depIdxs,
		MessageInfos:      file_rh_trex_v1_relationships_proto_msgTypes,
	}.Build()
	File_rh_trex_v1_relationships_proto = out.File
	file_rh_trex_v1_relationships_proto_goTypes = nil
	file_rh_trex_v1_relationships_proto_depIdxs = nil
}
