// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.12
// 	protoc        (unknown)
// source: rh_trex/v1/dinosaurs.proto

package rh_trex_v1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Dinosaur struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Metadata      *ObjectReference       `protobuf:"bytes,1,opt,name=metadata,proto3" json:"metadata,omitempty"`
	Species       string                 `protobuf:"bytes,2,opt,name=species,proto3" json:"species,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Dinosaur) Reset() {
	*x = Dinosaur{}
	mi := &file_rh_trex_v1_dinosaurs_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Dinosaur) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Dinosaur) ProtoMessage() {}

func (x *Dinosaur) ProtoReflect() protoreflect.Message {
	mi := &file_rh_trex_v1_dinosaurs_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Dinosaur.ProtoReflect.Descriptor instead.
func (*Dinosaur) Descriptor() ([]byte, []int) {
	return file_rh_trex_v1_dinosaurs_proto_rawDescGZIP(), []int{0}
}

func (x *Dinosaur) GetMetadata() *ObjectReference {
	if x != nil {
		return x.Metadata
	}
	return nil
}

func (x *Dinosaur) GetSpecies() string {
	if x != nil {
		return x.Species
	}
	return ""
}

type CreateDinosaurRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Species       string                 `protobuf:"bytes,1,opt,name=species,proto3" json:"species,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateDinosaurRequest) Reset() {
	*x = CreateDinosaurRequest{}
	mi := &file_rh_trex_v1_dinosaurs_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateDinosaurRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateDinosaurRequest) ProtoMessage() {}

func (x *CreateDinosaurRequest) ProtoReflect() protoreflect.Message {
	mi := &file_rh_trex_v1_dinosaurs_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateDinosaurRequest.ProtoReflect.Descriptor instead.
func (*CreateDinosaurRequest) Descriptor() ([]byte, []int) {
	return file_rh_trex_v1_dinosaurs_proto_rawDescGZIP(), []int{1}
}

func (x *CreateDinosaurRequest) GetSpecies() string {
	if x != nil {
		return x.Species
	}
	return ""
}

type GetDinosaurRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetDinosaurRequest) Reset() {
	*x = GetDinosaurRequest{}
	mi := &file_rh_trex_v1_dinosaurs_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetDinosaurRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetDinosaurRequest) ProtoMessage() {}

func (x *GetDinosaurRequest) ProtoReflect() protoreflect.Message {
	mi := &file_rh_trex_v1_dinosaurs_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetDinosaurRequest.ProtoReflect.Descriptor instead.
func (*GetDinosaurRequest) Descriptor() ([]byte, []int) {
	return file_rh_trex_v1_dinosaurs_proto_rawDescGZIP(), []int{2}
}

func (x *GetDinosaurRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

type UpdateDinosaurRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Species       *string                `protobuf:"bytes,2,opt,name=species,proto3,oneof" json:"species,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateDinosaurRequest) Reset() {
	*x = UpdateDinosaurRequest{}
	mi := &file_rh_trex_v1_dinosaurs_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateDinosaurRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateDinosaurRequest) ProtoMessage() {}

func (x *UpdateDinosaurRequest) ProtoReflect() protoreflect.Message {
	mi := &file_rh_trex_v1_dinosaurs_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateDinosaurRequest.ProtoReflect.Descriptor instead.
func (*UpdateDinosaurRequest) Descriptor() ([]byte, []int) {
	return file_rh_trex_v1_dinosaurs_proto_rawDescGZIP(), []int{3}
}

func (x *UpdateDinosaurRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *UpdateDinosaurRequest) GetSpecies() string {
	if x != nil && x.Species != nil {
		return *x.Species
	}
	return ""
}

type DeleteDinosaurRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteDinosaurRequest) Reset() {
	*x = DeleteDinosaurRequest{}
	mi := &file_rh_trex_v1_dinosaurs_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteDinosaurRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteDinosaurRequest) ProtoMessage() {}

func (x *DeleteDinosaurRequest) ProtoReflect() protoreflect.Message {
	mi := &file_rh_trex_v1_dinosaurs_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteDinosaurRequest.ProtoReflect.Descriptor instead.
func (*DeleteDinosaurRequest) Descriptor() ([]byte, []int) {
	return file_rh_trex_v1_dinosaurs_proto_rawDescGZIP(), []int{4}
}

func (x *DeleteDinosaurRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

type ListDinosaursRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Page          int32                  `protobuf:"varint,1,opt,name=page,proto3" json:"page,omitempty"`
	Size          int32                  `protobuf:"varint,2,opt,name=size,proto3" json:"size,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListDinosaursRequest) Reset() {
	*x = ListDinosaursRequest{}
	mi := &file_rh_trex_v1_dinosaurs_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListDinosaursRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListDinosaursRequest) ProtoMessage() {}

func (x *ListDinosaursRequest) ProtoReflect() protoreflect.Message {
	mi := &file_rh_trex_v1_dinosaurs_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListDinosaursRequest.ProtoReflect.Descriptor instead.
func (*ListDinosaursRequest) Descriptor() ([]byte, []int) {
	return file_rh_trex_v1_dinosaurs_proto_rawDescGZIP(), []int{5}
}

func (x *ListDinosaursRequest) GetPage() int32 {
	if x != nil {
		return x.Page
	}
	return 0
}

func (x *ListDinosaursRequest) GetSize() int32 {
	if x != nil {
		return x.Size
	}
	return 0
}

type ListDinosaursResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Items         []*Dinosaur            `protobuf:"bytes,1,rep,name=items,proto3" json:"items,omitempty"`
	Metadata      *ListMeta              `protobuf:"bytes,2,opt,name=metadata,proto3" json:"metadata,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListDinosaursResponse) Reset() {
	*x = ListDinosaursResponse{}
	mi := &file_rh_trex_v1_dinosaurs_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListDinosaursResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListDinosaursResponse) ProtoMessage() {}

func (x *ListDinosaursResponse) ProtoReflect() protoreflect.Message {
	mi := &file_rh_trex_v1_dinosaurs_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListDinosaursResponse.ProtoReflect.Descriptor instead.
func (*ListDinosaursResponse) Descriptor() ([]byte, []int) {
	return file_rh_trex_v1_dinosaurs_proto_rawDescGZIP(), []int{6}
}

func (x *ListDinosaursResponse) GetItems() []*Dinosaur {
	if x != nil {
		return x.Items
	}
	return nil
}

func (x *ListDinosaursResponse) GetMetadata() *ListMeta {
	if x != nil {
		return x.Metadata
	}
	return nil
}

type DeleteDinosaurResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteDinosaurResponse) Reset() {
	*x = DeleteDinosaurResponse{}
	mi := &file_rh_trex_v1_dinosaurs_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteDinosaurResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteDinosaurResponse) ProtoMessage() {}

func (x *DeleteDinosaurResponse) ProtoReflect() protoreflect.Message {
	mi := &file_rh_trex_v1_dinosaurs_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteDinosaurResponse.ProtoReflect.Descriptor instead.
func (*DeleteDinosaurResponse) Descriptor() ([]byte, []int) {
	return file_rh_trex_v1_dinosaurs_proto_rawDescGZIP(), []int{7}
}

type WatchDinosaursRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *WatchDinosaursRequest) Reset() {
	*x = WatchDinosaursRequest{}
	mi := &file_rh_trex_v1_dinosaurs_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *WatchDinosaursRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*WatchDinosaursRequest) ProtoMessage() {}

func (x *WatchDinosaursRequest) ProtoReflect() protoreflect.Message {
	mi := &file_rh_trex_v1_dinosaurs_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use WatchDinosaursRequest.ProtoReflect.Descriptor instead.
func (*WatchDinosaursRequest) Descriptor() ([]byte, []int) {
	return file_rh_trex_v1_dinosaurs_proto_rawDescGZIP(), []int{8}
}

type DinosaurWatchEvent struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Type          EventType              `protobuf:"varint,1,opt,name=type,proto3,enum=rh_trex.v1.EventType" json:"type,omitempty"`
	Dinosaur      *Dinosaur              `protobuf:"bytes,2,opt,name=dinosaur,proto3" json:"dinosaur,omitempty"`
	ResourceId    string                 `protobuf:"bytes,3,opt,name=resource_id,json=resourceId,proto3" json:"resource_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DinosaurWatchEvent) Reset() {
	*x = DinosaurWatchEvent{}
	mi := &file_rh_trex_v1_dinosaurs_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DinosaurWatchEvent) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DinosaurWatchEvent) ProtoMessage() {}

func (x *DinosaurWatchEvent) ProtoReflect() protoreflect.Message {
	mi := &file_rh_trex_v1_dinosaurs_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DinosaurWatchEvent.ProtoReflect.Descriptor instead.
func (*DinosaurWatchEvent) Descriptor() ([]byte, []int) {
	return file_rh_trex_v1_dinosaurs_proto_rawDescGZIP(), []int{9}
}

func (x *DinosaurWatchEvent) GetType() EventType {
	if x != nil {
		return x.Type
	}
	return EventType_EVENT_TYPE_UNSPECIFIED
}

func (x *DinosaurWatchEvent) GetDinosaur() *Dinosaur {
	if x != nil {
		return x.Dinosaur
	}
	return nil
}

func (x *DinosaurWatchEvent) GetResourceId() string {
	if x != nil {
		return x.ResourceId
	}
	return ""
}

var File_rh_trex_v1_dinosaurs_proto protoreflect.FileDescriptor

const file_rh_trex_v1_dinosaurs_proto_rawDesc = "" +
	"\n" +
	"\x1arh_trex/v1/dinosaurs.proto\x12\n" +
	"rh_trex.v1\x1a\x17rh_trex/v1/common.proto\"]\n" +
	"\bDinosaur\x127\n" +
	"\bmetadata\x18\x01 \x01(\v2\x1b.rh_trex.v1.ObjectReferenceR\bmetadata\x12\x18\n" +
	"\aspecies\x18\x02 \x01(\tR\aspecies\"1\n" +
	"\x15CreateDinosaurRequest\x12\x18\n" +
	"\aspecies\x18\x01 \x01(\tR\aspecies\"$\n" +
	"\x12GetDinosaurRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\"R\n" +
	"\x15UpdateDinosaurRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x1d\n" +
	"\aspecies\x18\x02 \x01(\tH\x00R\aspecies\x88\x01\x01B\n" +
	"\n" +
	"\b_species\"'\n" +
	"\x15DeleteDinosaurRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\">\n" +
	"\x14ListDinosaursRequest\x12\x12\n" +
	"\x04page\x18\x01 \x01(\x05R\x04page\x12\x12\n" +
	"\x04size\x18\x02 \x01(\x05R\x04size\"u\n" +
	"\x15ListDinosaursResponse\x12*\n" +
	"\x05items\x18\x01 \x03(\v2\x14.rh_trex.v1.DinosaurR\x05items\x120\n" +
	"\bmetadata\x18\x02 \x01(\v2\x14.rh_trex.v1.ListMetaR\bmetadata\"\x18\n" +
	"\x16DeleteDinosaurResponse\"\x17\n" +
	"\x15WatchDinosaursRequest\"\x92\x01\n" +
	"\x12DinosaurWatchEvent\x12)\n" +
	"\x04type\x18\x01 \x01(\x0e2\x15.rh_trex.v1.EventTypeR\x04type\x120\n" +
	"\bdinosaur\x18\x02 \x01(\v2\x14.rh_trex.v1.DinosaurR\bdinosaur\x12\x1f\n" +
	"\vresource_id\x18\x03 \x01(\tR\n" +
	"resourceId2\xf2\x03\n" +
	"\x0fDinosaurService\x12C\n" +
	"\vGetDinosaur\x12\x1e.rh_trex.v1.GetDinosaurRequest\x1a\x14.rh_trex.v1.Dinosaur\x12I\n" +
	"\x0eCreateDinosaur\x12!.rh_trex.v1.CreateDinosaurRequest\x1a\x14.rh_trex.v1.Dinosaur\x12I\n" +
	"\x0eUpdateDinosaur\x12!.rh_trex.v1.UpdateDinosaurRequest\x1a\x14.rh_trex.v1.Dinosaur\x12W\n" +
	"\x0eDeleteDinosaur\x12!.rh_trex.v1.DeleteDinosaurRequest\x1a\".rh_trex.v1.DeleteDinosaurResponse\x12T\n" +
	"\rListDinosaurs\x12 .rh_trex.v1.ListDinosaursRequest\x1a!.rh_trex.v1.ListDinosaursResponse\x12U\n" +
	"\x0eWatchDinosaurs\x12!.rh_trex.v1.WatchDinosaursRequest\x1a\x1e.rh_trex.v1.DinosaurWatchEvent0\x01BaZ_github.com/openshift-online/rh-trex-ai/components/api-server/pkg/api/grpc/rh_trex/v1;rh_trex_v1b\x06proto3"

var (
	file_rh_trex_v1_dinosaurs_proto_rawDescOnce sync.Once
	file_rh_trex_v1_dinosaurs_proto_rawDescData []byte
)

func file_rh_trex_v1_dinosaurs_proto_rawDescGZIP() []byte {
	file_rh_trex_v1_dinosaurs_proto_rawDescOnce.Do(func() {
		file_rh_trex_v1_dinosaurs_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_rh_trex_v1_dinosaurs_proto_rawDesc), len(file_rh_trex_v1_dinosaurs_proto_rawDesc)))
	})
	return file_rh_trex_v1_dinosaurs_proto_rawDescData
}

var file_rh_trex_v1_dinosaurs_proto_msgTypes = make([]protoimpl.MessageInfo, 10)
var file_rh_trex_v1_dinosaurs_proto_goTypes = []any{
	(*Dinosaur)(nil),               // 0: rh_trex.v1.Dinosaur
	(*CreateDinosaurRequest)(nil),  // 1: rh_trex.v1.CreateDinosaurRequest
	(*GetDinosaurRequest)(nil),     // 2: rh_trex.v1.GetDinosaurRequest
	(*UpdateDinosaurRequest)(nil),  // 3: rh_trex.v1.UpdateDinosaurRequest
	(*DeleteDinosaurRequest)(nil),  // 4: rh_trex.v1.DeleteDinosaurRequest
	(*ListDinosaursRequest)(nil),   // 5: rh_trex.v1.ListDinosaursRequest
	(*ListDinosaursResponse)(nil),  // 6: rh_trex.v1.ListDinosaursResponse
	(*DeleteDinosaurResponse)(nil), // 7: rh_trex.v1.DeleteDinosaurResponse
	(*WatchDinosaursRequest)(nil),  // 8: rh_trex.v1.WatchDinosaursRequest
	(*DinosaurWatchEvent)(nil),     // 9: rh_trex.v1.DinosaurWatchEvent
	(*ObjectReference)(nil),        // 10: rh_trex.v1.ObjectReference
	(*ListMeta)(nil),               // 11: rh_trex.v1.ListMeta
	(EventType)(0),                 // 12: rh_trex.v1.EventType
}
var file_rh_trex_v1_dinosaurs_proto_depIdxs = []int32{
	10, // 0: rh_trex.v1.Dinosaur.metadata:type_name -> rh_trex.v1.ObjectReference
	0,  // 1: rh_trex.v1.ListDinosaursResponse.items:type_name -> rh_trex.v1.Dinosaur
	11, // 2: rh_trex.v1.ListDinosaursResponse.metadata:type_name -> rh_trex.v1.ListMeta
	12, // 3: rh_trex.v1.DinosaurWatchEvent.type:type_name -> rh_trex.v1.EventType
	0,  // 4: rh_trex.v1.DinosaurWatchEvent.dinosaur:type_name -> rh_trex.v1.Dinosaur
	2,  // 5: rh_trex.v1.DinosaurService.GetDinosaur:input_type -> rh_trex.v1.GetDinosaurRequest
	1,  // 6: rh_trex.v1.DinosaurService.CreateDinosaur:input_type -> rh_trex.v1.CreateDinosaurRequest
	3,  // 7: rh_trex.v1.DinosaurService.UpdateDinosaur:input_type -> rh_trex.v1.UpdateDinosaurRequest
	4,  // 8: rh_trex.v1.DinosaurService.DeleteDinosaur:input_type -> rh_trex.v1.DeleteDinosaurRequest
	5,  // 9: rh_trex.v1.DinosaurService.ListDinosaurs:input_type -> rh_trex.v1.ListDinosaursRequest
	8,  // 10: rh_trex.v1.DinosaurService.WatchDinosaurs:input_type -> rh_trex.v1.WatchDinosaursRequest
	0,  // 11: rh_trex.v1.DinosaurService.GetDinosaur:output_type -> rh_trex.v1.Dinosaur
	0,  // 12: rh_trex.v1.DinosaurService.CreateDinosaur:output_type -> rh_trex.v1.Dinosaur
	0,  // 13: rh_trex.v1.DinosaurService.UpdateDinosaur:output_type -> rh_trex.v1.Dinosaur
	7,  // 14: rh_trex.v1.DinosaurService.DeleteDinosaur:output_type -> rh_trex.v1.DeleteDinosaurResponse
	6,  // 15: rh_trex.v1.DinosaurService.ListDinosaurs:output_type -> rh_trex.v1.ListDinosaursResponse
	9,  // 16: rh_trex.v1.DinosaurService.WatchDinosaurs:output_type -> rh_trex.v1.DinosaurWatchEvent
	11, // [11:17] is the sub-list for method output_type
	5,  // [5:11] is the sub-list for method input_type
	5,  // [5:5] is the sub-list for extension type_name
	5,  // [5:5] is the sub-list for extension extendee
	0,  // [0:5] is the sub-list for field type_name
}

func init() { file_rh_trex_v1_dinosaurs_proto_init() }
func file_rh_trex_v1_dinosaurs_proto_init() {
	if File_rh_trex_v1_dinosaurs_proto != nil {
		return
	}
	file_rh_trex_v1_common_proto_init()
	file_rh_trex_v1_dinosaurs_proto_msgTypes[3].OneofWrappers = []any{}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_rh_trex_v1_dinosaurs_proto_rawDesc), len(file_rh_trex_v1_dinosaurs_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   10,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_rh_trex_v1_dinosaurs_proto_goTypes,
		DependencyIndexes: file_rh_trex_v1_dinosaurs_proto_depIdxs,
		MessageInfos:      file_rh_trex_v1_dinosaurs_proto_msgTypes,
	}.Build()
	File_rh_trex_v1_dinosaurs_proto = out.File
	file_rh_trex_v1_dinosaurs_proto_goTypes = nil
	file_rh_trex_v1_dinosaurs_proto_depIdxs = nil
}
