// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.1
// - protoc             (unknown)
// source: rh_trex/v1/dinosaurs.proto

package rh_trex_v1

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	DinosaurService_GetDinosaur_FullMethodName    = "/rh_trex.v1.DinosaurService/GetDinosaur"
	DinosaurService_CreateDinosaur_FullMethodName = "/rh_trex.v1.DinosaurService/CreateDinosaur"
	DinosaurService_UpdateDinosaur_FullMethodName = "/rh_trex.v1.DinosaurService/UpdateDinosaur"
	DinosaurService_DeleteDinosaur_FullMethodName = "/rh_trex.v1.DinosaurService/DeleteDinosaur"
	DinosaurService_ListDinosaurs_FullMethodName  = "/rh_trex.v1.DinosaurService/ListDinosaurs"
	DinosaurService_WatchDinosaurs_FullMethodName = "/rh_trex.v1.DinosaurService/WatchDinosaurs"
)

// DinosaurServiceClient is the client API for DinosaurService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type DinosaurServiceClient interface {
	GetDinosaur(ctx context.Context, in *GetDinosaurRequest, opts ...grpc.CallOption) (*Dinosaur, error)
	CreateDinosaur(ctx context.Context, in *CreateDinosaurRequest, opts ...grpc.CallOption) (*Dinosaur, error)
	UpdateDinosaur(ctx context.Context, in *UpdateDinosaurRequest, opts ...grpc.CallOption) (*Dinosaur, error)
	DeleteDinosaur(ctx context.Context, in *DeleteDinosaurRequest, opts ...grpc.CallOption) (*DeleteDinosaurResponse, error)
	ListDinosaurs(ctx context.Context, in *ListDinosaursRequest, opts ...grpc.CallOption) (*ListDinosaursResponse, error)
	WatchDinosaurs(ctx context.Context, in *WatchDinosaursRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[DinosaurWatchEvent], error)
}

type dinosaurServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewDinosaurServiceClient(cc grpc.ClientConnInterface) DinosaurServiceClient {
	return &dinosaurServiceClient{cc}
}

func (c *dinosaurServiceClient) GetDinosaur(ctx context.Context, in *GetDinosaurRequest, opts ...grpc.CallOption) (*Dinosaur, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(Dinosaur)
	err := c.cc.Invoke(ctx, DinosaurService_GetDinosaur_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *dinosaurServiceClient) CreateDinosaur(ctx context.Context, in *CreateDinosaurRequest, opts ...grpc.CallOption) (*Dinosaur, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(Dinosaur)
	err := c.cc.Invoke(ctx, DinosaurService_CreateDinosaur_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *dinosaurServiceClient) UpdateDinosaur(ctx context.Context, in *UpdateDinosaurRequest, opts ...grpc.CallOption) (*Dinosaur, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(Dinosaur)
	err := c.cc.Invoke(ctx, DinosaurService_UpdateDinosaur_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *dinosaurServiceClient) DeleteDinosaur(ctx context.Context, in *DeleteDinosaurRequest, opts ...grpc.CallOption) (*DeleteDinosaurResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(DeleteDinosaurResponse)
	err := c.cc.Invoke(ctx, DinosaurService_DeleteDinosaur_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *dinosaurServiceClient) ListDinosaurs(ctx context.Context, in *ListDinosaursRequest, opts ...grpc.CallOption) (*ListDinosaursResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ListDinosaursResponse)
	err := c.cc.Invoke(ctx, DinosaurService_ListDinosaurs_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *dinosaurServiceClient) WatchDinosaurs(ctx context.Context, in *WatchDinosaursRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[DinosaurWatchEvent], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &DinosaurService_ServiceDesc.Streams[0], DinosaurService_WatchDinosaurs_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[WatchDinosaursRequest, DinosaurWatchEvent]{ClientStream: stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type DinosaurService_WatchDinosaursClient = grpc.ServerStreamingClient[DinosaurWatchEvent]

// DinosaurServiceServer is the server API for DinosaurService service.
// All implementations must embed UnimplementedDinosaurServiceServer
// for forward compatibility.
type DinosaurServiceServer interface {
	GetDinosaur(context.Context, *GetDinosaurRequest) (*Dinosaur, error)
	CreateDinosaur(context.Context, *CreateDinosaurRequest) (*Dinosaur, error)
	UpdateDinosaur(context.Context, *UpdateDinosaurRequest) (*Dinosaur, error)
	DeleteDinosaur(context.Context, *DeleteDinosaurRequest) (*DeleteDinosaurResponse, error)
	ListDinosaurs(context.Context, *ListDinosaursRequest) (*ListDinosaursResponse, error)
	WatchDinosaurs(*WatchDinosaursRequest, grpc.ServerStreamingServer[DinosaurWatchEvent]) error
	mustEmbedUnimplementedDinosaurServiceServer()
}

// UnimplementedDinosaurServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedDinosaurServiceServer struct{}

func (UnimplementedDinosaurServiceServer) GetDinosaur(context.Context, *GetDinosaurRequest) (*Dinosaur, error) {
	return nil, status.Error(codes.Unimplemented, "method GetDinosaur not implemented")
}
func (UnimplementedDinosaurServiceServer) CreateDinosaur(context.Context, *CreateDinosaurRequest) (*Dinosaur, error) {
	return nil, status.Error(codes.Unimplemented, "method CreateDinosaur not implemented")
}
func (UnimplementedDinosaurServiceServer) UpdateDinosaur(context.Context, *UpdateDinosaurRequest) (*Dinosaur, error) {
	return nil, status.Error(codes.Unimplemented, "method UpdateDinosaur not implemented")
}
func (UnimplementedDinosaurServiceServer) DeleteDinosaur(context.Context, *DeleteDinosaurRequest) (*DeleteDinosaurResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method DeleteDinosaur not implemented")
}
func (UnimplementedDinosaurServiceServer) ListDinosaurs(context.Context, *ListDinosaursRequest) (*ListDinosaursResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ListDinosaurs not implemented")
}
func (UnimplementedDinosaurServiceServer) WatchDinosaurs(*WatchDinosaursRequest, grpc.ServerStreamingServer[DinosaurWatchEvent]) error {
	return status.Error(codes.Unimplemented, "method WatchDinosaurs not implemented")
}
func (UnimplementedDinosaurServiceServer) mustEmbedUnimplementedDinosaurServiceServer() {}
func (UnimplementedDinosaurServiceServer) testEmbeddedByValue()                         {}

// UnsafeDinosaurServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to DinosaurServiceServer will
// result in compilation errors.
type UnsafeDinosaurServiceServer interface {
	mustEmbedUnimplementedDinosaurServiceServer()
}

func RegisterDinosaurServiceServer(s grpc.ServiceRegistrar, srv DinosaurServiceServer) {
	// If the following call panics, it indicates UnimplementedDinosaurServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&DinosaurService_ServiceDesc, srv)
}

func _DinosaurService_GetDinosaur_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetDinosaurRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DinosaurServiceServer).GetDinosaur(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: DinosaurService_GetDinosaur_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DinosaurServiceServer).GetDinosaur(ctx, req.(*GetDinosaurRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _DinosaurService_CreateDinosaur_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateDinosaurRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DinosaurServiceServer).CreateDinosaur(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: DinosaurService_CreateDinosaur_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DinosaurServiceServer).CreateDinosaur(ctx, req.(*CreateDinosaurRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _DinosaurService_UpdateDinosaur_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UpdateDinosaurRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DinosaurServiceServer).UpdateDinosaur(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: DinosaurService_UpdateDinosaur_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DinosaurServiceServer).UpdateDinosaur(ctx, req.(*UpdateDinosaurRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _DinosaurService_DeleteDinosaur_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DeleteDinosaurRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DinosaurServiceServer).DeleteDinosaur(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: DinosaurService_DeleteDinosaur_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DinosaurServiceServer).DeleteDinosaur(ctx, req.(*DeleteDinosaurRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _DinosaurService_ListDinosaurs_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListDinosaursRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DinosaurServiceServer).ListDinosaurs(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: DinosaurService_ListDinosaurs_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DinosaurServiceServer).ListDinosaurs(ctx, req.(*ListDinosaursRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _DinosaurService_WatchDinosaurs_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(WatchDinosaursRequest)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(DinosaurServiceServer).WatchDinosaurs(m, &grpc.GenericServerStream[WatchDinosaursRequest, DinosaurWatchEvent]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type DinosaurService_WatchDinosaursServer = grpc.ServerStreamingServer[DinosaurWatchEvent]

// DinosaurService_ServiceDesc is the grpc.ServiceDesc for DinosaurService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var DinosaurService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "rh_trex.v1.DinosaurService",
	HandlerType: (*DinosaurServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetDinosaur",
			Handler:    _DinosaurService_GetDinosaur_Handler,
		},
		{
			MethodName: "CreateDinosaur",
			Handler:    _DinosaurService_CreateDinosaur_Handler,
		},
		{
			MethodName: "UpdateDinosaur",
			Handler:    _DinosaurService_UpdateDinosaur_Handler,
		},
		{
			MethodName: "DeleteDinosaur",
			Handler:    _DinosaurService_DeleteDinosaur_Handler,
		},
		{
			MethodName: "ListDinosaurs",
			Handler:    _DinosaurService_ListDinosaurs_Handler,
		},
	},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "WatchDinosaurs",
			Handler:       _DinosaurService_WatchDinosaurs_Handler,
			ServerStreams: true,
		},
	},
	Metadata: "rh_trex/v1/dinosaurs.proto",
}
