// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.12
// 	protoc        (unknown)
// source: rh_trex/v1/fossils.proto

package rh_trex_v1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Fossil struct {
	state             protoimpl.MessageState `protogen:"open.v1"`
	Metadata          *ObjectReference       `protobuf:"bytes,1,opt,name=metadata,proto3" json:"metadata,omitempty"`
	DiscoveryLocation string                 `protobuf:"bytes,2,opt,name=discovery_location,json=discoveryLocation,proto3" json:"discovery_location,omitempty"`
	EstimatedAge      *int32                 `protobuf:"varint,3,opt,name=estimated_age,json=estimatedAge,proto3,oneof" json:"estimated_age,omitempty"`
	FossilType        *string                `protobuf:"bytes,4,opt,name=fossil_type,json=fossilType,proto3,oneof" json:"fossil_type,omitempty"`
	ExcavatorName     *string                `protobuf:"bytes,5,opt,name=excavator_name,json=excavatorName,proto3,oneof" json:"excavator_name,omitempty"`
	unknownFields     protoimpl.UnknownFields
	sizeCache         protoimpl.SizeCache
}

func (x *Fossil) Reset() {
	*x = Fossil{}
	mi := &file_rh_trex_v1_fossils_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Fossil) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Fossil) ProtoMessage() {}

func (x *Fossil) ProtoReflect() protoreflect.Message {
	mi := &file_rh_trex_v1_fossils_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Fossil.ProtoReflect.Descriptor instead.
func (*Fossil) Descriptor() ([]byte, []int) {
	return file_rh_trex_v1_fossils_proto_rawDescGZIP(), []int{0}
}

func (x *Fossil) GetMetadata() *ObjectReference {
	if x != nil {
		return x.Metadata
	}
	return nil
}

func (x *Fossil) GetDiscoveryLocation() string {
	if x != nil {
		return x.DiscoveryLocation
	}
	return ""
}

func (x *Fossil) GetEstimatedAge() int32 {
	if x != nil && x.EstimatedAge != nil {
		return *x.EstimatedAge
	}
	return 0
}

func (x *Fossil) GetFossilType() string {
	if x != nil && x.FossilType != nil {
		return *x.FossilType
	}
	return ""
}

func (x *Fossil) GetExcavatorName() string {
	if x != nil && x.ExcavatorName != nil {
		return *x.ExcavatorName
	}
	return ""
}

type CreateFossilRequest struct {
	state             protoimpl.MessageState `protogen:"open.v1"`
	DiscoveryLocation string                 `protobuf:"bytes,1,opt,name=discovery_location,json=discoveryLocation,proto3" json:"discovery_location,omitempty"`
	EstimatedAge      *int32                 `protobuf:"varint,2,opt,name=estimated_age,json=estimatedAge,proto3,oneof" json:"estimated_age,omitempty"`
	FossilType        *string                `protobuf:"bytes,3,opt,name=fossil_type,json=fossilType,proto3,oneof" json:"fossil_type,omitempty"`
	ExcavatorName     *string                `protobuf:"bytes,4,opt,name=excavator_name,json=excavatorName,proto3,oneof" json:"excavator_name,omitempty"`
	unknownFields     protoimpl.UnknownFields
	sizeCache         protoimpl.SizeCache
}

func (x *CreateFossilRequest) Reset() {
	*x = CreateFossilRequest{}
	mi := &file_rh_trex_v1_fossils_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateFossilRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateFossilRequest) ProtoMessage() {}

func (x *CreateFossilRequest) ProtoReflect() protoreflect.Message {
	mi := &file_rh_trex_v1_fossils_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateFossilRequest.ProtoReflect.Descriptor instead.
func (*CreateFossilRequest) Descriptor() ([]byte, []int) {
	return file_rh_trex_v1_fossils_proto_rawDescGZIP(), []int{1}
}

func (x *CreateFossilRequest) GetDiscoveryLocation() string {
	if x != nil {
		return x.DiscoveryLocation
	}
	return ""
}

func (x *CreateFossilRequest) GetEstimatedAge() int32 {
	if x != nil && x.EstimatedAge != nil {
		return *x.EstimatedAge
	}
	return 0
}

func (x *CreateFossilRequest) GetFossilType() string {
	if x != nil && x.FossilType != nil {
		return *x.FossilType
	}
	return ""
}

func (x *CreateFossilRequest) GetExcavatorName() string {
	if x != nil && x.ExcavatorName != nil {
		return *x.ExcavatorName
	}
	return ""
}

type GetFossilRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetFossilRequest) Reset() {
	*x = GetFossilRequest{}
	mi := &file_rh_trex_v1_fossils_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetFossilRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetFossilRequest) ProtoMessage() {}

func (x *GetFossilRequest) ProtoReflect() protoreflect.Message {
	mi := &file_rh_trex_v1_fossils_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetFossilRequest.ProtoReflect.Descriptor instead.
func (*GetFossilRequest) Descriptor() ([]byte, []int) {
	return file_rh_trex_v1_fossils_proto_rawDescGZIP(), []int{2}
}

func (x *GetFossilRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

type UpdateFossilRequest struct {
	state             protoimpl.MessageState `protogen:"open.v1"`
	Id                string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	DiscoveryLocation *string                `protobuf:"bytes,2,opt,name=discovery_location,json=discoveryLocation,proto3,oneof" json:"discovery_location,omitempty"`
	EstimatedAge      *int32                 `protobuf:"varint,3,opt,name=estimated_age,json=estimatedAge,proto3,oneof" json:"estimated_age,omitempty"`
	FossilType        *string                `protobuf:"bytes,4,opt,name=fossil_type,json=fossilType,proto3,oneof" json:"fossil_type,omitempty"`
	ExcavatorName     *string                `protobuf:"bytes,5,opt,name=excavator_name,json=excavatorName,proto3,oneof" json:"excavator_name,omitempty"`
	unknownFields     protoimpl.UnknownFields
	sizeCache         protoimpl.SizeCache
}

func (x *UpdateFossilRequest) Reset() {
	*x = UpdateFossilRequest{}
	mi := &file_rh_trex_v1_fossils_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateFossilRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateFossilRequest) ProtoMessage() {}

func (x *UpdateFossilRequest) ProtoReflect() protoreflect.Message {
	mi := &file_rh_trex_v1_fossils_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateFossilRequest.ProtoReflect.Descriptor instead.
func (*UpdateFossilRequest) Descriptor() ([]byte, []int) {
	return file_rh_trex_v1_fossils_proto_rawDescGZIP(), []int{3}
}

func (x *UpdateFossilRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *UpdateFossilRequest) GetDiscoveryLocation() string {
	if x != nil && x.DiscoveryLocation != nil {
		return *x.DiscoveryLocation
	}
	return ""
}

func (x *UpdateFossilRequest) GetEstimatedAge() int32 {
	if x != nil && x.EstimatedAge != nil {
		return *x.EstimatedAge
	}
	return 0
}

func (x *UpdateFossilRequest) GetFossilType() string {
	if x != nil && x.FossilType != nil {
		return *x.FossilType
	}
	return ""
}

func (x *UpdateFossilRequest) GetExcavatorName() string {
	if x != nil && x.ExcavatorName != nil {
		return *x.ExcavatorName
	}
	return ""
}

type DeleteFossilRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteFossilRequest) Reset() {
	*x = DeleteFossilRequest{}
	mi := &file_rh_trex_v1_fossils_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteFossilRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteFossilRequest) ProtoMessage() {}

func (x *DeleteFossilRequest) ProtoReflect() protoreflect.Message {
	mi := &file_rh_trex_v1_fossils_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteFossilRequest.ProtoReflect.Descriptor instead.
func (*DeleteFossilRequest) Descriptor() ([]byte, []int) {
	return file_rh_trex_v1_fossils_proto_rawDescGZIP(), []int{4}
}

func (x *DeleteFossilRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

type ListFossilsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Page          int32                  `protobuf:"varint,1,opt,name=page,proto3" json:"page,omitempty"`
	Size          int32                  `protobuf:"varint,2,opt,name=size,proto3" json:"size,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListFossilsRequest) Reset() {
	*x = ListFossilsRequest{}
	mi := &file_rh_trex_v1_fossils_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListFossilsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListFossilsRequest) ProtoMessage() {}

func (x *ListFossilsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_rh_trex_v1_fossils_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListFossilsRequest.ProtoReflect.Descriptor instead.
func (*ListFossilsRequest) Descriptor() ([]byte, []int) {
	return file_rh_trex_v1_fossils_proto_rawDescGZIP(), []int{5}
}

func (x *ListFossilsRequest) GetPage() int32 {
	if x != nil {
		return x.Page
	}
	return 0
}

func (x *ListFossilsRequest) GetSize() int32 {
	if x != nil {
		return x.Size
	}
	return 0
}

type ListFossilsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Items         []*Fossil              `protobuf:"bytes,1,rep,name=items,proto3" json:"items,omitempty"`
	Metadata      *ListMeta              `protobuf:"bytes,2,opt,name=metadata,proto3" json:"metadata,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListFossilsResponse) Reset() {
	*x = ListFossilsResponse{}
	mi := &file_rh_trex_v1_fossils_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListFossilsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListFossilsResponse) ProtoMessage() {}

func (x *ListFossilsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_rh_trex_v1_fossils_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListFossilsResponse.ProtoReflect.Descriptor instead.
func (*ListFossilsResponse) Descriptor() ([]byte, []int) {
	return file_rh_trex_v1_fossils_proto_rawDescGZIP(), []int{6}
}

func (x *ListFossilsResponse) GetItems() []*Fossil {
	if x != nil {
		return x.Items
	}
	return nil
}

func (x *ListFossilsResponse) GetMetadata() *ListMeta {
	if x != nil {
		return x.Metadata
	}
	return nil
}

type DeleteFossilResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteFossilResponse) Reset() {
	*x = DeleteFossilResponse{}
	mi := &file_rh_trex_v1_fossils_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteFossilResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteFossilResponse) ProtoMessage() {}

func (x *DeleteFossilResponse) ProtoReflect() protoreflect.Message {
	mi := &file_rh_trex_v1_fossils_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteFossilResponse.ProtoReflect.Descriptor instead.
func (*DeleteFossilResponse) Descriptor() ([]byte, []int) {
	return file_rh_trex_v1_fossils_proto_rawDescGZIP(), []int{7}
}

type WatchFossilsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *WatchFossilsRequest) Reset() {
	*x = WatchFossilsRequest{}
	mi := &file_rh_trex_v1_fossils_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *WatchFossilsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*WatchFossilsRequest) ProtoMessage() {}

func (x *WatchFossilsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_rh_trex_v1_fossils_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use WatchFossilsRequest.ProtoReflect.Descriptor instead.
func (*WatchFossilsRequest) Descriptor() ([]byte, []int) {
	return file_rh_trex_v1_fossils_proto_rawDescGZIP(), []int{8}
}

type FossilWatchEvent struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Type          EventType              `protobuf:"varint,1,opt,name=type,proto3,enum=rh_trex.v1.EventType" json:"type,omitempty"`
	Fossil        *Fossil                `protobuf:"bytes,2,opt,name=fossil,proto3" json:"fossil,omitempty"`
	ResourceId    string                 `protobuf:"bytes,3,opt,name=resource_id,json=resourceId,proto3" json:"resource_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *FossilWatchEvent) Reset() {
	*x = FossilWatchEvent{}
	mi := &file_rh_trex_v1_fossils_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FossilWatchEvent) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FossilWatchEvent) ProtoMessage() {}

func (x *FossilWatchEvent) ProtoReflect() protoreflect.Message {
	mi := &file_rh_trex_v1_fossils_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FossilWatchEvent.ProtoReflect.Descriptor instead.
func (*FossilWatchEvent) Descriptor() ([]byte, []int) {
	return file_rh_trex_v1_fossils_proto_rawDescGZIP(), []int{9}
}

func (x *FossilWatchEvent) GetType() EventType {
	if x != nil {
		return x.Type
	}
	return EventType_EVENT_TYPE_UNSPECIFIED
}

func (x *FossilWatchEvent) GetFossil() *Fossil {
	if x != nil {
		return x.Fossil
	}
	return nil
}

func (x *FossilWatchEvent) GetResourceId() string {
	if x != nil {
		return x.ResourceId
	}
	return ""
}

var File_rh_trex_v1_fossils_proto protoreflect.FileDescriptor

const file_rh_trex_v1_fossils_proto_rawDesc = "" +
	"\n" +
	"\x18rh_trex/v1/fossils.proto\x12\n" +
	"rh_trex.v1\x1a\x17rh_trex/v1/common.proto\"\xa1\x02\n" +
	"\x06Fossil\x127\n" +
	"\bmetadata\x18\x01 \x01(\v2\x1b.rh_trex.v1.ObjectReferenceR\bmetadata\x12-\n" +
	"\x12discovery_location\x18\x02 \x01(\tR\x11discoveryLocation\x12(\n" +
	"\restimated_age\x18\x03 \x01(\x05H\x00R\festimatedAge\x88\x01\x01\x12$\n" +
	"\vfossil_type\x18\x04 \x01(\tH\x01R\n" +
	"fossilType\x88\x01\x01\x12*\n" +
	"\x0eexcavator_name\x18\x05 \x01(\tH\x02R\rexcavatorName\x88\x01\x01B\x10\n" +
	"\x0e_estimated_ageB\x0e\n" +
	"\f_fossil_typeB\x11\n" +
	"\x0f_excavator_name\"\xf5\x01\n" +
	"\x13CreateFossilRequest\x12-\n" +
	"\x12discovery_location\x18\x01 \x01(\tR\x11discoveryLocation\x12(\n" +
	"\restimated_age\x18\x02 \x01(\x05H\x00R\festimatedAge\x88\x01\x01\x12$\n" +
	"\vfossil_type\x18\x03 \x01(\tH\x01R\n" +
	"fossilType\x88\x01\x01\x12*\n" +
	"\x0eexcavator_name\x18\x04 \x01(\tH\x02R\rexcavatorName\x88\x01\x01B\x10\n" +
	"\x0e_estimated_ageB\x0e\n" +
	"\f_fossil_typeB\x11\n" +
	"\x0f_excavator_name\"\"\n" +
	"\x10GetFossilRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\"\xa1\x02\n" +
	"\x13UpdateFossilRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x122\n" +
	"\x12discovery_location\x18\x02 \x01(\tH\x00R\x11discoveryLocation\x88\x01\x01\x12(\n" +
	"\restimated_age\x18\x03 \x01(\x05H\x01R\festimatedAge\x88\x01\x01\x12$\n" +
	"\vfossil_type\x18\x04 \x01(\tH\x02R\n" +
	"fossilType\x88\x01\x01\x12*\n" +
	"\x0eexcavator_name\x18\x05 \x01(\tH\x03R\rexcavatorName\x88\x01\x01B\x15\n" +
	"\x13_discovery_locationB\x10\n" +
	"\x0e_estimated_ageB\x0e\n" +
	"\f_fossil_typeB\x11\n" +
	"\x0f_excavator_name\"%\n" +
	"\x13DeleteFossilRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\"<\n" +
	"\x12ListFossilsRequest\x12\x12\n" +
	"\x04page\x18\x01 \x01(\x05R\x04page\x12\x12\n" +
	"\x04size\x18\x02 \x01(\x05R\x04size\"q\n" +
	"\x13ListFossilsResponse\x12(\n" +
	"\x05items\x18\x01 \x03(\v2\x12.rh_trex.v1.FossilR\x05items\x120\n" +
	"\bmetadata\x18\x02 \x01(\v2\x14.rh_trex.v1.ListMetaR\bmetadata\"\x16\n" +
	"\x14DeleteFossilResponse\"\x15\n" +
	"\x13WatchFossilsRequest\"\x8a\x01\n" +
	"\x10FossilWatchEvent\x12)\n" +
	"\x04type\x18\x01 \x01(\x0e2\x15.rh_trex.v1.EventTypeR\x04type\x12*\n" +
	"\x06fossil\x18\x02 \x01(\v2\x12.rh_trex.v1.FossilR\x06fossil\x12\x1f\n" +
	"\vresource_id\x18\x03 \x01(\tR\n" +
	"resourceId2\xcc\x03\n" +
	"\rFossilService\x12=\n" +
	"\tGetFossil\x12\x1c.rh_trex.v1.GetFossilRequest\x1a\x12.rh_trex.v1.Fossil\x12C\n" +
	"\fCreateFossil\x12\x1f.rh_trex.v1.CreateFossilRequest\x1a\x12.rh_trex.v1.Fossil\x12C\n" +
	"\fUpdateFossil\x12\x1f.rh_trex.v1.UpdateFossilRequest\x1a\x12.rh_trex.v1.Fossil\x12Q\n" +
	"\fDeleteFossil\x12\x1f.rh_trex.v1.DeleteFossilRequest\x1a .rh_trex.v1.DeleteFossilResponse\x12N\n" +
	"\vListFossils\x12\x1e.rh_trex.v1.ListFossilsRequest\x1a\x1f.rh_trex.v1.ListFossilsResponse\x12O\n" +
	"\fWatchFossils\x12\x1f.rh_trex.v1.WatchFossilsRequest\x1a\x1c.rh_trex.v1.FossilWatchEvent0\x01BaZ_github.com/openshift-online/rh-trex-ai/components/api-server/pkg/api/grpc/rh_trex/v1;rh_trex_v1b\x06proto3"

var (
	file_rh_trex_v1_fossils_proto_rawDescOnce sync.Once
	file_rh_trex_v1_fossils_proto_rawDescData []byte
)

func file_rh_trex_v1_fossils_proto_rawDescGZIP() []byte {
	file_rh_trex_v1_fossils_proto_rawDescOnce.Do(func() {
		file_rh_trex_v1_fossils_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_rh_trex_v1_fossils_proto_rawDesc), len(file_rh_trex_v1_fossils_proto_rawDesc)))
	})
	return file_rh_trex_v1_fossils_proto_rawDescData
}

var file_rh_trex_v1_fossils_proto_msgTypes = make([]protoimpl.MessageInfo, 10)
var file_rh_trex_v1_fossils_proto_goTypes = []any{
	(*Fossil)(nil),               // 0: rh_trex.v1.Fossil
	(*CreateFossilRequest)(nil),  // 1: rh_trex.v1.CreateFossilRequest
	(*GetFossilRequest)(nil),     // 2: rh_trex.v1.GetFossilRequest
	(*UpdateFossilRequest)(nil),  // 3: rh_trex.v1.UpdateFossilRequest
	(*DeleteFossilRequest)(nil),  // 4: rh_trex.v1.DeleteFossilRequest
	(*ListFossilsRequest)(nil),   // 5: rh_trex.v1.ListFossilsRequest
	(*ListFossilsResponse)(nil),  // 6: rh_trex.v1.ListFossilsResponse
	(*DeleteFossilResponse)(nil), // 7: rh_trex.v1.DeleteFossilResponse
	(*WatchFossilsRequest)(nil),  // 8: rh_trex.v1.WatchFossilsRequest
	(*FossilWatchEvent)(nil),     // 9: rh_trex.v1.FossilWatchEvent
	(*ObjectReference)(nil),      // 10: rh_trex.v1.ObjectReference
	(*ListMeta)(nil),             // 11: rh_trex.v1.ListMeta
	(EventType)(0),               // 12: rh_trex.v1.EventType
}
var file_rh_trex_v1_fossils_proto_depIdxs = []int32{
	10, // 0: rh_trex.v1.Fossil.metadata:type_name -> rh_trex.v1.ObjectReference
	0,  // 1: rh_trex.v1.ListFossilsResponse.items:type_name -> rh_trex.v1.Fossil
	11, // 2: rh_trex.v1.ListFossilsResponse.metadata:type_name -> rh_trex.v1.ListMeta
	12, // 3: rh_trex.v1.FossilWatchEvent.type:type_name -> rh_trex.v1.EventType
	0,  // 4: rh_trex.v1.FossilWatchEvent.fossil:type_name -> rh_trex.v1.Fossil
	2,  // 5: rh_trex.v1.FossilService.GetFossil:input_type -> rh_trex.v1.GetFossilRequest
	1,  // 6: rh_trex.v1.FossilService.CreateFossil:input_type -> rh_trex.v1.CreateFossilRequest
	3,  // 7: rh_trex.v1.FossilService.UpdateFossil:input_type -> rh_trex.v1.UpdateFossilRequest
	4,  // 8: rh_trex.v1.FossilService.DeleteFossil:input_type -> rh_trex.v1.DeleteFossilRequest
	5,  // 9: rh_trex.v1.FossilService.ListFossils:input_type -> rh_trex.v1.ListFossilsRequest
	8,  // 10: rh_trex.v1.FossilService.WatchFossils:input_type -> rh_trex.v1.WatchFossilsRequest
	0,  // 11: rh_trex.v1.FossilService.GetFossil:output_type -> rh_trex.v1.Fossil
	0,  // 12: rh_trex.v1.FossilService.CreateFossil:output_type -> rh_trex.v1.Fossil
	0,  // 13: rh_trex.v1.FossilService.UpdateFossil:output_type -> rh_trex.v1.Fossil
	7,  // 14: rh_trex.v1.FossilService.DeleteFossil:output_type -> rh_trex.v1.DeleteFossilResponse
	6,  // 15: rh_trex.v1.FossilService.ListFossils:output_type -> rh_trex.v1.ListFossilsResponse
	9,  // 16: rh_trex.v1.FossilService.WatchFossils:output_type -> rh_trex.v1.FossilWatchEvent
	11, // [11:17] is the sub-list for method output_type
	5,  // [5:11] is the sub-list for method input_type
	5,  // [5:5] is the sub-list for extension type_name
	5,  // [5:5] is the sub-list for extension extendee
	0,  // [0:5] is the sub-list for field type_name
}

func init() { file_rh_trex_v1_fossils_proto_init() }
func file_rh_trex_v1_fossils_proto_init() {
	if File_rh_trex_v1_fossils_proto != nil {
		return
	}
	file_rh_trex_v1_common_proto_init()
	file_rh_trex_v1_fossils_proto_msgTypes[0].OneofWrappers = []any{}
	file_rh_trex_v1_fossils_proto_msgTypes[1].OneofWrappers = []any{}
	file_rh_trex_v1_fossils_proto_msgTypes[3].OneofWrappers = []any{}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_rh_trex_v1_fossils_proto_rawDesc), len(file_rh_trex_v1_fossils_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   10,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_rh_trex_v1_fossils_proto_goTypes,
		DependencyIndexes: file_rh_trex_v1_fossils_proto_depIdxs,
		MessageInfos:      file_rh_trex_v1_fossils_proto_msgTypes,
	}.Build()
	File_rh_trex_v1_fossils_proto = out.File
	file_rh_trex_v1_fossils_proto_goTypes = nil
	file_rh_trex_v1_fossils_proto_depIdxs = nil
}
