// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.1
// - protoc             (unknown)
// source: rh_trex/v1/fossils.proto

package rh_trex_v1

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	FossilService_GetFossil_FullMethodName    = "/rh_trex.v1.FossilService/GetFossil"
	FossilService_CreateFossil_FullMethodName = "/rh_trex.v1.FossilService/CreateFossil"
	FossilService_UpdateFossil_FullMethodName = "/rh_trex.v1.FossilService/UpdateFossil"
	FossilService_DeleteFossil_FullMethodName = "/rh_trex.v1.FossilService/DeleteFossil"
	FossilService_ListFossils_FullMethodName  = "/rh_trex.v1.FossilService/ListFossils"
	FossilService_WatchFossils_FullMethodName = "/rh_trex.v1.FossilService/WatchFossils"
)

// FossilServiceClient is the client API for FossilService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type FossilServiceClient interface {
	GetFossil(ctx context.Context, in *GetFossilRequest, opts ...grpc.CallOption) (*Fossil, error)
	CreateFossil(ctx context.Context, in *CreateFossilRequest, opts ...grpc.CallOption) (*Fossil, error)
	UpdateFossil(ctx context.Context, in *UpdateFossilRequest, opts ...grpc.CallOption) (*Fossil, error)
	DeleteFossil(ctx context.Context, in *DeleteFossilRequest, opts ...grpc.CallOption) (*DeleteFossilResponse, error)
	ListFossils(ctx context.Context, in *ListFossilsRequest, opts ...grpc.CallOption) (*ListFossilsResponse, error)
	WatchFossils(ctx context.Context, in *WatchFossilsRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[FossilWatchEvent], error)
}

type fossilServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewFossilServiceClient(cc grpc.ClientConnInterface) FossilServiceClient {
	return &fossilServiceClient{cc}
}

func (c *fossilServiceClient) GetFossil(ctx context.Context, in *GetFossilRequest, opts ...grpc.CallOption) (*Fossil, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(Fossil)
	err := c.cc.Invoke(ctx, FossilService_GetFossil_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *fossilServiceClient) CreateFossil(ctx context.Context, in *CreateFossilRequest, opts ...grpc.CallOption) (*Fossil, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(Fossil)
	err := c.cc.Invoke(ctx, FossilService_CreateFossil_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *fossilServiceClient) UpdateFossil(ctx context.Context, in *UpdateFossilRequest, opts ...grpc.CallOption) (*Fossil, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(Fossil)
	err := c.cc.Invoke(ctx, FossilService_UpdateFossil_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *fossilServiceClient) DeleteFossil(ctx context.Context, in *DeleteFossilRequest, opts ...grpc.CallOption) (*DeleteFossilResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(DeleteFossilResponse)
	err := c.cc.Invoke(ctx, FossilService_DeleteFossil_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *fossilServiceClient) ListFossils(ctx context.Context, in *ListFossilsRequest, opts ...grpc.CallOption) (*ListFossilsResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ListFossilsResponse)
	err := c.cc.Invoke(ctx, FossilService_ListFossils_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *fossilServiceClient) WatchFossils(ctx context.Context, in *WatchFossilsRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[FossilWatchEvent], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &FossilService_ServiceDesc.Streams[0], FossilService_WatchFossils_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[WatchFossilsRequest, FossilWatchEvent]{ClientStream: stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type FossilService_WatchFossilsClient = grpc.ServerStreamingClient[FossilWatchEvent]

// FossilServiceServer is the server API for FossilService service.
// All implementations must embed UnimplementedFossilServiceServer
// for forward compatibility.
type FossilServiceServer interface {
	GetFossil(context.Context, *GetFossilRequest) (*Fossil, error)
	CreateFossil(context.Context, *CreateFossilRequest) (*Fossil, error)
	UpdateFossil(context.Context, *UpdateFossilRequest) (*Fossil, error)
	DeleteFossil(context.Context, *DeleteFossilRequest) (*DeleteFossilResponse, error)
	ListFossils(context.Context, *ListFossilsRequest) (*ListFossilsResponse, error)
	WatchFossils(*WatchFossilsRequest, grpc.ServerStreamingServer[FossilWatchEvent]) error
	mustEmbedUnimplementedFossilServiceServer()
}

// UnimplementedFossilServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedFossilServiceServer struct{}

func (UnimplementedFossilServiceServer) GetFossil(context.Context, *GetFossilRequest) (*Fossil, error) {
	return nil, status.Error(codes.Unimplemented, "method GetFossil not implemented")
}
func (UnimplementedFossilServiceServer) CreateFossil(context.Context, *CreateFossilRequest) (*Fossil, error) {
	return nil, status.Error(codes.Unimplemented, "method CreateFossil not implemented")
}
func (UnimplementedFossilServiceServer) UpdateFossil(context.Context, *UpdateFossilRequest) (*Fossil, error) {
	return nil, status.Error(codes.Unimplemented, "method UpdateFossil not implemented")
}
func (UnimplementedFossilServiceServer) DeleteFossil(context.Context, *DeleteFossilRequest) (*DeleteFossilResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method DeleteFossil not implemented")
}
func (UnimplementedFossilServiceServer) ListFossils(context.Context, *ListFossilsRequest) (*ListFossilsResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ListFossils not implemented")
}
func (UnimplementedFossilServiceServer) WatchFossils(*WatchFossilsRequest, grpc.ServerStreamingServer[FossilWatchEvent]) error {
	return status.Error(codes.Unimplemented, "method WatchFossils not implemented")
}
func (UnimplementedFossilServiceServer) mustEmbedUnimplementedFossilServiceServer() {}
func (UnimplementedFossilServiceServer) testEmbeddedByValue()                       {}

// UnsafeFossilServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to FossilServiceServer will
// result in compilation errors.
type UnsafeFossilServiceServer interface {
	mustEmbedUnimplementedFossilServiceServer()
}

func RegisterFossilServiceServer(s grpc.ServiceRegistrar, srv FossilServiceServer) {
	// If the following call panics, it indicates UnimplementedFossilServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&FossilService_ServiceDesc, srv)
}

func _FossilService_GetFossil_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetFossilRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(FossilServiceServer).GetFossil(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: FossilService_GetFossil_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(FossilServiceServer).GetFossil(ctx, req.(*GetFossilRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _FossilService_CreateFossil_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateFossilRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(FossilServiceServer).CreateFossil(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: FossilService_CreateFossil_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(FossilServiceServer).CreateFossil(ctx, req.(*CreateFossilRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _FossilService_UpdateFossil_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UpdateFossilRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(FossilServiceServer).UpdateFossil(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: FossilService_UpdateFossil_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(FossilServiceServer).UpdateFossil(ctx, req.(*UpdateFossilRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _FossilService_DeleteFossil_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DeleteFossilRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(FossilServiceServer).DeleteFossil(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: FossilService_DeleteFossil_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(FossilServiceServer).DeleteFossil(ctx, req.(*DeleteFossilRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _FossilService_ListFossils_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListFossilsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(FossilServiceServer).ListFossils(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: FossilService_ListFossils_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(FossilServiceServer).ListFossils(ctx, req.(*ListFossilsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _FossilService_WatchFossils_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(WatchFossilsRequest)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(FossilServiceServer).WatchFossils(m, &grpc.GenericServerStream[WatchFossilsRequest, FossilWatchEvent]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type FossilService_WatchFossilsServer = grpc.ServerStreamingServer[FossilWatchEvent]

// FossilService_ServiceDesc is the grpc.ServiceDesc for FossilService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var FossilService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "rh_trex.v1.FossilService",
	HandlerType: (*FossilServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetFossil",
			Handler:    _FossilService_GetFossil_Handler,
		},
		{
			MethodName: "CreateFossil",
			Handler:    _FossilService_CreateFossil_Handler,
		},
		{
			MethodName: "UpdateFossil",
			Handler:    _FossilService_UpdateFossil_Handler,
		},
		{
			MethodName: "DeleteFossil",
			Handler:    _FossilService_DeleteFossil_Handler,
		},
		{
			MethodName: "ListFossils",
			Handler:    _FossilService_ListFossils_Handler,
		},
	},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "WatchFossils",
			Handler:       _FossilService_WatchFossils_Handler,
			ServerStreams: true,
		},
	},
	Metadata: "rh_trex/v1/fossils.proto",
}
