// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.1
// - protoc             (unknown)
// source: rh_trex/v1/scientists.proto

package rh_trex_v1

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	ScientistService_GetScientist_FullMethodName    = "/rh_trex.v1.ScientistService/GetScientist"
	ScientistService_CreateScientist_FullMethodName = "/rh_trex.v1.ScientistService/CreateScientist"
	ScientistService_UpdateScientist_FullMethodName = "/rh_trex.v1.ScientistService/UpdateScientist"
	ScientistService_DeleteScientist_FullMethodName = "/rh_trex.v1.ScientistService/DeleteScientist"
	ScientistService_ListScientists_FullMethodName  = "/rh_trex.v1.ScientistService/ListScientists"
	ScientistService_WatchScientists_FullMethodName = "/rh_trex.v1.ScientistService/WatchScientists"
)

// ScientistServiceClient is the client API for ScientistService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type ScientistServiceClient interface {
	GetScientist(ctx context.Context, in *GetScientistRequest, opts ...grpc.CallOption) (*Scientist, error)
	CreateScientist(ctx context.Context, in *CreateScientistRequest, opts ...grpc.CallOption) (*Scientist, error)
	UpdateScientist(ctx context.Context, in *UpdateScientistRequest, opts ...grpc.CallOption) (*Scientist, error)
	DeleteScientist(ctx context.Context, in *DeleteScientistRequest, opts ...grpc.CallOption) (*DeleteScientistResponse, error)
	ListScientists(ctx context.Context, in *ListScientistsRequest, opts ...grpc.CallOption) (*ListScientistsResponse, error)
	WatchScientists(ctx context.Context, in *WatchScientistsRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[ScientistWatchEvent], error)
}

type scientistServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewScientistServiceClient(cc grpc.ClientConnInterface) ScientistServiceClient {
	return &scientistServiceClient{cc}
}

func (c *scientistServiceClient) GetScientist(ctx context.Context, in *GetScientistRequest, opts ...grpc.CallOption) (*Scientist, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(Scientist)
	err := c.cc.Invoke(ctx, ScientistService_GetScientist_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *scientistServiceClient) CreateScientist(ctx context.Context, in *CreateScientistRequest, opts ...grpc.CallOption) (*Scientist, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(Scientist)
	err := c.cc.Invoke(ctx, ScientistService_CreateScientist_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *scientistServiceClient) UpdateScientist(ctx context.Context, in *UpdateScientistRequest, opts ...grpc.CallOption) (*Scientist, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(Scientist)
	err := c.cc.Invoke(ctx, ScientistService_UpdateScientist_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *scientistServiceClient) DeleteScientist(ctx context.Context, in *DeleteScientistRequest, opts ...grpc.CallOption) (*DeleteScientistResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(DeleteScientistResponse)
	err := c.cc.Invoke(ctx, ScientistService_DeleteScientist_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *scientistServiceClient) ListScientists(ctx context.Context, in *ListScientistsRequest, opts ...grpc.CallOption) (*ListScientistsResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ListScientistsResponse)
	err := c.cc.Invoke(ctx, ScientistService_ListScientists_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *scientistServiceClient) WatchScientists(ctx context.Context, in *WatchScientistsRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[ScientistWatchEvent], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &ScientistService_ServiceDesc.Streams[0], ScientistService_WatchScientists_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[WatchScientistsRequest, ScientistWatchEvent]{ClientStream: stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type ScientistService_WatchScientistsClient = grpc.ServerStreamingClient[ScientistWatchEvent]

// ScientistServiceServer is the server API for ScientistService service.
// All implementations must embed UnimplementedScientistServiceServer
// for forward compatibility.
type ScientistServiceServer interface {
	GetScientist(context.Context, *GetScientistRequest) (*Scientist, error)
	CreateScientist(context.Context, *CreateScientistRequest) (*Scientist, error)
	UpdateScientist(context.Context, *UpdateScientistRequest) (*Scientist, error)
	DeleteScientist(context.Context, *DeleteScientistRequest) (*DeleteScientistResponse, error)
	ListScientists(context.Context, *ListScientistsRequest) (*ListScientistsResponse, error)
	WatchScientists(*WatchScientistsRequest, grpc.ServerStreamingServer[ScientistWatchEvent]) error
	mustEmbedUnimplementedScientistServiceServer()
}

// UnimplementedScientistServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedScientistServiceServer struct{}

func (UnimplementedScientistServiceServer) GetScientist(context.Context, *GetScientistRequest) (*Scientist, error) {
	return nil, status.Error(codes.Unimplemented, "method GetScientist not implemented")
}
func (UnimplementedScientistServiceServer) CreateScientist(context.Context, *CreateScientistRequest) (*Scientist, error) {
	return nil, status.Error(codes.Unimplemented, "method CreateScientist not implemented")
}
func (UnimplementedScientistServiceServer) UpdateScientist(context.Context, *UpdateScientistRequest) (*Scientist, error) {
	return nil, status.Error(codes.Unimplemented, "method UpdateScientist not implemented")
}
func (UnimplementedScientistServiceServer) DeleteScientist(context.Context, *DeleteScientistRequest) (*DeleteScientistResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method DeleteScientist not implemented")
}
func (UnimplementedScientistServiceServer) ListScientists(context.Context, *ListScientistsRequest) (*ListScientistsResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ListScientists not implemented")
}
func (UnimplementedScientistServiceServer) WatchScientists(*WatchScientistsRequest, grpc.ServerStreamingServer[ScientistWatchEvent]) error {
	return status.Error(codes.Unimplemented, "method WatchScientists not implemented")
}
func (UnimplementedScientistServiceServer) mustEmbedUnimplementedScientistServiceServer() {}
func (UnimplementedScientistServiceServer) testEmbeddedByValue()                          {}

// UnsafeScientistServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to ScientistServiceServer will
// result in compilation errors.
type UnsafeScientistServiceServer interface {
	mustEmbedUnimplementedScientistServiceServer()
}

func RegisterScientistServiceServer(s grpc.ServiceRegistrar, srv ScientistServiceServer) {
	// If the following call panics, it indicates UnimplementedScientistServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&ScientistService_ServiceDesc, srv)
}

func _ScientistService_GetScientist_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetScientistRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ScientistServiceServer).GetScientist(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ScientistService_GetScientist_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ScientistServiceServer).GetScientist(ctx, req.(*GetScientistRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ScientistService_CreateScientist_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateScientistRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ScientistServiceServer).CreateScientist(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ScientistService_CreateScientist_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ScientistServiceServer).CreateScientist(ctx, req.(*CreateScientistRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ScientistService_UpdateScientist_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UpdateScientistRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ScientistServiceServer).UpdateScientist(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ScientistService_UpdateScientist_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ScientistServiceServer).UpdateScientist(ctx, req.(*UpdateScientistRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ScientistService_DeleteScientist_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DeleteScientistRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ScientistServiceServer).DeleteScientist(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ScientistService_DeleteScientist_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ScientistServiceServer).DeleteScientist(ctx, req.(*DeleteScientistRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ScientistService_ListScientists_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListScientistsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ScientistServiceServer).ListScientists(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ScientistService_ListScientists_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ScientistServiceServer).ListScientists(ctx, req.(*ListScientistsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ScientistService_WatchScientists_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(WatchScientistsRequest)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(ScientistServiceServer).WatchScientists(m, &grpc.GenericServerStream[WatchScientistsRequest, ScientistWatchEvent]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type ScientistService_WatchScientistsServer = grpc.ServerStreamingServer[ScientistWatchEvent]

// ScientistService_ServiceDesc is the grpc.ServiceDesc for ScientistService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var ScientistService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "rh_trex.v1.ScientistService",
	HandlerType: (*ScientistServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetScientist",
			Handler:    _ScientistService_GetScientist_Handler,
		},
		{
			MethodName: "CreateScientist",
			Handler:    _ScientistService_CreateScientist_Handler,
		},
		{
			MethodName: "UpdateScientist",
			Handler:    _ScientistService_UpdateScientist_Handler,
		},
		{
			MethodName: "DeleteScientist",
			Handler:    _ScientistService_DeleteScientist_Handler,
		},
		{
			MethodName: "ListScientists",
			Handler:    _ScientistService_ListScientists_Handler,
		},
	},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "WatchScientists",
			Handler:       _ScientistService_WatchScientists_Handler,
			ServerStreams: true,
		},
	},
	Metadata: "rh_trex/v1/scientists.proto",
}
