// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.12
// 	protoc        (unknown)
// source: rh_trex/v1/scientists.proto

package rh_trex_v1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Scientist struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Metadata      *ObjectReference       `protobuf:"bytes,1,opt,name=metadata,proto3" json:"metadata,omitempty"`
	Name          string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Field         string                 `protobuf:"bytes,3,opt,name=field,proto3" json:"field,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Scientist) Reset() {
	*x = Scientist{}
	mi := &file_rh_trex_v1_scientists_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Scientist) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Scientist) ProtoMessage() {}

func (x *Scientist) ProtoReflect() protoreflect.Message {
	mi := &file_rh_trex_v1_scientists_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Scientist.ProtoReflect.Descriptor instead.
func (*Scientist) Descriptor() ([]byte, []int) {
	return file_rh_trex_v1_scientists_proto_rawDescGZIP(), []int{0}
}

func (x *Scientist) GetMetadata() *ObjectReference {
	if x != nil {
		return x.Metadata
	}
	return nil
}

func (x *Scientist) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *Scientist) GetField() string {
	if x != nil {
		return x.Field
	}
	return ""
}

type CreateScientistRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Field         string                 `protobuf:"bytes,2,opt,name=field,proto3" json:"field,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateScientistRequest) Reset() {
	*x = CreateScientistRequest{}
	mi := &file_rh_trex_v1_scientists_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateScientistRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateScientistRequest) ProtoMessage() {}

func (x *CreateScientistRequest) ProtoReflect() protoreflect.Message {
	mi := &file_rh_trex_v1_scientists_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateScientistRequest.ProtoReflect.Descriptor instead.
func (*CreateScientistRequest) Descriptor() ([]byte, []int) {
	return file_rh_trex_v1_scientists_proto_rawDescGZIP(), []int{1}
}

func (x *CreateScientistRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *CreateScientistRequest) GetField() string {
	if x != nil {
		return x.Field
	}
	return ""
}

type GetScientistRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetScientistRequest) Reset() {
	*x = GetScientistRequest{}
	mi := &file_rh_trex_v1_scientists_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetScientistRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetScientistRequest) ProtoMessage() {}

func (x *GetScientistRequest) ProtoReflect() protoreflect.Message {
	mi := &file_rh_trex_v1_scientists_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetScientistRequest.ProtoReflect.Descriptor instead.
func (*GetScientistRequest) Descriptor() ([]byte, []int) {
	return file_rh_trex_v1_scientists_proto_rawDescGZIP(), []int{2}
}

func (x *GetScientistRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

type UpdateScientistRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Name          *string                `protobuf:"bytes,2,opt,name=name,proto3,oneof" json:"name,omitempty"`
	Field         *string                `protobuf:"bytes,3,opt,name=field,proto3,oneof" json:"field,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateScientistRequest) Reset() {
	*x = UpdateScientistRequest{}
	mi := &file_rh_trex_v1_scientists_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateScientistRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateScientistRequest) ProtoMessage() {}

func (x *UpdateScientistRequest) ProtoReflect() protoreflect.Message {
	mi := &file_rh_trex_v1_scientists_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateScientistRequest.ProtoReflect.Descriptor instead.
func (*UpdateScientistRequest) Descriptor() ([]byte, []int) {
	return file_rh_trex_v1_scientists_proto_rawDescGZIP(), []int{3}
}

func (x *UpdateScientistRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *UpdateScientistRequest) GetName() string {
	if x != nil && x.Name != nil {
		return *x.Name
	}
	return ""
}

func (x *UpdateScientistRequest) GetField() string {
	if x != nil && x.Field != nil {
		return *x.Field
	}
	return ""
}

type DeleteScientistRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteScientistRequest) Reset() {
	*x = DeleteScientistRequest{}
	mi := &file_rh_trex_v1_scientists_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteScientistRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteScientistRequest) ProtoMessage() {}

func (x *DeleteScientistRequest) ProtoReflect() protoreflect.Message {
	mi := &file_rh_trex_v1_scientists_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteScientistRequest.ProtoReflect.Descriptor instead.
func (*DeleteScientistRequest) Descriptor() ([]byte, []int) {
	return file_rh_trex_v1_scientists_proto_rawDescGZIP(), []int{4}
}

func (x *DeleteScientistRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

type ListScientistsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Page          int32                  `protobuf:"varint,1,opt,name=page,proto3" json:"page,omitempty"`
	Size          int32                  `protobuf:"varint,2,opt,name=size,proto3" json:"size,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListScientistsRequest) Reset() {
	*x = ListScientistsRequest{}
	mi := &file_rh_trex_v1_scientists_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListScientistsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListScientistsRequest) ProtoMessage() {}

func (x *ListScientistsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_rh_trex_v1_scientists_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListScientistsRequest.ProtoReflect.Descriptor instead.
func (*ListScientistsRequest) Descriptor() ([]byte, []int) {
	return file_rh_trex_v1_scientists_proto_rawDescGZIP(), []int{5}
}

func (x *ListScientistsRequest) GetPage() int32 {
	if x != nil {
		return x.Page
	}
	return 0
}

func (x *ListScientistsRequest) GetSize() int32 {
	if x != nil {
		return x.Size
	}
	return 0
}

type ListScientistsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Items         []*Scientist           `protobuf:"bytes,1,rep,name=items,proto3" json:"items,omitempty"`
	Metadata      *ListMeta              `protobuf:"bytes,2,opt,name=metadata,proto3" json:"metadata,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListScientistsResponse) Reset() {
	*x = ListScientistsResponse{}
	mi := &file_rh_trex_v1_scientists_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListScientistsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListScientistsResponse) ProtoMessage() {}

func (x *ListScientistsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_rh_trex_v1_scientists_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListScientistsResponse.ProtoReflect.Descriptor instead.
func (*ListScientistsResponse) Descriptor() ([]byte, []int) {
	return file_rh_trex_v1_scientists_proto_rawDescGZIP(), []int{6}
}

func (x *ListScientistsResponse) GetItems() []*Scientist {
	if x != nil {
		return x.Items
	}
	return nil
}

func (x *ListScientistsResponse) GetMetadata() *ListMeta {
	if x != nil {
		return x.Metadata
	}
	return nil
}

type DeleteScientistResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteScientistResponse) Reset() {
	*x = DeleteScientistResponse{}
	mi := &file_rh_trex_v1_scientists_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteScientistResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteScientistResponse) ProtoMessage() {}

func (x *DeleteScientistResponse) ProtoReflect() protoreflect.Message {
	mi := &file_rh_trex_v1_scientists_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteScientistResponse.ProtoReflect.Descriptor instead.
func (*DeleteScientistResponse) Descriptor() ([]byte, []int) {
	return file_rh_trex_v1_scientists_proto_rawDescGZIP(), []int{7}
}

type WatchScientistsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *WatchScientistsRequest) Reset() {
	*x = WatchScientistsRequest{}
	mi := &file_rh_trex_v1_scientists_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *WatchScientistsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*WatchScientistsRequest) ProtoMessage() {}

func (x *WatchScientistsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_rh_trex_v1_scientists_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use WatchScientistsRequest.ProtoReflect.Descriptor instead.
func (*WatchScientistsRequest) Descriptor() ([]byte, []int) {
	return file_rh_trex_v1_scientists_proto_rawDescGZIP(), []int{8}
}

type ScientistWatchEvent struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Type          EventType              `protobuf:"varint,1,opt,name=type,proto3,enum=rh_trex.v1.EventType" json:"type,omitempty"`
	Scientist     *Scientist             `protobuf:"bytes,2,opt,name=scientist,proto3" json:"scientist,omitempty"`
	ResourceId    string                 `protobuf:"bytes,3,opt,name=resource_id,json=resourceId,proto3" json:"resource_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ScientistWatchEvent) Reset() {
	*x = ScientistWatchEvent{}
	mi := &file_rh_trex_v1_scientists_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ScientistWatchEvent) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ScientistWatchEvent) ProtoMessage() {}

func (x *ScientistWatchEvent) ProtoReflect() protoreflect.Message {
	mi := &file_rh_trex_v1_scientists_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ScientistWatchEvent.ProtoReflect.Descriptor instead.
func (*ScientistWatchEvent) Descriptor() ([]byte, []int) {
	return file_rh_trex_v1_scientists_proto_rawDescGZIP(), []int{9}
}

func (x *ScientistWatchEvent) GetType() EventType {
	if x != nil {
		return x.Type
	}
	return EventType_EVENT_TYPE_UNSPECIFIED
}

func (x *ScientistWatchEvent) GetScientist() *Scientist {
	if x != nil {
		return x.Scientist
	}
	return nil
}

func (x *ScientistWatchEvent) GetResourceId() string {
	if x != nil {
		return x.ResourceId
	}
	return ""
}

var File_rh_trex_v1_scientists_proto protoreflect.FileDescriptor

const file_rh_trex_v1_scientists_proto_rawDesc = "" +
	"\n" +
	"\x1brh_trex/v1/scientists.proto\x12\n" +
	"rh_trex.v1\x1a\x17rh_trex/v1/common.proto\"n\n" +
	"\tScientist\x127\n" +
	"\bmetadata\x18\x01 \x01(\v2\x1b.rh_trex.v1.ObjectReferenceR\bmetadata\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12\x14\n" +
	"\x05field\x18\x03 \x01(\tR\x05field\"B\n" +
	"\x16CreateScientistRequest\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12\x14\n" +
	"\x05field\x18\x02 \x01(\tR\x05field\"%\n" +
	"\x13GetScientistRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\"o\n" +
	"\x16UpdateScientistRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x17\n" +
	"\x04name\x18\x02 \x01(\tH\x00R\x04name\x88\x01\x01\x12\x19\n" +
	"\x05field\x18\x03 \x01(\tH\x01R\x05field\x88\x01\x01B\a\n" +
	"\x05_nameB\b\n" +
	"\x06_field\"(\n" +
	"\x16DeleteScientistRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\"?\n" +
	"\x15ListScientistsRequest\x12\x12\n" +
	"\x04page\x18\x01 \x01(\x05R\x04page\x12\x12\n" +
	"\x04size\x18\x02 \x01(\x05R\x04size\"w\n" +
	"\x16ListScientistsResponse\x12+\n" +
	"\x05items\x18\x01 \x03(\v2\x15.rh_trex.v1.ScientistR\x05items\x120\n" +
	"\bmetadata\x18\x02 \x01(\v2\x14.rh_trex.v1.ListMetaR\bmetadata\"\x19\n" +
	"\x17DeleteScientistResponse\"\x18\n" +
	"\x16WatchScientistsRequest\"\x96\x01\n" +
	"\x13ScientistWatchEvent\x12)\n" +
	"\x04type\x18\x01 \x01(\x0e2\x15.rh_trex.v1.EventTypeR\x04type\x123\n" +
	"\tscientist\x18\x02 \x01(\v2\x15.rh_trex.v1.ScientistR\tscientist\x12\x1f\n" +
	"\vresource_id\x18\x03 \x01(\tR\n" +
	"resourceId2\x85\x04\n" +
	"\x10ScientistService\x12F\n" +
	"\fGetScientist\x12\x1f.rh_trex.v1.GetScientistRequest\x1a\x15.rh_trex.v1.Scientist\x12L\n" +
	"\x0fCreateScientist\x12\".rh_trex.v1.CreateScientistRequest\x1a\x15.rh_trex.v1.Scientist\x12L\n" +
	"\x0fUpdateScientist\x12\".rh_trex.v1.UpdateScientistRequest\x1a\x15.rh_trex.v1.Scientist\x12Z\n" +
	"\x0fDeleteScientist\x12\".rh_trex.v1.DeleteScientistRequest\x1a#.rh_trex.v1.DeleteScientistResponse\x12W\n" +
	"\x0eListScientists\x12!.rh_trex.v1.ListScientistsRequest\x1a\".rh_trex.v1.ListScientistsResponse\x12X\n" +
	"\x0fWatchScientists\x12\".rh_trex.v1.WatchScientistsRequest\x1a\x1f.rh_trex.v1.ScientistWatchEvent0\x01BaZ_github.com/openshift-online/rh-trex-ai/components/api-server/pkg/api/grpc/rh_trex/v1;rh_trex_v1b\x06proto3"

var (
	file_rh_trex_v1_scientists_proto_rawDescOnce sync.Once
	file_rh_trex_v1_scientists_proto_rawDescData []byte
)

func file_rh_trex_v1_scientists_proto_rawDescGZIP() []byte {
	file_rh_trex_v1_scientists_proto_rawDescOnce.Do(func() {
		file_rh_trex_v1_scientists_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_rh_trex_v1_scientists_proto_rawDesc), len(file_rh_trex_v1_scientists_proto_rawDesc)))
	})
	return file_rh_trex_v1_scientists_proto_rawDescData
}

var file_rh_trex_v1_scientists_proto_msgTypes = make([]protoimpl.MessageInfo, 10)
var file_rh_trex_v1_scientists_proto_goTypes = []any{
	(*Scientist)(nil),               // 0: rh_trex.v1.Scientist
	(*CreateScientistRequest)(nil),  // 1: rh_trex.v1.CreateScientistRequest
	(*GetScientistRequest)(nil),     // 2: rh_trex.v1.GetScientistRequest
	(*UpdateScientistRequest)(nil),  // 3: rh_trex.v1.UpdateScientistRequest
	(*DeleteScientistRequest)(nil),  // 4: rh_trex.v1.DeleteScientistRequest
	(*ListScientistsRequest)(nil),   // 5: rh_trex.v1.ListScientistsRequest
	(*ListScientistsResponse)(nil),  // 6: rh_trex.v1.ListScientistsResponse
	(*DeleteScientistResponse)(nil), // 7: rh_trex.v1.DeleteScientistResponse
	(*WatchScientistsRequest)(nil),  // 8: rh_trex.v1.WatchScientistsRequest
	(*ScientistWatchEvent)(nil),     // 9: rh_trex.v1.ScientistWatchEvent
	(*ObjectReference)(nil),         // 10: rh_trex.v1.ObjectReference
	(*ListMeta)(nil),                // 11: rh_trex.v1.ListMeta
	(EventType)(0),                  // 12: rh_trex.v1.EventType
}
var file_rh_trex_v1_scientists_proto_depIdxs = []int32{
	10, // 0: rh_trex.v1.Scientist.metadata:type_name -> rh_trex.v1.ObjectReference
	0,  // 1: rh_trex.v1.ListScientistsResponse.items:type_name -> rh_trex.v1.Scientist
	11, // 2: rh_trex.v1.ListScientistsResponse.metadata:type_name -> rh_trex.v1.ListMeta
	12, // 3: rh_trex.v1.ScientistWatchEvent.type:type_name -> rh_trex.v1.EventType
	0,  // 4: rh_trex.v1.ScientistWatchEvent.scientist:type_name -> rh_trex.v1.Scientist
	2,  // 5: rh_trex.v1.ScientistService.GetScientist:input_type -> rh_trex.v1.GetScientistRequest
	1,  // 6: rh_trex.v1.ScientistService.CreateScientist:input_type -> rh_trex.v1.CreateScientistRequest
	3,  // 7: rh_trex.v1.ScientistService.UpdateScientist:input_type -> rh_trex.v1.UpdateScientistRequest
	4,  // 8: rh_trex.v1.ScientistService.DeleteScientist:input_type -> rh_trex.v1.DeleteScientistRequest
	5,  // 9: rh_trex.v1.ScientistService.ListScientists:input_type -> rh_trex.v1.ListScientistsRequest
	8,  // 10: rh_trex.v1.ScientistService.WatchScientists:input_type -> rh_trex.v1.WatchScientistsRequest
	0,  // 11: rh_trex.v1.ScientistService.GetScientist:output_type -> rh_trex.v1.Scientist
	0,  // 12: rh_trex.v1.ScientistService.CreateScientist:output_type -> rh_trex.v1.Scientist
	0,  // 13: rh_trex.v1.ScientistService.UpdateScientist:output_type -> rh_trex.v1.Scientist
	7,  // 14: rh_trex.v1.ScientistService.DeleteScientist:output_type -> rh_trex.v1.DeleteScientistResponse
	6,  // 15: rh_trex.v1.ScientistService.ListScientists:output_type -> rh_trex.v1.ListScientistsResponse
	9,  // 16: rh_trex.v1.ScientistService.WatchScientists:output_type -> rh_trex.v1.ScientistWatchEvent
	11, // [11:17] is the sub-list for method output_type
	5,  // [5:11] is the sub-list for method input_type
	5,  // [5:5] is the sub-list for extension type_name
	5,  // [5:5] is the sub-list for extension extendee
	0,  // [0:5] is the sub-list for field type_name
}

func init() { file_rh_trex_v1_scientists_proto_init() }
func file_rh_trex_v1_scientists_proto_init() {
	if File_rh_trex_v1_scientists_proto != nil {
		return
	}
	file_rh_trex_v1_common_proto_init()
	file_rh_trex_v1_scientists_proto_msgTypes[3].OneofWrappers = []any{}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_rh_trex_v1_scientists_proto_rawDesc), len(file_rh_trex_v1_scientists_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   10,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_rh_trex_v1_scientists_proto_goTypes,
		DependencyIndexes: file_rh_trex_v1_scientists_proto_depIdxs,
		MessageInfos:      file_rh_trex_v1_scientists_proto_msgTypes,
	}.Build()
	File_rh_trex_v1_scientists_proto = out.File
	file_rh_trex_v1_scientists_proto_goTypes = nil
	file_rh_trex_v1_scientists_proto_depIdxs = nil
}
