package main

import (
	"bytes"
	"os"
	"path/filepath"
	"sort"
	"testing"
	"text/template"
)

func TestGeneratedEntityOpenAPIDocumentsCompleteCRUDContract(t *testing.T) {
	templatePath := filepath.Join("..", "..", "templates", "generate-openapi-kind.txt")
	contents, err := os.ReadFile(templatePath)
	if err != nil {
		t.Fatalf("read entity OpenAPI template: %v", err)
	}

	parsed, err := template.New(filepath.Base(templatePath)).Parse(string(contents))
	if err != nil {
		t.Fatalf("parse entity OpenAPI template: %v", err)
	}

	var generated bytes.Buffer
	err = parsed.Execute(&generated, struct {
		Project             string
		Kind                string
		KindPlural          string
		KindLowerSingular   string
		KindLowerPlural     string
		KindSnakeCasePlural string
		Fields              []struct{}
	}{
		Project:             "example",
		Kind:                "Widget",
		KindPlural:          "Widgets",
		KindLowerSingular:   "widget",
		KindLowerPlural:     "widgets",
		KindSnakeCasePlural: "widgets",
	})
	if err != nil {
		t.Fatalf("render entity OpenAPI template: %v", err)
	}

	directory := t.TempDir()
	entityPath := filepath.Join(directory, "openapi.widgets.yaml")
	if err := os.WriteFile(entityPath, generated.Bytes(), 0o600); err != nil {
		t.Fatalf("write rendered entity OpenAPI document: %v", err)
	}
	rootPath := filepath.Join(directory, "openapi.yaml")
	if err := os.WriteFile(rootPath, []byte(widgetRootOpenAPI), 0o600); err != nil {
		t.Fatalf("write root OpenAPI document: %v", err)
	}

	operations := loadResolvedOpenAPIOperations(t, rootPath)
	operationIDs := make([]string, 0, len(operations))
	for _, operation := range operations {
		operationIDs = append(operationIDs, operation.OperationID)
		if operation.OperationID == "deleteWidget" {
			if len(operation.Responses) != 5 || operation.Responses["204"] == nil {
				t.Fatalf("deleteWidget responses = %#v, want 204 plus declared errors", operation.Responses)
			}
		}
	}
	sort.Strings(operationIDs)
	want := []string{"createWidget", "deleteWidget", "getWidget", "listWidgets", "updateWidget"}
	if len(operationIDs) != len(want) {
		t.Fatalf("generated operation IDs = %v, want %v", operationIDs, want)
	}
	for index := range want {
		if operationIDs[index] != want[index] {
			t.Fatalf("generated operation IDs = %v, want %v", operationIDs, want)
		}
	}
}

const widgetRootOpenAPI = `openapi: 3.0.3
info:
  title: generated entity test
  version: 1.0.0
paths:
  /api/example/v1/widgets:
    $ref: 'openapi.widgets.yaml#/paths/~1api~1example~1v1~1widgets'
  /api/example/v1/widgets/{id}:
    $ref: 'openapi.widgets.yaml#/paths/~1api~1example~1v1~1widgets~1{id}'
components:
  securitySchemes:
    Bearer:
      type: http
      scheme: bearer
  schemas:
    ObjectReference:
      type: object
    List:
      type: object
    Error:
      type: object
`
